### ISSUE TITLE
 'ASP.default_aspx' does not contain a definition for 'LogoutButtonClick'

### ISSUE THREAD

**Issue by pkaak** [cedrozor/myrtille#100]
So installing 1.8 over 1.7 gave some errors. The uninstall didn't work right (something with uninstall with value null not accepted), so after some hunting to remove everything manual of 1.7.
After installing 1.8 and starting myrtille again I get a server error. Deinstall of myrtille still gives the same error, even with 1.8. 

The server error is: 

CS1061: 'ASP.default_aspx' does not contain a definition for 'LogoutButtonClick' and no extension method 'LogoutButtonClick' accepting a first argument of type 'ASP.default_aspx' could be found (are you missing a using directive or an assembly reference?)

Line 159:                
Line 160:                    
Line 161:                    <input type="button" runat="server" id="logout" value="Logout" onserverclick="LogoutButtonClick" title="Logout"/>
Line 162:
Line 163:                </div>

Source File: c:\Program Files (x86)\Myrtille\Default.aspx    Line: 161 

c:\windows\system32\inetsrv> "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /t:library /utf8output /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\d4750317\00266ede_88cad301\CertEnroll_Interop.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\7be32bb7\002752c7_cecad301\Myrtille.MFAProviders.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\5054b81b\00950950_41a0d301\Myrtille.Services.Contracts.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\a33b85a6\005c32e8_8f75cd01\System.Data.SqlServerCe.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\390a9ab9\00f7b1f8_004cd301\EntityFramework.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Entity\v4.0_4.0.0.0__b77a5c561934e089\System.Web.Entity.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_global.asax.3d79cjbh.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\0cdfedf3\0024e3f9_004cd301\EntityFramework.SqlServer.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\8eae7ad0\00c23a51_41a0d301\Myrtille.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\dd856b52\00ca80f7_004cd301\EntityFramework.SqlServerCompact.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\5789ad87\00d84772_999fd301\OASIS.Integration.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\fa3ad1f8\002752c7_cecad301\Myrtille.Enterprise.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\assembly\GAC_MSIL\Microsoft.Web.Administration\7.0.0.0__31bf3856ad364e35\Microsoft.Web.Administration.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\90f0b18a\00037ade_4198d201\log4net.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\836da31e\00c23a51_41a0d301\Myrtille.Common.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\assembly\dl3\3057dbdf\008ca35a_7b36d101\Microsoft.WebSockets.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /out:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.dll" /debug- /optimize+ /win32res:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\hba1h1v4.res" /w:4 /nowarn:1659;1699;1701;612;618 /warnaserror-  "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.5.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.4.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.2.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.7.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.0.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.3.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.1.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.8.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\myrtille\b9b76342\eb04360f\App_Web_hba1h1v4.6.cs"

Microsoft (R) Visual C# Compiler version 4.7.2558.0

for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

c:\Program Files (x86)\Myrtille\Default.aspx(161,65): error CS1061: 'ASP.default_aspx' does not contain a definition for 'LogoutButtonClick' and no extension method 'LogoutButtonClick' accepting a first argument of type 'ASP.default_aspx' could be found (are you missing a using directive or an assembly reference?)
c:\Program Files (x86)\Myrtille\Default.aspx(161,65): error CS1061: 'ASP.default_aspx' does not contain a definition for 'LogoutButtonClick' and no extension method 'LogoutButtonClick' accepting a first argument of type 'ASP.default_aspx' could be found (are you missing a using directive or an assembly reference?)
c:\Program Files (x86)\Myrtille\Default.aspx(166,98): error CS1061: 'ASP.default_aspx' does not contain a definition for 'hostsList_ItemDataBound' and no extension method 'hostsList_ItemDataBound' accepting a first argument of type 'ASP.default_aspx' could be found (are you missing a using directive or an assembly reference?)
c:\Program Files (x86)\Myrtille\Default.aspx(166,98): error CS1061: 'ASP.default_aspx' does not contain a definition for 'hostsList_ItemDataBound' and no extension method 'hostsList_ItemDataBound' accepting a first argument of type 'ASP.default_aspx' could be found (are you missing a using directive or an assembly reference?)
c:\Program Files (x86)\Myrtille\Default.aspx(236,137): error CS1061: 'Myrtille.Web.RemoteSession' does not contain a definition for 'ExitCode' and no extension method 'ExitCode' accepting a first argument of type 'Myrtille.Web.RemoteSession' could be found (are you missing a using directive or an assembly reference?)
c:\Program Files (x86)\Myrtille\Default.aspx(236,167): error CS1061: 'Myrtille.Web.RemoteSession' does not contain a definition for 'ExitCode' and no extension method 'ExitCode' accepting a first argument of type 'Myrtille.Web.RemoteSession' could be found (are you missing a using directive or an assembly reference?)

**Comment by pkaak** [comment]
After stopping the myrtille service, stopping the application myrtille application pool and overwrite all files it seems to work. 
But that error at uninstall seems to be a big problem for upgrading.

**Comment by cedrozor** [comment]
Hi Patrick,

It looks like you had a dlls mixup with 1.7.0 and 1.8.1 after the failed 1.7.0 uninstall (do you have more details about this? maybe in the windows system or application event logs?).

You can try the following: uninstall myrtille and check the myrtille folder; there shouldn't be anything left except the log folder (and the data folder, if you enabled the enterprise mode). Remove the myrtille folder completely then reinstall.

Please tell me if all is fine after that.

Cedric

**Comment by cedrozor** [comment]
Our replies just crossed almost at the same time. Glad it's working now.

When you installed the 1.8.1, did you had a message asking you to remove first the 1.7.0? I enforced such behavior to avoid such versions mixup.

**Comment by cedrozor** [comment]
Hmm I just tried the uninstall (1.7.0) / install (1.8.1) process and may have understood what happened.

When you uninstall, you should have a dialog box saying that Myrtille.Services is running and should be stopped before continuing. If you don't stop it, this could lead to the installer being unable to update it and thus the install to be incomplete.

I tested that use case some time ago and didn't had any problem.. but the Myrtille.Services evolved quite much recently and this could now be a problem. I'll open a new issue.

**Comment by cedrozor** [comment]
Well, I checked the code I found that I already handled that case! :)
Sorry for spamming that thread. Closed.
