### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#107]
I am opening a connection with Myrtille passing as a program parameter. I need to identify which application opened the session, for example:

https://[HOST]?__EVENTTARGET=&__EVENTARGUMENT=&server=[SERVER]&user=[USER]&password=[PASSWORD]&program=notepad.exe&connect=Connect%2521

In the above example the connection was opened by the notepad.exe application. Is there any way in myrtille to add environment variables in the session, either through the url or through freerdp? In this case I could create an environment variable with the name of my application.

**Comment by cedrozor** [comment]
This is the other way around, the application is opened on connect. wfreerdp is just a client, it doesn't (and couldn't) set any environment variable on the target server.

You could have a batch or .cmd script on your target server which would take in argument (%1) the program to run, create an environment variable from it and run the program. Then pass the batch or .cmd script as "&program=" param into the myrtille url.

**Comment by cedrozor** [comment]
closing, reopen if needed
