### ISSUE TITLE
Arrow keys don't work.

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#11]
Have you noticed that the arrow keys don't work? I have notepad open to test it and looks to be converting the arrow keys to the numpad versions. for example, pressing the up arrow returns an '8'

**Comment by cedrozor** [comment]
Hi, Did you checked if your numlock key was active or not?

**Comment by tmakaro** [comment]
I tried that. It didn't seem to matter

**Comment by tmakaro** [comment]
hmm, its working now. strange. oh well :)
