### ISSUE TITLE
Keyboard input issues

### ISSUE THREAD

**Issue by mapl** [cedrozor/myrtille#112]
Pressing cursor keys, number characters are being printed instead of the expected cursor function, making it hard to navigate :)

e.g.: 
UP = 8 

Just like when typing on the num block

Where is myrtille installed on?
Hyper-V  Windows Server 2016 VM, accessing the same VM.

**Comment by cedrozor** [comment]
It happens sometimes, a desynchro between the rdp server and client; see this previously reported issue: https://github.com/cedrozor/myrtille/issues/77

**Comment by mapl** [comment]
Thank you for pointing me to the known issue. The only way to mitigate the behavior was to actually restart the VM. Alt-GR is not working at all. For instance you want to type a pipe "|" character.

**Comment by cedrozor** [comment]
Which client device/OS are you using? someone reported a similar issue under Ubuntu (https://github.com/cedrozor/myrtille/issues/92).

I will investigate it.

**Comment by mapl** [comment]
Myrtille server running on Windows Server 2016 VM

Tested on Client OS Windows 7/10 using chrome latest and firefox latest with same results

I had to reboot the VM again since it stopped working out of nowhere. will keep monitoring this

**Comment by cedrozor** [comment]
Thanks for the details. What keyboard/language mapping are you using?

I just tested under windows 7 + chrome (latest) with myrtille installed on a windows 10 and accessing the same machine (localhost), all went ok.

My keyboard is azerty/FR (France), I tested with pipe "|" using AltGr + the "6" key on my keyboard layout.

**Comment by mapl** [comment]
I have configured a QWERTZ Keyboard Layout (German). When I press "ALT GR" + "-"(next to right shift button), I finally get a Backslash "\".
However, using an ordinary RDP Connection, I have no issues at all.

**Comment by cedrozor** [comment]
Thanks, I'll test with such layout; I tried to make something universal, but I may have to use some config files for different keyboards mapping...

**Comment by cedrozor** [comment]
duplicate with #92

**Comment by rhessinger** [comment]
I'm experiencing the same issues with the arrow keys.  I'm connecting to a windows 10 computer remotely from a windows 10 computer using chrome.

**Comment by cedrozor** [comment]
numlock is probably inverted; it happens (see #77). Try to switch on/off numlock or reconnect the session.

**Comment by rhessinger** [comment]
I have tried that and it still does not work.  I'm using a standard US keyboard layout.

**Comment by cedrozor** [comment]
Your session is probably bugged, or you have a key modifier being stuck. Try to press the "alt" key, for a try.

**Comment by mapl** [comment]
A temporay fix for me was to reboot the VM.

**Comment by rhessinger** [comment]
Rebooting my computer (the one i'm RDPing into) fixed the arrow key thing.  That is very weird.

**Comment by cedrozor** [comment]
Just closing the session (logout, not just disconnect)  / opening a new one
should be enough.

This is a well known issue with rdp (
https://social.technet.microsoft.com/Forums/forefront/en-US/c002126a-0f50-49e0-977c-d66ec051c880/num-lockcap-lock-are-working-in-reverse-on-terminal-server-2012-r2?forum=winserver8gen
)
