### ISSUE TITLE
Specify RDS collection ID when connecting to RD Connection Broker

### ISSUE THREAD

**Issue by kevxlreee** [cedrozor/myrtille#115]
Does Myrtille support connection hints for the RDS collection ID (loadbalanceinfo parameter in the RDP file) to be able to connect to RD Connection Broker and be redirected to the appropriate RD Virtualization Host VM?

I have a Sever 2016 VM with RD Gateway/Connection Broker/Licensing/Web Access and another server specifically dedicated as an RD Virtualization Host. Connecting via Myrtille to the RD GW/CB/Licensing/WA server, with client credentials, fails because no VM resource ID hints are passed by Myrtille. Is there a way to enable this?

**Comment by cedrozor** [comment]
No, you can only specify the RD host or connection broker hostname, FQDN or IP with myrtille. I'm not even sure FreeRDP (on which myrtille relies) could do what you are looking for.

But perhaps you could configure your RDS collection and connection broker to redirect to a specific host when the connection comes from the myrtille gateway.

**Comment by kevxlreee** [comment]
Thanks - unfortunately we cannot just configure a default collection ID because there are multiple collections that all have to be accessible by Myrtille.
