### ISSUE TITLE
netsh port forwarding and Myrtille

### ISSUE THREAD

**Issue by windylea** [cedrozor/myrtille#118]
I ran this command to forward traffic from port `12345` to default RDP port `3389`:

`netsh interface portproxy add v4tov4 listenport=12345 listenaddress=0.0.0.0 connectaddress=127.0.0.1 connectport=3389 protocol=tcp`

After that, I was able to remote control my computer by connecting to `[public_server_address]:12345` using other RDP clients. But when I tried with Myrtille, connecting to `[public_server_address]:12345` results in `The remote connection failed or was closed unexpected` and connecting to `localhost:12345` results in `The remote connection failed due to invalid or unreachable server address`.

So is there anything I can do to make it work? Thanks.

**Comment by cedrozor** [comment]
The difference with others rdp clients is that myrtille is running on your server itself, and so is wfreerdp (its rdp client).

So you don't have to use your public ip (or the connection will exit and re-enter your network, which can lead to some unexpected issues) neither the port 12345.

You just have to connect with `localhost` (wfreerdp use the port 3389 by default).

**Comment by windylea** [comment]
I know that I just have to connect with `localhost` but beside port 3389, I want to be able to connect with  another port 12345 as well (for, uhm, some reasons) so I forwarded all incoming traffic from port 12345 to port 3389 using the above command. I tried to use Myrtille to connect to `localhost:12345` but not successful. So I'm asking if may be you know the reason behind that..

**Comment by cedrozor** [comment]
I you made the port redirection on the machine on which myrtille is installed (not on your NAT or an external proxy), it should work indeed.

Did you tried to connect on the machine itself, using mstsc with `localhost:12345`?

I understand the reason for using a different port (port scanning, among others).

**Comment by windylea** [comment]
I already tried to connect on the machine itself, using mstsc with `localhost:12345` and it works fine. For this issue, I have to use Myrtille to connect to address `127.0.0.1:12345` instead. Not sure why I cannot use `localhost:12345` , but since it's okay now for me then please close the issue if you want.

**Comment by cedrozor** [comment]
If you have ipv6 enabled on your machine, `localhost` may be resolved to `::1` by wfreerdp. The port redirection you have is for ipv4 only, so that's must be the problem. You should add the netsh rule:

`netsh interface portproxy add v6tov4 listenport=12345 connectaddress=127.0.0.1 connectport=3389 protocol=tcp`

http://virot.eu/using-windows-builtin-portproxy-to-forward-ports/

**Comment by windylea** [comment]
That's indeed solved my issue completely. Thank you very much for your help!
