### ISSUE TITLE
new install. freerdp won't start

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#12]
Hi Cedric, this one has me stumped. I just tried a new server and it looks like freerdp won't start. Its a window 2012 r2 server completely up to date. It also has the c++ 2015 libraries(both x64 and x86). There is nothing interesting in the logs but the event viewer shows the following:

Faulting application name: FreeRDP.wfreerdp.exe, version: 0.0.0.0, time stamp: 0x5766ba49
Faulting module name: ntdll.dll, version: 6.3.9600.18233, time stamp: 0x56bb4e1d
Exception code: 0xc0000374
Fault offset: 0x000e6054
Faulting process id: 0x4ec
Faulting application start time: 0x01d1f8b17f270433
Faulting application path: C:\Program Files (x86)\Myrtille\bin\FreeRDP.wfreerdp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: bdc35e5c-64a4-11e6-80bf-1458d05b72a1
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: FreeRDP.wfreerdp.exe
P2: 0.0.0.0
P3: 5766ba49
P4: StackHash_cc59
P5: 6.3.9600.18233
P6: 56bb4e1d
P7: c0000374
P8: PCH_70_FROM_ntdll+0x0003C7EC
P9: 
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_FreeRDP.wfreerdp_b43f76a1a8140afaedb3deb25d15c757962a961_8bebd625_12495b37

Analysis symbol: 
Rechecking for solution: 0
Report Id: bdc35e5c-64a4-11e6-80bf-1458d05b72a1
Report Status: 4100
Hashed bucket: 

Here is the attach file mentioned above:

Version=1
EventType=APPCRASH
EventTime=131159305415146734
ReportType=2
Consent=1
ReportIdentifier=bdc35e5d-64a4-11e6-80bf-1458d05b72a1
IntegratorReportIdentifier=bdc35e5c-64a4-11e6-80bf-1458d05b72a1
WOW64=1
NsAppName=FreeRDP.wfreerdp.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=FreeRDP.wfreerdp.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5766ba49
Sig[3].Name=Fault Module Name
Sig[3].Value=StackHash_cc59
Sig[4].Name=Fault Module Version
Sig[4].Value=6.3.9600.18233
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=56bb4e1d
Sig[6].Name=Exception Code
Sig[6].Value=c0000374
Sig[7].Name=Exception Offset
Sig[7].Value=PCH_70_FROM_ntdll+0x0003C7EC
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=cc59
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=cc593782a6638c65d26dfd6713a5bbda
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=b3b9
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=b3b9d35b50d6a30b4b18e55d7c18bf95
UI[2]=C:\Program Files (x86)\Myrtille\bin\FreeRDP.wfreerdp.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=FreeRDP.wfreerdp.exe stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Program Files (x86)\Myrtille\bin\FreeRDP.wfreerdp.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\SYSTEM32\WS2_32.dll
LoadedModule[5]=C:\Program Files (x86)\Myrtille\bin\LIBEAY32.dll
LoadedModule[6]=C:\Windows\SYSTEM32\USER32.dll
LoadedModule[7]=C:\Windows\SYSTEM32\GDI32.dll
LoadedModule[8]=C:\Windows\SYSTEM32\ole32.dll
LoadedModule[9]=C:\Program Files (x86)\Myrtille\bin\FreeRDP.libfreerdpchanman.dll
LoadedModule[10]=C:\Program Files (x86)\Myrtille\bin\FreeRDP.libfreerdp.dll
LoadedModule[11]=C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.18405_none_dad773c85bcd115f\gdiplus.dll
LoadedModule[12]=C:\Windows\SYSTEM32\MSVCP140.dll
LoadedModule[13]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[14]=C:\Windows\SYSTEM32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[15]=C:\Windows\SYSTEM32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[16]=C:\Windows\SYSTEM32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[17]=C:\Windows\SYSTEM32\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[18]=C:\Windows\SYSTEM32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[19]=C:\Windows\SYSTEM32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[20]=C:\Windows\SYSTEM32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[21]=C:\Windows\SYSTEM32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[22]=C:\Windows\SYSTEM32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[23]=C:\Windows\SYSTEM32\NSI.dll
LoadedModule[24]=C:\Windows\SYSTEM32\RPCRT4.dll
LoadedModule[25]=C:\Windows\SYSTEM32\ADVAPI32.dll
LoadedModule[26]=C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_5094ca96bcb6b2bb\MSVCR90.dll
LoadedModule[27]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[28]=C:\Windows\SYSTEM32\msvcrt.dll
LoadedModule[29]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[30]=C:\Program Files (x86)\Myrtille\bin\SSLEAY32.dll
LoadedModule[31]=C:\Windows\SYSTEM32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[32]=C:\Windows\SYSTEM32\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[33]=C:\Windows\SYSTEM32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[34]=C:\Windows\SYSTEM32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[35]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[36]=C:\Windows\SYSTEM32\ucrtbase.DLL
LoadedModule[37]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[38]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[39]=C:\Windows\system32\napinsp.dll
LoadedModule[40]=C:\Windows\system32\NLAapi.dll
LoadedModule[41]=C:\Windows\System32\mswsock.dll
LoadedModule[42]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[43]=C:\Windows\System32\winrnr.dll
LoadedModule[44]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[45]=C:\Windows\System32\rasadhlp.dll
LoadedModule[46]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[47]=C:\Windows\system32\rsaenh.dll
LoadedModule[48]=C:\Windows\SYSTEM32\bcrypt.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=FreeRDP.wfreerdp.exe
AppPath=C:\Program Files (x86)\Myrtille\bin\FreeRDP.wfreerdp.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=6EC80E5DD029F5134E8F9E54D5B88E91

**Comment by cedrozor** [comment]
Did you disabled the NLA on the server you try to connect? on Windows Server 2012 R2, unchecking the NLA requirement (control panel > system > remote access settings) isn't enough.

Even with freerdp started with the "--no-nla" option, the server ask for it (it doesn't _require_ it but still ask for it...) which fails if the certificate doesn't match (which occurs most of the time because who care creating certificates for rdp servers? ^^).

If you installed the RDS role and host feature, you should be able to configure it and select "Standard RDP Authentication". Otherwise, you can execute "RDPSetup.reg", bundled with myrtille, on the rdp server(s) to do it automatically (direct registry config).

Fortunally, this recurent problem will stop soon because I'm upgrading myrtille to the latest version of freerdp. It will work with NLA servers out of the box, support clipboard, Hyper-V connections, hardware acceleration and much more ;)

**Comment by tmakaro** [comment]
The RDPSetup.reg did it. Thank you! 

PS, I’m looking forward to seeing the new freerdp version!

Troy
