### ISSUE TITLE
Hide toolbar during remote session

### ISSUE THREAD

**Issue by windylea** [cedrozor/myrtille#120]
The toolbar is taking up space of the screen during remote session, not too much but I think it would be better if it can be hidden and showed up only when needed.

So I came up with this little script (tested to work with the ye olde Internet Explorer 6), which you can check in the attached file. Hope that will be useful and be considered in next version of Myrtille.

[toolbar.zip](https://github.com/cedrozor/myrtille/files/2152937/toolbar.zip)

**Comment by cedrozor** [comment]
It's indeed a good idea! if possible, could you please make a pull request, for easier integration (and automatically credit you as contributor)?

Thanks :)

**Comment by cedrozor** [comment]
Done into Myrtille 2.0.0! :)
