### ISSUE TITLE
Change Myrtille Services port

### ISSUE THREAD

**Issue by Arcath** [cedrozor/myrtille#121]
Like **a lot** of services Myrtille uses port _8080_ to talk to its Service which is always in use on my servers by something else.

I can change it in the config files but its a bit of a pain to do after every update.

Would it not make more sense to ask for a port during install?

**Comment by cedrozor** [comment]
Good idea yes. In fact, I had such configuration back in time into the installer but, at a moment, I decided to simplify it. But it's relevant for many people, so I'll add it again.

**Comment by cedrozor** [comment]
Myrtille version 2.0.0, just released, provides the ability to change the port on install :)
