### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by jah29m** [cedrozor/myrtille#122]
The file transfer option when downloading from the Myrtille server. 2 things.

Is it possible to download from the RDP machine you're connecting to (instead of having to copy files to server hosting myrtile)?

The file transfer download option selects the first file, regardless of what is selected in the dropdown.

BTW: great job on the new features!

**Comment by cedrozor** [comment]
The myrtille file transfer is designed to work with a domain and roaming accounts. Both the myrtille gateway and the rdp server must be members of the same domain. When you connect the rdp server, you have to specify the domain name and it should work (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#file-transfer)
