### ISSUE TITLE
VS 2017 Build Error/Failed

### ISSUE THREAD

**Issue by Manthan2611** [cedrozor/myrtille#125]
Hi,
Getting error while building FreeRDP repo
CMAKE GUI log: [pastebin](https://pastebin.com/8JwYH70C).
Build log: [pastebin](https://pastebin.com/5tx8urpG ).  
using visual studio 15 2017 Win64 Generator. 

Any suggestions? 

Thank you.

**Comment by Manthan2611** [comment]
Downloaded v2.0 and It build successfully 👍 

Thank you :)

**Comment by cedrozor** [comment]
Glad it's working :) you probably missed the right openssl libs (1.1.0h, the full 32bits version from https://slproweb.com/products/Win32OpenSSL.html). 

It's autodetected by cmake and allows for a proper configuration of the solution (projects); even if the build itself uses a nuget package with static libs (https://github.com/cedrozor/FreeRDP/blob/master/libfreerdp/packages.config)
