### ISSUE TITLE
ipv6?

### ISSUE THREAD

**Issue by jol64** [cedrozor/myrtille#128]
In my testing I just tried ipv6, and I am unable to connect with either an ipv6 address (with or without[]) nor a hostname that resolves to ipv6 address only.

**Comment by jol64** [comment]
with wfreerdp I succeeded with [fe80::94b0:d277:5e17:9f2c] but not with an hostname (AAAA record).

**Comment by jol64** [comment]
https://github.com/FreeRDP/FreeRDP/issues/1949

**Comment by cedrozor** [comment]
Well, while reading this thread again, I just noticed something... you said your hostname resolves to ipv6 only; so, if there is an issue with ipv6, it's normal the connection doesn't work anyway.

But that doesn't explains why wfreerdp didn't worked either, so also check your DNS :p

**Comment by cedrozor** [comment]
I released the fix because, even if it doesn't address your issue, it fixes another. Please tell me if it's ok.

**Comment by jol64** [comment]
I now tried IP v6 with 2.1.2. I can now get it to run with [] notation, but not with a hostname that resolves to IPv6 only – as with wfreerdp. Any idea how to debug that? Is there a log or trace of freerdp communication?
Thanks, Joachim

**Comment by cedrozor** [comment]
Nice the ipv6 is working :)

Regarding the hostname, check your DNS configuration.  try running `nslookup `as explained in my previous post.

You can enable the myrtille logs into `<myrtille>\bin\Myrtille.Services.exe.config` (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#configuration--performance-tweaks--debug), **RemoteSessionLog** key; don't forget to restart the myrtille service.

Also look to the windows event logs (system and application), and search for anything related to DNS.

**Comment by jol64** [comment]
nslookup reports the expected ipv6 address.
I enabled logging, however the wfreerdp.*.log files are length 0 (except for the one where I tried [] notation). All other logs untouched. Nothing in the system and application event logs that I can attribute to that test.

**Comment by jol64** [comment]
myrtille server and hyper-v server are in the same domain, even the virtual machine is a clone of a domain member. (Btw, domain is not shown for VM Bus connections, nor security).

ping -6 with NetBIOS name does not work (not sure it should, https://msdn.microsoft.com/en-us/library/jj663161.aspx), neither does ping -6 with FQDN, whereas ping with the address returned by nslookup (which also succeeds) does. 

With Myrtille I am using the exact same URLs except exchanging server=xx, and it works for everything except a name that resolves to ipv6 only. Thus I don´t think it is about security options or authentication.

**Comment by cedrozor** [comment]
Ah sorry, I thought you were connecting a standard rdp server (not an Hyper-V VM).

Yes, the domain is not shown for a VM bus connection because it applies to the user whose authentication is delegated to the VM. The security protocol is not shown either because it applies to a standard rdp connection.

I have to recheck the VM bus connection using a hostname for the (Hyper-V) server address. For my previouses tests, I entered the server IP or just left the field empty (equivalent to "localhost"), because both Myrtille and Hyper-V servers are on the same machine. And I don't think "localhost" even goes through the DNS lookup; as a loopback address, it must be translated directly to 127.0.0.1 or [::1].

The wfreerdp code to resolve the hostname for a VM bus connection may differ from the one used for a standard rdp connection (even if I doubt it because it relies on tcp in both cases, just with a different port). 

Just for a try, could you enable remote desktop access on the VM then connect it with myrtille through a standard rdp connection with the VM hostname?

**Comment by cedrozor** [comment]
So I installed myrtille on another machine of the domain. The VM Bus connection, with the Hyper-V host as server, worked in all cases :
- NETBIOS
- NETBIOS.home
- FQDN

There must be something with your config :/ what is the error message (dialog box) into the browser after the connection fails?

**Comment by jol64** [comment]
*.home does not resolve in my network, and I think it shouldn´t.
The message is the following:
![image](https://user-images.githubusercontent.com/24666601/44875006-34c57980-ac9d-11e8-93a0-4bec90aeeeb9.png)
I only need to change the server= part of the URL to use an ipv4 alias and it succeeds.
I´d be happy to figure out what´s wrong or different...

**Comment by cedrozor** [comment]
You said the hyperv server address resolves to ipv6 only and you use an ipv4 for the server param into the url? and why does it resolves to ipv6 only? did you disabled ipv4?

On the myrtille machine, you said the nslookup of your hyperv machine works (fe80::94b0:d277:5e17:9f2c) and you can ping that ip. Is it still working?

If the connection with [fe80::94b0:d277:5e17:9f2c] works (&server=%5Bfe80%3A%3A94b0%3Ad277%3A5e17%3A9f2c%5D into the url), it must be an DNS issue...

Sorry, I'm running out of ideas :/

**Comment by jol64** [comment]
My network is mostly ipv4 and at present only exposes ivp4 to the outside. Internally I have some aliases in my DNS that resolve to ipv6 only in order to test software explicitly with ipv6. In other words, the hyper-v server hast multiple ipv4 aliases and one ipv6 alias resolving to the exact ipv6 address I used for testing..
I do understand you are running out of ideas. Actually I think it is either a local issue or a freerdp issue (as I can reproduce it with that as well). If only diagnostics would be better.. likely I have to go the hard way and debug wfreerdp.

**Comment by cedrozor** [comment]
About diagnostics, there is something you could do. Open a console window and go into the myrtille bin folder. There enter the following command lines (obviously replacing path and values by yours):
```
SET WLOG_APPENDER=FILE
SET WLOG_FILEAPPENDER_OUTPUT_FILE_NAME=wfreerdp.log
SET WLOG_FILEAPPENDER_OUTPUT_FILE_PATH=absolute\path\to\wfreerdp.log
SET WLOG_LEVEL=TRACE

wfreerdp /u:user /p:password/ /v:hostname /cert-ignore /vmconnect:vmguid /log-level:TRACE
```

This will not only bypass myrtille, but also set logs to a more precise level.

Then check wfreerdp.log.

**Comment by cedrozor** [comment]
If you want to check it, this should guarantee at least something in the logs (not 0 sized) and probably the root of the problem...

**Comment by jol64** [comment]
finally had time to dig deeper...
https://stackoverflow.com/questions/10767107/getaddrinfo-cannot-resolve-ipv6-google-com-but-nslookup-can provided the right solution of `Netsh interface teredo set state enterpriseclient`.

**Comment by cedrozor** [comment]
Congratulations, it was deep digging! did the log helped or did you had to debug wfreerdp?
