### ISSUE TITLE
Issue with a particular software

### ISSUE THREAD

**Issue by Manthan2611** [cedrozor/myrtille#133]
First of all thanks for this awesome project. 

I have installed Myrtille in my office it is working great but my major work is on a software know as Tally.ERP 9 ((http://tallysolutions.com/download/)). 
On the mentioned software i am unable to add space, while in notepad and other application i am able to add space using spacebar. 
In RDP Session it works fine. From Myrtille i've tried from on-screen keyboard and from it i can add space in the application.

So is there any way from which this space issue can be solved.?

**Comment by cedrozor** [comment]
I remember you asked that question, for this software, some months ago. I tried to fix it by changing the way wfreerdp send the keystroke to the rdp server, but it didn't worked.

By using myrtille, does adding space work in other applications? (i.e.: notepad)?

The application must do something low level that isn't handled by wfreerdp. Do you have any other key that is not working?

Did you tried to connect from another machine (not yours), with a different browser, possibly with another keyboard layout?

You can try to adjust the keyboard timings, server side:
https://www.dummies.com/computers/pcs/set-your-keyboards-repeat-delay-and-repeat-rate/
https://support.microsoft.com/en-us/help/894040/adjust-long-delay-in-keystrokes-appearing-due-to-windows-filterkeys

**Comment by Manthan2611** [comment]
yes yes i have asked you the same previously. 

yes i can add space in all other program like word, excel, notepad etc. 

Changing the keyboard setting did not work either and by enabling Filter Keys most of the key expect alphabet was not working. 

Tried with different browser / different machine / diff keyboard layer but still was not able to add space with it. 

The only way i could find was to use onscreen keyboard and other was by using alt combination (alt +255).

**Comment by cedrozor** [comment]
If it works in other applications, that's what I said, the application must do something low level that isn't supported by wfreerdp.

I will try to find some time to download and test this ERP application, but I have very few availability lately (I now provide freelance services).

What are your gateway (the machine on which myrtille is installed), remote server specs and language?

**Comment by Manthan2611** [comment]
Myrtille is installed in xeon x3430, 6GB RAM with windows 7 OS & Language is US Eng

**Comment by cedrozor** [comment]
Thanks.

What are the target (the machine on which Tally.ERP is installed) specs and language?

**Comment by Manthan2611** [comment]
Sorry didn't got you on this part, i have install tally on the same machine whose spec are mentioned above. 
Tally.ERP9 is a windows desktop based application its purpose it to maintain our accounts and inventory of any business segment.

**Comment by cedrozor** [comment]
Related to https://github.com/cedrozor/myrtille/issues/176; will probably be fixed with using IME keyboard support
