### ISSUE TITLE
SSH not proper CR/LF and no output - Fedora

### ISSUE THREAD

**Issue by diepeterpan** [cedrozor/myrtille#134]
Using myrtille 2.1.2.0 I SSH to my linux Fedora SRV and there appears to be a CR/LF issue and no output from commands.

![image](https://user-images.githubusercontent.com/15066052/47906436-eba6c700-de91-11e8-99d6-87a563740fb0.png)

**Comment by cedrozor** [comment]
From the screenshot, I see that the xterm console doesn't have the focus (empty square cursor). You just have to click (focus) it for it to work.

**Comment by diepeterpan** [comment]
Let me try and explain again; I type ls -l end the shell prompt appear on the same line without output; in the new screen capture you will see using Putty I get a directory listing but in myrtille not :-( 
![image](https://user-images.githubusercontent.com/15066052/47957279-6c151700-dfbb-11e8-8926-e3549bfd4619.png)

**Comment by MrZakos** [comment]
ls -l -a
will show all

**Comment by diepeterpan** [comment]
> ls -l -a
> will show all

R U Serious?  I am trying to explain a problem experienced with myrtille using ssh compared to Putty.  Putty works 100% but myrtille not.  Any command I give @ the ssh prompt in myrtille is not providing the output of the command issued; just another linux prompt.

**Comment by cedrozor** [comment]
Myrtille use `xterm.js` and `Renci.SshNet`, an ssh client which sets the terminal type to `xterm` when it connects the ssh server.

If the server isn't configured for an xterm output, the client won't be able to display it. What is surprising is you can see the commands you are typing ("ls -l") but not the result. Perhaps it's working because it's a simple output (one character at a time), not a formatted files list (for "ls -l", with colors, etc.).

Can you check the terminal type you are using? you can do it by using `echo $TERM`, and change it by using `setenv TERM` (https://unix.stackexchange.com/questions/23764/changing-terminal-emulators) or perhaps `export TERM=` for Fedora (https://unix.stackexchange.com/questions/108410/is-it-correct-to-set-the-term-variable-manually).

**Comment by diepeterpan** [comment]
> Myrtille use `xterm.js` and `Renci.SshNet`, an ssh client which sets the terminal type to `xterm` when it connects the ssh server.
> 
> If the server isn't configured for an xterm output, the client won't be able to display it. What is surprising is you can see the commands you are typing ("ls -l") but not the result. Perhaps it's working because it's a simple output (one character at a time), not a formatted files list (for "ls -l", with colors, etc.).
> 
> Can you check the terminal type you are using? you can do it by using `echo $TERM`, and change it by using `setenv TERM` (https://unix.stackexchange.com/questions/23764/changing-terminal-emulators) or perhaps `export TERM=` for Fedora (https://unix.stackexchange.com/questions/108410/is-it-correct-to-set-the-term-variable-manually).

Using Putty the echo says xterm
![image](https://user-images.githubusercontent.com/15066052/47978362-23965000-e0c6-11e8-8de6-d425a773353a.png)
 
And with Myrtille I can't see the echo :-(

![image](https://user-images.githubusercontent.com/15066052/47978433-812a9c80-e0c6-11e8-96d4-61c4e037973e.png)

**Comment by cedrozor** [comment]
I will install a Fedora VM to check that. Do you use the default ssh server (openssh)? no specific configuration (custom port, proxy ,etc.)? did you use putty from the machine where myrtille is installed?

**Comment by diepeterpan** [comment]
> I will install a Fedora VM to check that. Do you use the default ssh server (openssh)? no specific configuration (custom port, proxy ,etc.)? did you use putty from the machine where myrtille is installed?

Jip, standard openssh; default installation, no customization.  Linuz server is running headless (No GUI), just terminal/ssh access.  No proxy etc.

Output below when I checked my ssh deamon.

[root@srvfedora ~]# systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset>
   Active: active (running) since Fri 2018-10-26 15:24:03 SAST; 1 weeks 3 days >
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 777 (sshd)
    Tasks: 1 (limit: 1015)
   Memory: 6.8M
   CGroup: /system.slice/sshd.service
           └─777 /usr/sbin/sshd -D -oCiphers=aes256-gcm@openssh.com,chacha20-po>

**Comment by PraveenAnil** [comment]
I am also getting the same issue in an Ubuntu 16.04 VM. I checked the TERM value from a putty session and its already set to xterm
![image](https://user-images.githubusercontent.com/7903608/53479326-ce2fe580-3a9e-11e9-9e42-b0937405c693.png)

**Comment by cedrozor** [comment]
Thanks for your report, I will investigate

**Comment by cedrozor** [comment]
Fixed into 2.5.x

**Comment by diepeterpan** [comment]
Confirmed fixed; tested on Fedora :-)  Thank you.
