### ISSUE TITLE
V2.3.0 Swipe Emulation

### ISSUE THREAD

**Issue by j4kara** [cedrozor/myrtille#135]
Hi,

With the latest version I had a chance to test swipe emulation at an ipad(ios 12). It works very nice.
Only issue is after each swipe ends, the first next tap still clicks on the last point where swipe has finished. The second tap clicks on right point.
Just to be sure I tried with different apps, same result.
I also noticed it happens after tap&hold(long click) too.

Thanks in advance.

**Comment by cedrozor** [comment]
Hi,

Yes, it's an experimental feature and needs some tuning.  I'll need to find an ipad (don't have one :/) to check that (it's working fine on my Windows 10 laptop with touchscreen).

**Comment by j4kara** [comment]
My bad! I forgot to clear safari cache after update. JS messed up. 

What about using 2 fingers touch for scrolling and 1 finger touch for tapping?
300 ms delay in the new script, makes frequent touches impossible(as in calculator numpad or any fast response kiosk application). 

Best regards.

**Comment by j4kara** [comment]
For IOS safari webapp I changed some lines at touchscreen.js as

function Touchscreen(config, dialog, display, network, user)
{
    this.init = function()
    {
        try
        {
            user.addListener('touchmove', function(e) { touchMove(e); }, {passive: false});


and

    function touchMove(e)
    {
        try
        { e.preventDefault();

I have also disabled timeout(gesture=false), it helped a lot, I can now type fast and scroll smoothly by using just touchmove function. Issue is closed.

Myrtille is miracle :) Thanks a lot Cedrozor.

**Comment by cedrozor** [comment]
I improved the mechanism; this is still in test, I will include it into the next release.
