### ISSUE TITLE
Cannot install printer with error code 216

### ISSUE THREAD

**Issue by kisskumam** [cedrozor/myrtille#136]
Hi @cedrozor , thank you for your wonderful project.

I'm trying to install myrtille on my windows 7 - 32bits processor, but it always returns the win32 with error code 216. I'm not sure how it happen and how to fix this. Please take a look at the setup log.

> Installing Myrtille.Services
Installing service Myrtille.Services...
Service Myrtille.Services has been successfully installed.
Creating EventLog source Myrtille.Services in log Application...
Port monitor successfully installed.
Destination file C:\Windows\system32\spool\DRIVERS\W32X86\PSCRIPT5.DLL was not copied/created - it already exists.
Destination file C:\Windows\system32\spool\DRIVERS\W32X86\PS5UI.DLL was not copied/created - it already exists.
Destination file C:\Windows\system32\spool\DRIVERS\W32X86\PSCRIPT.HLP was not copied/created - it already exists.
Destination file C:\Windows\system32\spool\DRIVERS\W32X86\SCPDFPRN.PPD was not copied/created - it already exists.
Destination file C:\Windows\system32\spool\DRIVERS\W32X86\PSCRIPT.NTF was not copied/created - it already exists.
Printer drivers copied or already exist.
Redirection port added.
Could not add PDF Scribe printer driver. Win32 error code 216.
Printer driver installation failed.
Could not remove PDF Scribe printer driver. Win32 error code 1797.
Partial uninstallation failure. Function RemovePDFScribePrinterDriver returned false.
Partial uninstallation failure. Function RemovePdfScribePortMonitor returned false.
Installed Myrtille.Services
Running Commit phase of non-transacted install.
Committing assembly 'C:\Program Files\Myrtille\bin\Myrtille.Services.exe'.
Affected parameters are:
   oasisappid = 
   enterprisenetbiosdomain = 
   targetdir = C:\Program Files\Myrtille\\
   logtoconsole = true
   logfile = C:\Program Files\Myrtille\\log\Myrtille.Setup.log
   pdfprinter = 1
   enterpriseadmingroup = 
   oasisappkey = 
   installtype = notransaction
   servicesport = 8080
   oasisapikey = 
   assemblypath = C:\Program Files\Myrtille\bin\Myrtille.Services.exe
   action = commit
   enterprisedomain = 
Starting Myrtille.Services

**Comment by kisskumam** [comment]
Update - here is the definition of error 216 from win32:

> RROR_EXE_MACHINE_TYPE_MISMATCH

216 (0xD8)

This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by cedrozor** [comment]
Hi, sorry was quite busy this week.

Did you checked the windows application and system event log? you could also check the spooler event log https://answers.microsoft.com/en-us/windows/forum/windows_7-security/about-log-spooler-information/9bd4203c-9882-41b2-b1be-0af3f9b67222

**Comment by cedrozor** [comment]
Closed due to lack of feedback

**Comment by kisskumam** [comment]
hi, I found the problem is the PSCRIPT5.DLL and PS5UI.DLL dont match the platform version. I dont know why! But I resolved it by downloaded the correct file from internet, then replacing them on:
C:\Windows\System32\spool\drivers\W32X86
C:\Windows\System32\spool\drivers\W32X86\3 (if this folder is existed)

Then reinstall the printer!

**Comment by cedrozor** [comment]
Hi, this is great! where did you downloaded these 2 files?

**Comment by kisskumam** [comment]
Use this link:
[https://drive.google.com/open?id=1fvKuW64kZ1NcY8Aq-3yyxxDCYwH33-gu](url)
