### ISSUE TITLE
myrtille initDisplay error: Display is not defined

### ISSUE THREAD

**Issue by augster** [cedrozor/myrtille#138]
I have Myrtille installed and running on a Windows 10 PC. When I navigate to https://myserver/myrtille I get a browsere popup message that reads "myrtille initDisplay error: Display is not defined". I can click past this and enter the info to connect to an RDP server. But when I click "Connect!" I get the same popup message and Myrtille doesn't connect to the RDP. I'm using Chrome Version 71.0.3578.98 (Official Build) (64-bit). I also tried with the latest version of IE and same thing happened.

I looked at the DevTools on Chrome and the error is coming from "index.js" line 50: "Uncaught ReferenceError: startMyrtille is not defined"

**Comment by cedrozor** [comment]
You probably have something (an extension or configuration ?) that prevent the javascript files to be loaded correctly. "startMyrtille," for exemple, is defined into js/myrtille.js. But, as you checked with another browser, I think more of a server side issue.

Using the devtools, could you check the http result code for the .js files ? should be HTTP 200 (ok). If not, please tell me which code it is. It may be a MIME type issue with IIS (with the .js extension) or an access right issue with the js folder.

**Comment by cedrozor** [comment]
Did you checked the myrtille.js (where the function `startMyrtille` is located) result code?

**Comment by cedrozor** [comment]
any news?

**Comment by pietro2005** [comment]
Good morning! I have the same problem and I would like to fix it. 

![image](https://user-images.githubusercontent.com/48014399/53406356-132e1c00-39ba-11e9-9a30-fa1c64b0d732.png)

How can I check if myrtille.js relusts code? Thank you!

**Comment by pietro2005** [comment]
![image](https://user-images.githubusercontent.com/48014399/53418286-be010300-39d7-11e9-9fe8-20b17ee45984.png)

![image](https://user-images.githubusercontent.com/48014399/53418317-d07b3c80-39d7-11e9-9649-54ef4e8913c0.png)

**Comment by augster** [comment]
Sorry for the delayed response. The problem ended up being in my IIS installation. I didn't have "Static Content" installed. Once installed, it loaded up just fine. See below...

Install the feature in **control panel->programs->turn windows features on and off->Internet Information Services/World Wide Web Services/Common HTTP Features/Static Content**.

**Comment by pietro2005** [comment]
![image](https://user-images.githubusercontent.com/48014399/53484488-3fae6a80-3a84-11e9-86cd-da76cb3e7682.png)

Wow! Thank you a lot! it works

**Comment by cedrozor** [comment]
Glad you found it! :) indeed, .css, .js files, etc. are static content
