### ISSUE TITLE
Myrtille unable to connect

### ISSUE THREAD

**Issue by songlim327** [cedrozor/myrtille#139]
Hi,

Thanks for your awesome work in creating myrtille. The app is definitely awesome. I had recently pull myrtille from github and planning to build it myself. I had followed every steps in the documentation (build freeRDP, set multiple startup project, ... ). The website seems to be fine after start debugging(F5). However, when i press the button to connect to a remote desktop, the connection was closed down immediately with the following error(s):

- The remote connection was disconnected after the host client process was killed (exit code 131078)
- The remote connection failed or was closed unexpectedly (exit code 1)

One of the error stated above will be shown in the dialog. Can't really figure out what had happened. I had also ensured that with the same server(IP),username and password, i was able to access to the remote desktop by using remote desktop connection provided by Windows. Can anyone guide me on this one? Much help appreciated. 
Edited:
It did works fine with release. However i would like to make some modification on it.

**Comment by cedrozor** [comment]
There may be an issue with wfreerdp (mising dll for example). Did you tried to run wfreerdp.exe (into the `Myrtille.RDP\FreeRDP\Debug` folder) from a console command?

`wfreerdp.exe /v:server /d:domain /u:user /p:password `

**Comment by songlim327** [comment]
Had run the wfreedp.exe(`FreeRDP\Debug`) from a console. It works fine though.

**Comment by cedrozor** [comment]
As you are under Visual Studio, you can put a breakpoint here: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L258 and check for any exception. There may be an access right issue when running wfreerdp (do you run Visual Studio as Administrator ?).

You should also check the `Myrtille.Web` and `Myrtille.Services` logs (into their respective locations, log folder), and enable the wfreerdp logs: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L190 (wfreerdp logs will be located at `Myrtille.RDP\FreeRDP\Log`)

**Comment by cedrozor** [comment]
Well, I checked and it turns out that I forgot to commit something on the freerdp fork (!)

For my defense, TortoiseGit (the GIT client I use on my dev machine) does not mark files as modified (with the red sign "!") for some time (?), although this is a recent version. I should perhaps go back to SourceTree (Atlassian).

Anyway, it's fixed (commited). You will have to rebuild wfreerdp after pulling the changes. Sorry for that.

The release (installer) is working because it includes the changes on my build environment.

**Comment by songlim327** [comment]
Hi, i had tried to build it and it works successfully. However, after i connect to a remote desktop, it shows a session in browser and another in `FreeRDP.exe`, is it normal?

![myrtille](https://user-images.githubusercontent.com/36408539/50553068-6c3f4380-0cda-11e9-9ed8-644caa20874a.PNG)

**Comment by cedrozor** [comment]
Yes, under Visual Studio you have the wfreerdp window and console to help for debug. When Myrtille.Services runs as a Windows service, you don't have them (because a service can't have an UI).

**Comment by songlim327** [comment]
ok understood. Thanks for all your help. Appreciate a lot.

**Comment by cedrozor** [comment]
You are welcome. Issue closed.
