### ISSUE TITLE
Unable to run APP on a WS2012R2 server

### ISSUE THREAD

**Issue by laurentg78** [cedrozor/myrtille#144]
Hi,
My setup is as follow:
Client IE11 on a WS2008R2 Server
Myrtille on a WS2012R2 Server
Host on a WS2012R2 Server
I want to launch an app on the host but the connection window closes and I fall back on the Myrtille connection page.
I can't also run an APP from an MSTSC connexion launched from the client, and also from the myrtille gateway.
I ran the rdpsetup.reg on the myrtille gateway with no result.
I have the feeling that WS2012R2 doesn't allow this feature?
Do you have any clue?
My link is :http://MyrtilleGateway.domain/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=REAXAS01T&domain=domain&user=user&password=Password&program=notepad.exe&connect=Connect%21

**Comment by cedrozor** [comment]
Hi,

Did you installed the RDS role on the server?

If you did (needed), there are several locations where you can configure it and, most importantly, allow a program to start on connection:

GPO (local or group, if you are using a domain):
- Computer Configuration\Policies\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Remote Session Environment
- User Configuration\Policies\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Remote Session Environment

Registry: HKCU\Software\Microsoft\Windows\CurrentVersion\Run

RemoteApp: even if myrtille doesn't use it, you may have to allow the program you want to start into the RemoteApp feature (https://www.concurrency.com/blog/w/rds8-quick-and-easy,-remoteapp-on-windows-server-2)

**Comment by cedrozor** [comment]
Did you tried my suggestion?

**Comment by laurentg78** [comment]
Hi,
Sorry for the delay. Unfortunately I had to change my environment and I am now in non-domain environment. So only the registry method works but it launches the desktop and the application afterwards.
I realize my question was not clear. I want to launch only an app via Myrtille. Is it possible without using RDS?

**Comment by cedrozor** [comment]
Remoteapp is doing that but, unfortunately, it's not well supported by wfreerdp and thus by Myrtille. This is something I want to implement for a long time... as soon as it's working fine with wfreerdp, I'll use it with Myrtille.
