### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by yotoprules** [cedrozor/myrtille#146]
Hi, I am unable to install Myrtille. it gives me error 1001 saying the class is not registered. Is there a way to fix this?

**Comment by cedrozor** [comment]
Did you installed IIS and .NET 4.5 (requirements) before installing Myrtille?

**Comment by cedrozor** [comment]
any news?

**Comment by cedrozor** [comment]
please check https://github.com/cedrozor/myrtille/issues/165, it should work by reinstalling IIS and .NET 4.6
