### ISSUE TITLE
compiling your FreeRDP and openSSL

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#15]
Hi Cedric, Any idea why I cannot get cmake working? It chokes when looking for OpenSSL even though I have c:\OpenSSL-Win32 and c:\OpenSSL-Win64

both 32 and 64 bit folder are the full version 1.1.0

Here is a dump of my cmake attempt:

The C compiler identification is MSVC 19.0.24213.1
The CXX compiler identification is MSVC 19.0.24213.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
FreeRDP GIT
Git Revision 5829680
MSVC: using dynamically-linked runtime (/MD and /MDd).
Looking for include file fcntl.h
Looking for include file fcntl.h - found
Looking for include file unistd.h
Looking for include file unistd.h - not found
Looking for include file execinfo.h
Looking for include file execinfo.h - not found
Looking for include file inttypes.h
Looking for include file inttypes.h - found
Looking for include file sys/modem.h
Looking for include file sys/modem.h - not found
Looking for include file sys/filio.h
Looking for include file sys/filio.h - not found
Looking for include file sys/sockio.h
Looking for include file sys/sockio.h - not found
Looking for include file sys/strtio.h
Looking for include file sys/strtio.h - not found
Looking for include file sys/select.h
Looking for include file sys/select.h - not found
Looking for include file syslog.h
Looking for include file syslog.h - not found
Performing Test HAVE_TM_GMTOFF
Performing Test HAVE_TM_GMTOFF - Failed
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Skipping disabled feature X11 for X11 (X11 client and server)
Skipping disabled feature Wayland for Wayland (Wayland client)
Skipping disabled feature DirectFB for DirectFB (DirectFB client)
Skipping disabled feature ZLIB for compression (data compression)
Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
  version "1.1.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:307 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:713 (find_feature)

Configuring incomplete, errors occurred!
See also "C:/repos/Other/cedrozor/FreeRDP/build/CMakeFiles/CMakeOutput.log".
See also "C:/repos/Other/cedrozor/FreeRDP/build/CMakeFiles/CMakeError.log".

**Comment by tmakaro** [comment]
fixed. I installed openssl 1.0.2h instead and now cmake completes.

**Comment by tmakaro** [comment]
26 compilation errors :(

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		class "rdp_settings" has no member "MyrtilleDebugLog"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	159	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	147	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	223	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	232	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	241	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	245	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	267	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	342	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	451	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	462	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	619	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	635	
Error (active)		class "rdp_settings" has no member "MyrtilleSessionId"	wfreerdp-client	c:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	884	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	147	
Error	C2039	'MyrtilleDebugLog': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	159	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	223	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	232	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	241	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	245	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	267	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	342	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	451	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	462	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	619	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	635	
Error	C2039	'MyrtilleSessionId': is not a member of 'rdp_settings'	wfreerdp-client	C:\repos\Other\cedrozor\FreeRDP\client\Windows\wf_myrtille.cpp	884

**Comment by cedrozor** [comment]
Oups, it seems I forgot to commit [https://github.com/cedrozor/FreeRDP/blob/master/include/freerdp/settings.h](https://github.com/cedrozor/FreeRDP/blob/master/include/freerdp/settings.h). I go home for lunch, I will do it ;)

**Comment by cedrozor** [comment]
done.
