### ISSUE TITLE
remote access terribly slow

### ISSUE THREAD

**Issue by percoclap** [cedrozor/myrtille#150]
hi all, first thanks for this free tool, really goot soft. however, dont know why, but my remote access is randomly slow, to connect on an Azure VM (, no firewall, 8CPU / 16GB RAM...), using internet fiber connection. and for unknown reasons sometimes the connection is sooo slow it makes impossible to use remote desktop.

Could you please tell me what kind of optmizations / settings I could change to check if it would be better ? I heard about websocket improves the connection... what does it means exactly ? anyway if you could give me some advices... thanks a lot

**Comment by cedrozor** [comment]
Did you enabled the websocket protocol on IIS? (https://www.iis.net/configreference/system.webserver/websocket)

**Comment by percoclap** [comment]
lool omg yes it definitely better, ^^ perfect thanks
