### ISSUE TITLE
Slow refresh of desktop over vmconnect

### ISSUE THREAD

**Issue by joburg** [cedrozor/myrtille#154]
Hi, are there recommended settings that can be used to improve repaint/refresh of desktop when using the vmconnect option to connect to Hyper-V VM?  unfornately, hyper-v host doesn't support vmenhanced connection. lag time between screen repaints makes it look like you're watching a film in slow-motion.

**Comment by cedrozor** [comment]
Did you enabled the websocket protocol on IIS? (https://www.iis.net/configreference/system.webserver/websocket). If not, myrtille falls back to HTML4 (long-polling) and that adds up to a slow rendering.

**Comment by joburg** [comment]
Yes, websocket protocol's enabled. And looking at my javascript trace and debugging code I added, it is using a websocket connection. Straight RDP has no lag time, VmEnhanced connection is also ok but when I uncheck VmEnhanced (since Vm's running on a 2012 host doesn't support it and just never connects), I start seeing the lag time even at the login screen. I'll disable wallpaper and all graphics-heavy items on the desktop and see if it helps.  

Would this also cause the cursor to have a lag, i.e. you move the mouse around and sometimes it stays stuck in an hour glass cursor even if it should be an hour glass... I can only break it out of that loop by moving the mouse over something that makes it switch again.

**Comment by cedrozor** [comment]
Normally, you should be able to enable the VM enhanced mode with a 2012 server (http://www.askme4tech.com/how-enable-hyper-v-enhanced-session-mode)

**Comment by cedrozor** [comment]
Were you able to check the Hyper-V settings?

**Comment by joburg** [comment]
Yes. VmEnhanced is available only on Server 2012 R2 and up. Removed wallpaper and all background images and I think performance is acceptable.

**Comment by cedrozor** [comment]
It's a Server 2012 not R2? if possible, did you considered upgrading it?

**Comment by joburg** [comment]
Unfortunately, it's not an option to upgrade.

**Comment by cedrozor** [comment]
In order to improve performance, if you can't have the enhanced mode, you can lower the rendering quality (https://github.com/cedrozor/myrtille/issues/162)
