### ISSUE TITLE
Just can't make Myrtille work with all the prerequisites

### ISSUE THREAD

**Issue by romanad** [cedrozor/myrtille#157]
Hello dear support team

If it's possible please help me to launch the Myrtille.
Unfortunately I wasn't able to sole the problem with DOCUMENTATION.md
My prerequisites are:
1) Win 10 x64, 
2) IIS 10 itegrated to Win 10
3) ASP.NET 4.5
4) ISAPI extensions 
5) ISAPI filters
6) web sockets
7) Static Content

and after all thee prerequisites I've installed the Myrtille and when I go to http://localhost/Myrtille/ I'm getting these:

1) HTTP ERROR 500 in browser
2) "A process serving application pool 'MyrtilleAppPool' terminated unexpectedly. The process id was '12240'. The process exit code was '0xfffffffe'." - in event viewer
3) And this in service log:
 "2019-05-29 17:31:30,300 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IMFAAuthentication
2019-05-29 17:31:30,301 [4] INFO  System.Diagnostics redirection [(null)] - 
2019-05-29 17:31:30,310 [4] INFO  System.Diagnostics redirection [(null)] - Service: Myrtille.Services.EnterpriseService
2019-05-29 17:31:30,311 [4] INFO  System.Diagnostics redirection [(null)] - Endpoint: BasicHttpBinding_IEnterpriseService
2019-05-29 17:31:30,311 [4] INFO  System.Diagnostics redirection [(null)] - Address: http://localhost:8080/Myrtille/EnterpriseService
2019-05-29 17:31:30,311 [4] INFO  System.Diagnostics redirection [(null)] - Binding: BasicHttpBinding
2019-05-29 17:31:30,311 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IEnterpriseService
2019-05-29 17:31:30,311 [4] INFO  System.Diagnostics redirection [(null)] - "

**Comment by cedrozor** [comment]
Hi, can you enable the detailed error message into the browser, by following the steps explained here: https://stackoverflow.com/questions/2640526/detailed-500-error-message-asp-iis-7-5/4714919#4714919

**Comment by romanad** [comment]
I tried but with no luck, can you guide me please in right directions.
What I have done:
1) inserted those parameters into Web.config file located in C:\Program Files (x86)\Myrtille
2) saved the file
3) restarted Myrtille.Services
4) opened IE and chrome to http://localhost/Myrtille/ and the error is the same - 500, no additional info.
What I'm doing wrong?
Please see screenshots
![system webServer](https://user-images.githubusercontent.com/26842711/58637328-f4ae2880-82fa-11e9-9e28-3264eae026ac.jpg)
![system webServer_edited](https://user-images.githubusercontent.com/26842711/58637335-faa40980-82fa-11e9-8b88-61dbeff9cf8d.jpg)
![IE_error](https://user-images.githubusercontent.com/26842711/58637358-02fc4480-82fb-11e9-8cd7-19d77aa5cc70.jpg)
![chrome error](https://user-images.githubusercontent.com/26842711/58637365-05f73500-82fb-11e9-8842-c089ff4af481.jpg)

**Comment by romanad** [comment]
I even performed a command listed bellow:
 appcmd.exe set config -section:system.webServer/httpErrors -allowAbsolutePathsWhenDelegated:true

still doesn't work
![command_bellow](https://user-images.githubusercontent.com/26842711/58637829-0e03a480-82fc-11e9-9d68-bb533f79d189.jpg)

**Comment by romanad** [comment]
I also restarted IIS - no changes
![IIS_restart](https://user-images.githubusercontent.com/26842711/58638031-879b9280-82fc-11e9-8e1d-0ac6d52bc10d.jpg)

**Comment by cedrozor** [comment]
Hi, IIS config can be annoying sometimes. Did you tried what is also suggested here: https://stackoverflow.com/questions/2640526/detailed-500-error-message-asp-iis-7-5/2765795#2765795

![image](https://user-images.githubusercontent.com/17749498/58638482-389e2f00-82f5-11e9-85b2-6439e0e7e9cd.png)

Can you check if you have something useful into the Windows event logs (System and application)? HTTP 500 errors usually come with a suffix (i.e.: HTTP 500.24, https://github.com/cedrozor/myrtille/issues/30)

**Comment by romanad** [comment]
OK, finally I found where the option was placed, I just needed to install it via "Turn windows features on or off".
And now I got full error.
![ERROR](https://user-images.githubusercontent.com/26842711/58641404-cd0f8e00-8303-11e9-96b7-2f015d6e7a40.jpg)

**Comment by romanad** [comment]
Finally I've figured it out, the problem was easily solved with that post -->
