### ISSUE TITLE
Clipboard buggy symbols from remote to local (English encoding)

### ISSUE THREAD

**Issue by romanad** [cedrozor/myrtille#160]
And one more issue with clipboard ...
When I'm trying to copy remote clipboard in English encoding there are problems with symbols like " and '. 
I'm using HTML 5 with websocket on latest 2.5.5.0 version.
Please see screenshot.
![buggy_symbols](https://user-images.githubusercontent.com/26842711/58790170-79998a80-85f8-11e9-96ee-b06d33c222cc.jpg)

**Comment by cedrozor** [comment]
These characters are normally escaped by Myrtille but, then again, I must have missed some use cases. I think that I will definitely use a base64 encoding for clipboard into the next release, as I mentionned into https://github.com/cedrozor/myrtille/issues/159

These issues were not introduced by the version 2.5.5, they are here for some time I would say.

**Comment by cedrozor** [comment]
#158 and #159 related
