### ISSUE TITLE
How to change encoding and quality

### ISSUE THREAD

**Issue by didimomonteiro** [cedrozor/myrtille#162]
I'm trying to change the image quality through the config.js file

But we can not make a connection. continuous quality 100% and encodig PNG.

I opened the config.js file by notepad, changed the following lines, restarted IIS and later the machine, but even then there was no change in quality or encoding

![image](https://user-images.githubusercontent.com/51522576/59155236-48d3ae00-8a5b-11e9-8e3d-0c2631d275e0.png)
![image](https://user-images.githubusercontent.com/51522576/59155238-4d986200-8a5b-11e9-8446-927ca5f79540.png)

**Comment by cedrozor** [comment]
Can you try to clear your browser cache and then reload the page?

**Comment by didimomonteiro** [comment]
oh man...

The problem was exactly this, logging in with an anonymous av worked perfectly.

I apologize for not having thought of that.

Thank you very much
