### ISSUE TITLE
er 1001

### ISSUE THREAD

**Issue by d7eeem** [cedrozor/myrtille#164]
error 1001 : some or all identity references  could not be translated 
Then 
error 1001 cloud not find Files (x86)\Mytille\bin\Mytille.services.InstallStat

**Comment by cedrozor** [comment]
Did you installed IIS and .NET 4.5 (or newer)? you can find troubleshooting info here: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot

**Comment by datgb** [comment]
I actually have both installed on mine. Ill try to do a reinstall of them. net 4.6 is on.

**Comment by cedrozor** [comment]
duplicate of https://github.com/cedrozor/myrtille/issues/165 (fixed)
