### ISSUE TITLE
Autoinstaller issues

### ISSUE THREAD

**Issue by datgb** [cedrozor/myrtille#165]
Hey guys, new to checking this out. i downloaded the latest exe release (Myrtille_2.5.5_x86_x64_Setup) and get these errors on install.

Windows 10 Pro. 64bit  Build 10586.1176

Error 1001: Some or all identity resources could not be translated.

Error 1001: Could not find file 'C:\Program files (x86)\Mytrille\bin\Mytrille.Services.InstallState'.

Error 1001: Could not find file 'C:\Program files (x86)\Mytrille\bin\Mytrille.Admin.Services.InstallState'.

**Comment by cedrozor** [comment]
probable duplicate https://github.com/cedrozor/myrtille/issues/164

**Comment by datgb** [comment]
Sorry. Reinstall of IIS and net 4,6 worked.
