### ISSUE TITLE
Pages cannot listen for input methods

### ISSUE THREAD

**Issue by osswiseyelin** [cedrozor/myrtille#170]
Pages can not listen to input methods, and can not directly enter text in other languages such as Chinese.

**Comment by cedrozor** [comment]
Myrtille captures unicode characters from javascript to be language independent (Chinese/Hebrew/etc. users have used myrtille successfully in the past).

The problem may be something else (not language related); did you tried with an english keyboard/language successfully?

Can you type/send some Chinese text with the "keyboard" button (into the toolbar)?

**Comment by osswiseyelin** [comment]
I think it's a pity that the experience is too bad to use the local keyboard directly compared with the direct connection of the freerdp client. On Mytille's ssh-webClient, you can use the local keyboard to input directly. Why can't RDP be implemented?

**Comment by cedrozor** [comment]
It is treated differently from ssh, but it is implemented. Have you tried what I suggest?

**Comment by Halajohn** [comment]
I have the same issue.

My local environment is:
- Chrome 76
- MacOS Mojave
and my remote environment is:
- Windows 10 pro RDP server
- Myrtille 2.5.5.0

The testing result is:
- Using the "keyboard" button, and enable the Chinese input method locally (i.e, on Mac) to enter Chinese characters into the "keyboard" dialog to send them to the remote Windows machine : OK.
- Open "notepad" (or some other applications which can accept Chinese characters) directly in the remote Windows machine, and enabling the Chinese input method locally (i.e, on Mac) to enter Chinese characters into that "notepad" : Failed.

The testing results of different combinations of enabling/disabling of the local/remote Chinese input methods are:
- local (EN), remote (EN) : notepad receives correct English characters I clicked.
- local (EN), remote (Chinese input method enabled) : notepad receives English characters I clicked
- local (Chinese input method enabled), remote (EN) : notepad can NOT receives any Chinese characters nor English characters
- local (Chinese input method enabled), remote (Chinese input method enabled) : notepad can NOT receives any Chinese characters nor English characters

It seems that the Myrtille client webpage prevents the Chinese input method on Mac from generating the final Chinese characters, so there is no correct Chinese characters to sent to the remote machine.

**Comment by cedrozor** [comment]
Hi, Thanks for the detailed report.

I confess I tested with Chinese language on Windows and not on Mac. I will try with a Mac.

The SSH implementation (using xterm.js) handles the unicode inputs a bit differently than Myrtille; it translates them from javascript keycodes to U+XXXX (C# \uXXXX) before sending them to myrtille.

I will see if I can use a similar technique.

Do other Chinese people there have this problem?

**Comment by cedrozor** [comment]
related to #158 #159 and #171

**Comment by cedrozor** [comment]
I checked on Windows (remains to test on Mac) and found the reason behind the problem. The "Pinyin" keyboard, if that is what you use, displays the Chinese characters into an horizontal bar, under the keyboard cursor, when a keystroke is entered. More details: https://chinese.yabla.com/type-chinese-characters.php?platform=win7

Problem is, the page javascript code (used by myrtille) does capture the keystroke (unicode value) but the browser itself doesn't display that horizontal bar; so it isn't possible to select a Chinese character.

A workaround is to enable the Chinese Pinyin keyboard server side and use the Windows On-Screen-Keyboard (osk.exe); it will display the horizontal bar with Chinese characters. It's possible to have osk.exe run automatically on session start (https://www.cybernetman.com/kb/index.cfm/fuseaction/home.viewArticles/articleId/197).

I know it's not ideal; if someone have a better idea, please tell me.

**Comment by Halajohn** [comment]
I use Zhuyin input method of Traditional Chinese. And I tried your osk.exe method and found that when I click the Myrtille browser window, the IME is disabled, however, it seems you are using Windows 7, but I am using Windows 10. Don't know if this caused the differences.

**Comment by cedrozor** [comment]
Thanks for your feedback.

I just checked on Windows 10. Unfortunately, I don't have a physical Chinese keyboard and I also don't have the option to choose Zhuyin (only Pinyin) into Windows 10; so I can't test it :/

Did you ran osk.exe server side? because I found that even if IME is enabled client side with Pinyin, the javascript code doesn't care and capture the keystroke of my physical (Western Europe, Azerty) keyboard.

**Comment by Halajohn** [comment]
I miss the "server side", and yes, what you have seen is the same with mine. osk.exe of client side can only capture the keystroke of the physical keyboard, and I tested the osk.exe of "server side", it can type Chinese characters correctly. I believe not only Zhuyin, but Pinyin is also in the same situation.

**Comment by cedrozor** [comment]
After some additional researches, IME keyboards need "composition" events with javascript, as explained here: https://www.w3.org/TR/ime-api/.
#176 duplicate
