### ISSUE TITLE
Unparsed external symbol

### ISSUE THREAD

**Issue by osswiseyelin** [cedrozor/myrtille#172]
When compiling, we encountered an external symbol "WebPConfigInitial" that could not be resolved. This symbol is referenced in the function "wf_myrtille_start"

**Comment by osswiseyelin** [comment]
My compilation environment is visualstudio 2019,openssl-x64

**Comment by cedrozor** [comment]
If I remember well, the webp lib is 32 bits only, so wfreerdp have to be compiled in x86 (32 bits). While you are here, you could update it (https://developers.google.com/speed/webp/download).

Regarding webp, I found it interesting to lower the images size (thus the bandwidth), but at the expense of speed. Myrtille use png by default but it can be tweaked here: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L123 (see comments into display.js) 

I used the nuget package openssl-vc141-static-x86_64 for openssl (1.1.0) (https://github.com/cedrozor/FreeRDP/blob/master/libfreerdp/packages.config)

**Comment by osswiseyelin** [comment]
In fact, I would like to know what your compilation environment is like, for example, openssl is x64 or win32,visual studio version is 2019 or 2017, or even 2015, I feel that the reason why I can't compile is more of this aspect

**Comment by osswiseyelin** [comment]
hi：
            I've configured in visual2019 for all except wfreerdp - client for win - x64, only wfreerdp - client configuration is a win32, compiled, compiled by 28 in front of the product that only appeared in the wfreerdp - client here c3861 __readfsdword couldn't find the identifier of the error, I don't know what place is I didn't notice that, unfortunately, for compiling wfreerdp I always failed.The error is shown below:






此致  
          敬礼！
======================
姓名：叶林
公司：北京欧智科技有限公司
手机：18610944486
邮箱：yelin@osswise.cn
 
From: cedrozor
Date: 2019-08-23 22:06
To: cedrozor/myrtille
CC: osswiseyelin; Author
Subject: Re: [cedrozor/myrtille] Unparsed external symbol (#172)
If I remember well, the webp lib is 32 bits only, so wfreerdp have to be compiled in x86 (32 bits). While you are here, you could update it (https://developers.google.com/speed/webp/download).
Regarding webp, I found it interesting to lower the images size (thus the bandwidth), but at the expense of speed. Myrtille use png by default but it can be tweaked here: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L123 (see comments into display.js)
I used the nuget package openssl-vc141-static-x86_64 for openssl (1.1.0) (https://github.com/cedrozor/FreeRDP/blob/master/libfreerdp/packages.config)

**Comment by cedrozor** [comment]
I'm using VS2017 and cmake 3.10; config for wfreerdp is win32 (x86) and config for myrtille is Any CPU.

What is the error message (can't see any in your post)?

**Comment by osswiseyelin** [comment]
I can see my post, but I can reply directly after the email reminder, which is more convenient. As for the compilation problem, I have solved it. The compilation environment compiled successfully in Windows 7-64 as you said. Thank you very much for your support.

**Comment by osswiseyelin** [comment]
hi:The following picture is the file compiled by me with debug, but it can only be used for CMD, and cannot be put in myrtille's rdptool for web page interaction. I want to know, what else do I need to do after compilation?



此致  
          敬礼！
======================
姓名：叶林
公司：北京欧智科技有限公司
手机：18610944486
邮箱：yelin@osswise.cn
 
From: cedrozor
Date: 2019-08-26 18:52
To: cedrozor/myrtille
CC: osswiseyelin; Author
Subject: Re: [cedrozor/myrtille] Unparsed external symbol (#172)
I'm using VS2017 and cmake 3.10; config for wfreerdp is win32 (x86) and config for myrtille is Any CPU.
What is the error message (can't see any in your post)?

**Comment by cedrozor** [comment]
To my knowledge, building wfreerdp in win64 have no real benefits besides going upper 4GB of RAM (which should never happen with a wfreerd process!). I didn't noticed any performance improvement; that's why I remained with a win32 build for myrtille (in addition to linking the Google's webp lib, which is x86), I don't have to package 2 executables and it works on both 32 and 64 bits OSes.

Did you built https://github.com/cedrozor/FreeRDP ? (not the main project, https://github.com/FreeRDP/FreeRDP)

**Comment by osswiseyelin** [comment]
Yes, I build is https://github.com/cedrozor/FreeRDP/releases (Myrtille 2.1.1), after I am trying to find, only under the compilation of the device can be used any wfreerdp, but packaged debug packet to another environment, seems to be missing some dependent, unable to run normally, can only be connected, the connection on screen will be stuck in the first frame, then this should be a gdi rely on such errors, then wfreerdp quit, How do you put all the dependencies into debug and still work on other devices without additional dependencies

**Comment by osswiseyelin** [comment]
hi:The debug package below is the directory I compiled, and you can probably see which dependencies I missed
        



此致  
          敬礼！
======================
姓名：叶林
公司：北京欧智科技有限公司
手机：18610944486
邮箱：yelin@osswise.cn
 
From: cedrozor
Date: 2019-08-27 22:51
To: cedrozor/myrtille
CC: osswiseyelin; State change
Subject: Re: [cedrozor/myrtille] Unparsed external symbol (#172)
To my knowledge, building wfreerdp in win64 have no real benefits besides going upper 4GB of RAM (which should never happen with a wfreerd process!). I didn't noticed any performance improvement; that's why I remained with a win32 build for myrtille (in addition to linking the Google's webp lib, which is x86), I don't have to package 2 executables and it works on both 32 and 64 bits OSes.
Did you built https://github.com/cedrozor/FreeRDP ? (not the main project, https://github.com/FreeRDP/FreeRDP)

**Comment by osswiseyelin** [comment]
Can you receive my Debug package?

**Comment by cedrozor** [comment]
Hi, you need to build the master branch from https://github.com/cedrozor/FreeRDP. The 2.1.1 release tag is related to myrtille 2.1.1. Sorry about that, I forgot/was a bit lazy to create tags after that. I will do for sure with the next releases!

**Comment by osswiseyelin** [comment]
Hello, yes, according to what you said, I compile successfully and combined with certain dependence can perfect run anywhere, however, after I put him in a myrtille replace original wfreerdp, found myrtille cannot use normally, it should be and I don't know the steps, make wfreerdp in command line mode and use the program call is different, is that so?

**Comment by cedrozor** [comment]
Did you tried to run wfreerdp.exe in command line from the myrtille bin folder? you may forgot to copy some dlls

**Comment by osswiseyelin** [comment]
Yes, I can run successfully. Thank you very much for your support during this period of time. I have successfully solved all the problems.
