### ISSUE TITLE
Enterprise Mode loads blank

### ISSUE THREAD

**Issue by mattdoble89** [cedrozor/myrtille#173]
I have installed Myrtille and enabled enterprise mode. I am able to login, it picks up incorrect credentials, but logs me into a blank screen, blue background with username in the top right. The user is in the admin group specified.

**Comment by cedrozor** [comment]
I'm not sure to understand exactly the issue. How are you able to login with incorrect credentials? do you mean the myrtille login or a remote server login?

**Comment by mattdoble89** [comment]
Sorry. So I get the Myrtille login page, which correctly picks up correct/incorrect credentials for the remote server. However, when I enter correct details, I am taken to a blank, blue page. Nothing else present.

All works fine in normal more, this just happens with enterprise.

**Comment by cedrozor** [comment]
Is there something different with the connection params in enterprise mode (domain, security protocol)?
the blue page may be the windows logon sequence which remains stuck for any reason.

**Comment by mattdoble89** [comment]
I am wondering if I have missed something in the setup. While I have set the enterprise settings, link to AD etc, where do I then enter the actual RDP connection settings?

**Comment by cedrozor** [comment]
You can check the config files, located into your install and bin folders; if you forgot something during the setup or if there are changes afterward (read the documentation, you may need to restart the myrtille services).

You can change the connection settings by enabling the "Prompt for credentials" checkbox into the RDP or SSH hosts settings.

**Comment by mattdoble89** [comment]
I am struggling with finding any documentation on setting up the enterprise mode, past the basic guidance in the read me file?

**Comment by cedrozor** [comment]
Did you read that? https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#enterprise-mode

**Comment by cedrozor** [comment]
Any success?
