### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by FelR** [cedrozor/myrtille#174]
Hi,

I'm trying to integrate Myrtille into a PHP website to connect to virtual machines in Hyper-V. Therefore I'd like to ask you to provide me with information on how to call the http://*:8008/Myrtille connection api to generate a cid, that can be passed to the frontend.

Thank you.

**Comment by cedrozor** [comment]
Hi, you can check how it's done in that sample: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Web/Default.aspx.cs
