### ISSUE TITLE
Remote session exit cause

### ISSUE THREAD

**Issue by cedrozor** [cedrozor/myrtille#18]
Currently, a remote session may be closed for many reasons (not exhaustive: connection or authentication issue, user logout, session timeout, client crash, etc.).

It would nice to be able to identify the exact cause, in order to inform the end user.

**Comment by cedrozor** [comment]
Not so easy to do, as some exit cases don't raise any event, or log. Also, the end user doesn't really need an information in most cases; a redirect to the home page means the session has ended.

**Comment by cedrozor** [comment]
Well, many people may think myrtille doesn't work when redirected to the homepage without explaination, so an error message is important.

The best would be to capture the FreeRDP error message and display it into the homepage

**Comment by welsonplay** [comment]
@cedrozor I find the message very interesting, but the display must be configured, because I do not think it is interesting for a user to know what happened behind the scenes. But if you enable the Myrtille log then you could display the error message.

**Comment by cedrozor** [comment]
1.8.1 now displays a simple information dialog for connection failure, unexpected disconnect and logout. Indeed, for detailed info, FreeRDP logs must be enabled as explained into the doc (troubleshoot section)
