### ISSUE TITLE
Enumerating Usergroups is not working

### ISSUE THREAD

**Issue by Kilowatt-W** [cedrozor/myrtille#180]
Hi there,

thank you for this wonderful piece of code.

I am testing it in our Domain evironment, but when i add some sessions and assign them to a ad group.
When I give an user more then one group, only the sessions of the first group will be displayed.

Is this per design, that i have to add the group to the session ?

I would like to create some AD-groups and let the ad team make the group assignments without having to change them in the Myrtille Site.

Hope you can understand what i am meening :-)

Greetings from Austria

Wolfgang

**Comment by cedrozor** [comment]
Hi, maybe Paul (@bigpjo ) who made this feature could help you

**Comment by Kilowatt-W** [comment]
Hi

thank you for information, but Bigpjo has no issue tracker on his fork :-(

**Comment by bigpjo** [comment]
Hi.

We do not actively maintain a fork.

What issue are you having and we will try to look into it it for you.

**Comment by cedrozor** [comment]
Hi,

Sorry, I'm not not to understand your question. The way it's done in myrtille is you can bind a (rdp, ssh) host to one or several groups; if the logged in user is member of one of these groups, it can see the host and connect it.

**Comment by cedrozor** [comment]
I hope I replied to your question; if I didn't, please reopen
