### ISSUE TITLE
Installation error on Windows 10 Pro

### ISSUE THREAD

**Issue by evilmanimani** [cedrozor/myrtille#184]
I believe I have all prerequisites installed, but I'm seeing the following errors in the middle of the installation, copied from event viewer, not too sure where I should start, or what other information I should include. I did try a couple times, and once with all the other options disabled (SSL Cert, PDF Printer, Session URL):

> Myrtille -- Error 1001. Error 1001. Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index

> Myrtille -- Error 1001. Error 1001. An exception occurred during the Rollback phase of the installation. This exception will be ignored and the rollback will continue. However, the machine might not fully revert to its initial state after the rollback is complete. --> Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index

> Myrtille -- Error 1001. Error 1001. Could not find file 'C:\Program Files (x86)\Myrtille\bin\Myrtille.Admin.Services.InstallState'.

**Comment by cedrozor** [comment]
You should have more info into Myrtille.Setup.log, into the myrtille (install path) log folder.

Usually, error 1001 is a missing prerequisite, for example the IIS management console (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot)

**Comment by cedrozor** [comment]
The next version will install the myrtille prerequisites, if missing, during the setup
