### ISSUE TITLE
Reconnect and Scale option to OFF by default

### ISSUE THREAD

**Issue by laurentg78** [cedrozor/myrtille#185]
Hi,
We have an application which shuts down as soon as there's disconnect/reconnect sequence.
I found out that it was working fine as soon as in the bar I set the Scale to OFF and the Reconnect to OFF also. Unfortunately the Reconnect option switches back to ON from time to time.
Is there a way to set Reconnect and Scale to OFF by default?

Thakns,

**Comment by cedrozor** [comment]
Hi, yes you can change the settings into config.js:
Replace
`var defaultResize = browserResizeEnum.RECONNECT;`
By
`var defaultResize = browserResizeEnum.NONE;`

**Comment by laurentg78** [comment]
Perfect, thanks!!!

**Comment by laurentg78** [comment]
solved
