### ISSUE TITLE
Close tab or clear cookie when disconnect

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#186]
Is there a way to clear cookies or close the tab/redirect when user gets disconnected from WebRDP?

**Comment by cedrozor** [comment]
Cookies are indeed cleared when the session is disconnected, but only when when using myrtille into an iframe. You can force the cleanup whatever the setup, and for all the cookies if you want, [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network/websocket.js#L327) and prevent a redirect [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network/websocket.js#L331). The same thing must be done in xmlhttp.js for HTLML4.
