### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#187]
Hi, on the 2.7.0 today morning service on one of the server hang with below error details in Even Log:

```
Application: Myrtille.Services.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Diagnostics.Process.EnsureState(State)
   at System.Diagnostics.Process.get_HasExited()
   at Myrtille.Services.RemoteSessionProcess.ProcessExited(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)
```

--------------------------------------------------------

```
Faulting application name: Myrtille.Services.exe, version: 2.7.0.0, time stamp: 0x5dd40ff7
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3321, time stamp: 0x5da7fdee
Exception code: 0xe0434352
Fault offset: 0x0000000000034c48
Faulting process id: 0xafc
Faulting application start time: 0x01d5a0f5f121dde2
Faulting application path: C:\Program Files (x86)\Myrtille\bin\Myrtille.Services.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: c8b68e3a-51d0-40a1-9e41-e9f19cbb094a
Faulting package full name: 
Faulting package-relative application ID: 
```
---

**Setup info:**
OS: Windows Server 2016 
Type: VM on GCP
Hardware info: 6*CPU + 14GB RAM + 250GB SSD
Roles Installed: IIS, AD
This server works as a gateway to the RDS server
At that time there were around 10 users connected.

I did not find anything in the Myrtille Service Log, and when I started the service everything started to work normally. Currently I set up the service to try to recovery after fail, however it would be great to prevent this to happend in the future ;)

**Comment by cedrozor** [comment]
Hi, thanks for the report. I modified in 2.7.0 the way to notify a session disconnect (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L455). It was to avoid deadlocks occuring in some rare cases when invoking the callback of a WCF duplex channel; but that's not good if that brings new issues :/

I will investigate and, at least, gave that async task instanciation into a try/catch block so that it doesn't crash Myrtille.Services.exe.

**Comment by cedrozor** [comment]
Did you had the issue happening again?
If not, it should be fixed in myrtille [2.7.1](https://github.com/cedrozor/myrtille/releases/tag/v2.7.1).

**Comment by gtmsew** [comment]
It was one-time error for me.

**Comment by cedrozor** [comment]
Well... anyway, I improved the exception handling around that call, so it shouldn't happen again
