### ISSUE TITLE
Wrong credentials

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#188]
Hello,
it is possible to redirect the user to the custom page when he provides the wrong credentials?
Now it shows that the credentials are wrong, I would like to move them somewhere after that.

Thank you in advance.

**Comment by gtmsew** [comment]
Or the solution from here #186 will also work in that situation?

**Comment by cedrozor** [comment]
#186 is a global handler for session disconnect. If you want to do something specific on wrong credentials, you can do it after the dialog message (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/myrtille.js#L706)
