### ISSUE TITLE
Issue with very slow performance on MAC OS + Chrome

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#189]
One of our new users cannot use the Myrtille at all, it is not responsive, very slow, the latency is showing really high (check video).

What I notice is very high RDP latency and that the bandwidth has not been detected. Maybe the bandwidth detection is the issue here?

User has the newest Chrome and MAC OS
![Project 2](https://user-images.githubusercontent.com/51693068/70535583-9d1c2f80-1b5d-11ea-9109-9a8e38835350.gif)

**Comment by cedrozor** [comment]
Hi, I see that HTML5 (websocket + canvas) is OFF (myrtille uses long-polling and divs). Did you disabled it into config.js or just clicked the related button into the toolbar? I recon it could be confusing, these buttons are both toggles and statuses indicators. 

I assume you enabled the websocket protocol into IIS? (as explained into the documentation). If you didn't, myrtille falls back to long-polling, but should use canvas if supported by the browser (true for Chrome/iOS).

Regarding the bandwidth detection, it's based on a simple image download through xhr and time calculation; it's possible but surprising that it could fail.

**Comment by gtmsew** [comment]
Hi,

I did not disable anything and did not disable by the button. This is how it open automatically on this machine. Websockets are ON
![Project 4](https://user-images.githubusercontent.com/51693068/70538801-fc307300-1b62-11ea-91d9-0fda9c11dbc3.gif)
 I checked the network tab on that machine - no errors there.

So as you can see it works fine on my end.

**Comment by cedrozor** [comment]
The gif now shows HTML5 ON (websockets and canvas are enabled) and the available bandwidth.

Is its still a capture from the user chrome/IOS or from your own machine? (I see the connected user, "manadmin" is different).

**Comment by gtmsew** [comment]
Looks like this user was messing up with the html5 settings a bit, after full clear of cache, etc it started to working fine again,
Thank you!
