### ISSUE TITLE
Cannot see online connected users of Myrtile gateway.

### ISSUE THREAD

**Issue by romanad** [cedrozor/myrtille#193]
Hello dear support team,
I'm trying to understand if it is possible to see online connected users of Myrtile gateway?

**Comment by cedrozor** [comment]
Not directly with Myrtille, but you can use the task manager, server manager or even powershell to see the connected users (https://www.petri.com/windows-server-2012-r2-get-list-active-remote-desktop-users)

**Comment by romanad** [comment]
Okay but how to check who is connected to vpn clients (distant hosts) for those I have no access to task manager?

**Comment by cedrozor** [comment]
VPN clients? I'm sorry, I don't understand your question

**Comment by romanad** [comment]
OK, for example I have router with VPN server 
My Myrtile gateway and other my PCs where I have administrative permissions have network 192.168.1.0 (I have access to)
Remote VPN clients have network 192.168.2.0 (I have no access to those hosts). Those hosts has their own user accounts I do not control.
Can I somehow monitor if someone is connecting to those remote VPN hosts?

**Comment by cedrozor** [comment]
You can check Myrtille.Services.log (into the myrtille install path, log folder); it logs all the connections, info and exit code, so you can filter it by target address (192.168.2.x)

**Comment by romanad** [comment]
Thank you very much for the workaround. The issue can be closed.
