### ISSUE TITLE
ConnectionBrokerDbContext DB and connection string

### ISSUE THREAD

**Issue by dgcom** [cedrozor/myrtille#194]
Hi!

I've set up 2.7.1 and enabled Enterprise mode, but can't connect to anything, most probably because ConnectionBrokerDbContext is pointing to (presumably) dev test server:
`<add name="ConnectionBrokerDbContext" providerName="System.Data.SqlClient" connectionString="data source=WIN-0VSDKGKDTPI.myrtlab.local;initial catalog=RDCB;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework" />`
At least I think this is why NRE is logged:
`ERROR System.Diagnostics redirection [(null)] - Unable to get session connection details System.NullReferenceException: Object reference not set to an instance of an object.
   at Myrtille.Services.EnterpriseService.GetSessionConnectionDetails(String sessionID, Int64 hostID, String sessionKey)
` 
Disabling Enterprise mode works, but I'd like to know how to setup local ConnectionBrokerDbContext DB using SqlServer Compact...

**Comment by cedrozor** [comment]
Hi,

Indeed, it's a test server and shouldn't had made it's way into the commits. I removed it into the next version. The data source should point to the server hosting a database configured by connection broker(s) in HA mode (more info: https://ryanmangansitblog.com/2013/03/30/deploying-rd-connection-broker-high-availability-in-windows-server-2012/).

But this is only a a problem if you have set "DrainDisconnectedSessions" to true into the services config, and this is not needed by the enterprise mode. The enterprise mode use a local database.

The error you have is more likely a configuration issue or the session being expired. Are you able to login past the username/password screen? when do you have this error logged?

**Comment by dgcom** [comment]
Hi!

Thank you for looking into this. 
I did a bit more digging and realized that ConnectionBrokerDbContext is only used when DrainDisconnectedSessions is set to true. I have it set to false.

When in Enterprise mode, I can login and setup connection. However when I try to connect, nothing happens and that NRE is logged.
I plan to dig more when I have some time, but if you can tell me what additional logging/tracing I can turn on, this would be helpful.

**Comment by cedrozor** [comment]
Did you allowed yourself into the "Domain Groups or Users Allowed" field? it's a bit unintuitive I agree, I should change that to allow any member of `EnterpriseAdminGroup` to connect any host by default, without that field defined.

Or maybe your domain account is rejected by the host. If you didn't already, you should check "Prompt for credentials" for the host and try to connect with another account.

You have all connections details into Myrtille.Services.log (myrtille install path, log folder). If you want even more info, you can enable `RemoteSessionLog` into the services config (then restart the "Myrtille.Services" windows service) and check the FreeRDP logs (same log folder).

**Comment by dgcom** [comment]
Hi!

That was it - I did not set any allowed groups, thinking this would either show an error or allow everyone...
Not allowing by default is fine as long as there is some diagnostics available - that NRE in the log is not the one :)

Does Myrtille.Services.log have more verbose logging levels? I see log4net listener configured as "Information"...

And speaking of wfreerdp logs, I see that last line in the log is cut off at random, for example:
`[16:44:26:704] [6084:00000424] [INFO][com.freerdp.client.myrtille] - processInputsPipe: MMO738-657
[16:44:26:735] [6084:00000424] [INFO][com.freerdp.clie`

Other than that, this seems to be a great tool, I need to test it more.

**Comment by cedrozor** [comment]
I agree, the exception logged isn't very useful (and may even not be related to that issue).

In fact, a non admin user is displayed only the hosts it has access to. So the case where it tries to connect an host to which it doesn't have access should not happen (but if it happens, I'll try to have a better log or dialog).

An admin user is displayed all the hosts, so I think it's normal it should be able to connect all of them, regardless of the "allowed groups" setting.

"Information" is the max verbosity level with log4net. You should have more logs by having this level into web.config (but caution as it might alter the performance).

About the truncated wfreerdp logs, I guess it occurs when the output is buffered and wfreerdp doesn't flush it on exit. It happens quite rarely, I wasn't able to identify the exact cause.  I will try to have a look on it.

Thanks for your interest in the project! :)

**Comment by dgcom** [comment]
Hi!

I created host connection and was trying to access with the same domain admin user, so it might be fine to let it connect... However (coming with enterprise experience), this is not the best from security prospective - each action should have a role and then you assign roles to users or (better) groups.
Question though - who is considered admin user in this case? Member of the administrators group on the machine where web app is installed?

I am also running into another problem - I cannot login with several different domain accounts - app claims that password is expired (it is not) and prompts to change it. Changing password does not work either...
The log has only this:
`
2020-01-03 17:42:33,229 [23] INFO  System.Diagnostics redirection [(null)] - Change password for user tempadmin
2020-01-03 17:42:40,417 [23] INFO  System.Diagnostics redirection [(null)] - Requesting authentication of user tempadmin`

**Comment by dgcom** [comment]
Hi!

Regarding expired password - there seems to be a bug in ActiveDirectory.cs - when checking for expiration, you need to ignore the default case when user.PasswordNeverExpires is false but expiration date is not set - call to get PasswordExpirationDate actually returns 1/1/1970.
This does not mean that password has expired, it means that it _can_ be expired, but expiration is not set, so it is still valid.
Not sure where is this documented, but I checked quickly via VBScript that this is the case:
`set MyUser = GetObject("LDAP://CN=Temp Admin,OU=Staff,DC=drgdds,DC=lan")
wscript.echo MyUser.PasswordExpirationDate`
Current workaround is to set PasswordNeverExpires to true, but it would be best of code can work with defaults...

**Comment by cedrozor** [comment]
Hi,

Administrators for the enterprise mode are domain users members of the `EnterpriseAdminGroup`. They can create the hosts (shortcuts) and define the allowed groups or users allowed to connect them, so it doesn't make much sense to prevent them from connecting the hosts if they didn't allowed themselves to connect them.

About the expired password, this is something which was already reported (https://github.com/cedrozor/myrtille/issues/76) but was overlooked. Thanks for the investigation :) I fixed it into the upcoming release

**Comment by dgcom** [comment]
Hi!

Ok, now I got it how this is controlled, thanks a lot for clarifications :)
You are right, that Myrtille letting someone connect does not mean they will be able to, I am fine with that :)

And yes, somehow I did not find that previously reported issue with password expiration policy set to 0 (which is actually a default).

Thank you for fixing this.
