### ISSUE TITLE
Error 193 with Myrtille

### ISSUE THREAD

**Issue by vasu-senawongse** [cedrozor/myrtille#197]
Hello! First of all, Thank you for the wonderful works.

I'm trying to use Myrtille for a URL remoteApp but having a problem in opening .docx files.
.exe like notepad, and also direct MSword.exe(Winword.exe) works fine. but I want the url to open each file of Microsoft Word directly. It gave me error 193.

Another question is that can I disable the three bullet collapsed menu on the top-left of the myrtille screen? Can I use this as a part of my Senior Project, I will give the credit for sure? :)

Thank you in advance!

**Comment by cedrozor** [comment]
Hi, did you url-encoded the command line params (https://www.url-encode-decode.com/) for `&program=`?

To disable the toolbar:  https://github.com/cedrozor/myrtille/blob/5f92ee3f3783c42749baf26bd6992fa4374971c3/Myrtille.Web/Web.Base.config#L189

or you can hide it from css: https://github.com/cedrozor/myrtille/blob/2823f433f0a3c892ac3ecc9be6dd99c8c4cb8837/Myrtille.Web/css/Default.css#L214

Sure, you can use myrtille for your project, that's the magic of open source! :) if it's a publicly accessible project, it would be great if you could link it there :)

**Comment by vasu-senawongse** [comment]
I already encode the path of the program but it still doesn't work with other extension than .exe. Anyway, I solved the task by using cmd.exe and pass command to let it open .docx file by cmd instead.

**Comment by cedrozor** [comment]
Last time I tried top open a file with notepad as startup program ("`C:\Windows\System32\notepad exe /A test.txt`" -> `&program=C%3A%5CWindows%5CSystem32%5Cnotepad+exe+%2FA+test.txt`), it did worked without any problem. I haven't tried MS Word, but it's weird that it doesn't work the same way :/

So it did worked with "`cmd.exe <path>\Winword.exe <your file>`"?

**Comment by vasu-senawongse** [comment]
I didn't do as yours, that's why it didn't work. I used only "path/Document1.docx" .
Yes, it works with "cmd.exe <path>\Winword.exe <myfile>".

**Comment by cedrozor** [comment]
It's normally possible to have a relative (%) width and height with iframes, but I had it partially (?) working for the admin mockup I made for Myrtille (mockup because I don't have much time, nor the wish, to make a full blown UI for myrtille admin and preferred to focus on a REST API; letting people use their own UIs).

See https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Web/Default.aspx#L47 and https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Web/css/iframe.css#L41

**Comment by cedrozor** [comment]
Hi, did the relative iframe size worked?

**Comment by vasu-senawongse** [comment]
It seems like the width and height which defined in the url param have to be in "px". Yes, we can make it responsive with iframe because the relative width and height work with it but not with the remoteApp screen inside the iframe. By the way, it is not much of a problem, it is acceptable.

**Comment by vasu-senawongse** [comment]
I will close this issue and post another one. Could be opened again if any problem related to this.
