### ISSUE TITLE
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by wellloaded** [cedrozor/myrtille#199]
I  have just installed the latest mystille on my RDP enable Window10. As part of the installation I have left the default ports 8080 and 8008

Now visiting

https://127.0.0.1:8008 I get the following error
```

Secure Connection Failed

An error occurred during a connection to 127.0.0.1:8008. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

Not sure what went wrong there. in general also reading  the documentation it's not 100% clear to me what are the prerequisites for a standalone windows10 device. Is there a check list of items that need to be preinstalled (if any)?

Thanks

**Comment by cedrozor** [comment]
Hi, these are the ports for the myrtille services, not for the myrtille web application (hosted on IIS). More specifically, it is intended for the local communication between the web application and the services.

You are not the 1st person confused by it, so it must not be clear enough on the installation screen. I will have it more explained into the next version.

In order to use myrtille, you access it at http://yourserver/myrtille (port 80) or https://yourserver/myrtille (port 443, SSL).

**Comment by wellloaded** [comment]
That helped a lot! Thanks
There's one final point that I'm experiencing and perhaps you want to cover this in the installation section. Myrtille is reachable via 127.0.0.1:80 but not the NIC IP address.
I remember during the installation I was asked about the IP binding and ports which I left to the defaults but does the installation also take care of the relevant firewall exception?

Regardless many thanks for your hard work!

**Comment by cedrozor** [comment]
Https requires an SSL certificate installed on IIS. The myrtille installer provides the option to install one, but this only a _self-signed certificate_. Consequently, you have a add a security exception into your browser.

If you don't want that, you need to purchase a trusted certificate for your domain (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#security)

**Comment by wellloaded** [comment]
Ok not precisely my issue but that helped me to look in the right direction. Thanks! Basically I had a software running already on port 443 so I've uninstalled that first. At this point the https would still not work so I went into the IIS settings and associated a certificate to the port now it works!

Can I suggest:
-  you check the existence of a service on 443 before setting up the IIS? Also you could allow a custom myrtille webserver port so that users can have multiple servers running if needed
- It would be a good idea (still as part of the installation) to allow users to specify a custom virtual path this can be mainly for security so that the /Myrtille is not a giveaway for malicious users.

Wonderful software. many thanks!!

**Comment by cedrozor** [comment]
Thanks for you suggestion. I tried to have the installation simple but it lacks some fine tuning as a result. These are security settings, so I will try to have more of them into the installer.
