### ISSUE TITLE
binary websocket support

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#20]
Hi Cedric, it would be nice if you could support binary web socket data instead of using base64 :)

**Comment by cedrozor** [comment]
Hi Troy, good idea yes :) base64 does increase the size of data by around 30%. It would be on same upgrade logic than moving from Fleck to IIS websockets. There are some interesting stuff there: http://blog.mgechev.com/2015/02/06/parsing-binary-protocol-data-javascript-typedarrays-blobs/. Interesting too the fact that FreeRDP-WebConnect, through CloudBase, already use such techniques.

**Comment by cedrozor** [comment]
Tests in progress. Scheduled for next release (1.5.x).
