### ISSUE TITLE
Is multiple myrtille remote session possible from same browser?

### ISSUE THREAD

**Issue by wellloaded** [cedrozor/myrtille#205]
I have noticed that if I have a session open (e.g. SSH) in a Chrome tab and I open a second Myrtille session with same URL into a new browser tab, this will replicates my existing session, so essentially I'm unable to have e.g. 1 session used for SSH and one for RDP.

Just wondering if this is meant/wanted that's all.

**Comment by cedrozor** [comment]
Yes, it's normal. By copying the url, you are also copying the http session ID, which is bound to your remote session (SSH or RDP). Into a new browser tab, you only need the myrtille base url (i.e.: `https://yourserver/myrtille`). A new http session will be created, with another remote session.

If you don't want that behavior (which allows multiple connection/tabs) you can change the `sessionState` value into web.config (see comments there).
