### ISSUE TITLE
2FA Oliveinnovations has changed

### ISSUE THREAD

**Issue by DrVaskee** [cedrozor/myrtille#207]
There is no "Register for free" Button anymore. 
Also all off their documentation pages have been removed.
I didn't find an issue regarding this. Is there any plan to support a new / other 2FA provider?

**Comment by cedrozor** [comment]
It looks like @bigpjo revamped its website. Paul, any news on this? there is no plan to support another 2FA provider for the moment, but the architecture that we had set up in Myrtille is quite extensible if you wish to

**Comment by dgcom** [comment]
This is sad, I was about to register and try it out for very small number of users...
Wonder if it is possible to integrate with other TOTP solutions? I know [Duo](https://duo.com/pricing/duo-free) has free account for up to 10 users and there are more elaborate setups possible with [FreeIPA](https://www.freeipa.org/)...

**Comment by bigpjo** [comment]
Hi good afternoon all.

The free service is still available.

Registration is via www.oasis2fa.com

Our website is currently under development and apologies for the removal of
the information about our service.

**Comment by dgcom** [comment]
That is great, thank you, @bigpjo for providing direct link!

**Comment by DrVaskee** [comment]
Thank you!
But is it still working without a change?

I can't get it to working. I use the Enterprise Integration and set the username to the same as in my AD. But it always tells me, that it failed to authenticate.
