### ISSUE TITLE
Blank screen when connecting to ssh terminal over SSL(non 443 port) in chrome

### ISSUE THREAD

**Issue by deepakkataria0878** [cedrozor/myrtille#210]
Hi Team,

I have installed Myrtille on my windows 10 machine, then connect through browser. After this, I edited the application binding in IIS for HTTP and HTTPS. Everything is working fine over HTTP port. When i tried with https, the problem occurs in chrome only. It looks like the application is loading(as below).

![image](https://user-images.githubusercontent.com/2275366/76072901-c7478700-5fbe-11ea-867c-5a879ed200b4.png)

and console logs looks like as below

![image](https://user-images.githubusercontent.com/2275366/76073020-f827bc00-5fbe-11ea-8c6c-e2414ea9f3b8.png)

 This happens only in chrome. Please help me to resolve this issue.

Thanks

**Comment by cedrozor** [comment]
These errors are from "abp" = adblock plus and have nothing to do with myrtille.
You changed the default ssl port 443 -> xxx, did you opened xxx on your firewall?

**Comment by cedrozor** [comment]
Hi @deepakkataria0878, any news on this? can it be closed?

**Comment by cedrozor** [comment]
Closing for now. Please re-open if needed.
