### ISSUE TITLE
Connection through VPN

### ISSUE THREAD

**Issue by isadoravira** [cedrozor/myrtille#212]
Hello team,

First, thank you making such a great project for everyone to use, we all aprecciate it. So, I'm having a problem to make Myrtille conect through VPN, it works if the server where the project was published is connected to the VPN and also when I debug in my computer, but not if only the client is connected. My question is: is there a workaround for this?

**Comment by cedrozor** [comment]
Hi, Myrtille is a gateway between the browser and the remote server.

If I understand well, what you call "client "is the browser; but on the Myrtille perspective, the client is FreeRDP, an open source RDP client running on the Myrtille machine. You don't need the "client" to be connected to the VPN, only Myrtille needs it.

**Comment by cedrozor** [comment]
Hi @isadoravira, any news on this? I wasn't (and I'm still not) sure to understand your question. Could you be mroe specific please? did you manage to make it work?

**Comment by cedrozor** [comment]
Closing. please re-open if you still need help
