### ISSUE TITLE
Can't unselect "prompt for credentials"

### ISSUE THREAD

**Issue by Reece-Tantalus** [cedrozor/myrtille#214]
Hi there, we use myrtille for our print server and have multiple people signing in and out all day.
Is there a way to turn off the 2nd prompt for credentials? It's slightly annoying having to type in credentials twice and It never used to ask for them a second time in prior updates. I've attached some photos to better outline my issue.

Thanks for your time!

![image](https://user-images.githubusercontent.com/54325202/76544198-e1f98000-6444-11ea-9e7e-56c246476c9c.png)

![image](https://user-images.githubusercontent.com/54325202/76544273-fd648b00-6444-11ea-8f33-3a970d5666f0.png)

![image](https://user-images.githubusercontent.com/54325202/76544083-ac549700-6444-11ea-878d-f2bcb74e25d5.png)

**Comment by cedrozor** [comment]
"prompt for credentials" is checked by default and can't be unchecked with the default "local admin" mode. This is because "local admin" not a "real" user (Windows account) while connections require user accounts.

The enterprise mode relies on AD to login a domain user, whose credentials are in turn used to connect the configured servers; that's why you don't have to enter them a 2nd time (except if you want to connect with another account, and checked "prompt for credentials").

If you created the connections in "local admin" mode, the "prompt for credentials" was checked and you have to uncheck it in the enterprise mode.

**Comment by Reece-Tantalus** [comment]
Thanks for the response @cedrozor ,

But we're not using local admin, we're using our AD accounts to log in.
As is said in the documentation local admin mode should be disabled if enterprise mode is enabled no?
Am i misinterpreting something?

Thanks again!

**Comment by cedrozor** [comment]
I wasn't sure you were using local admin or AD, so I replied for both cases.

Were you using local admin when you created the hosts ? if yes, the prompt for credentials was checked when you switched to AD. Otherwise, that's a regression because prompt for credentials should be disabled by default when using AD.

Anyway, you can uncheck it on your hosts so that your users are not prompted for it.

**Comment by Reece-Tantalus** [comment]
@cedrozor We weren't using local when creating the hosts no, which is where the confusion is coming from.

We are logging in with our AD credentials.

Even when creating a new host the option is enabled and we aren't able to uncheck:
![image](https://user-images.githubusercontent.com/54325202/77091206-7e7fcd00-69c5-11ea-97d2-f1a898d5403c.png)


Below is the enterprise section of our myrtille.services.config file, please let me know if you see anything that might help.

` <localAdmin>
    
    
  </localAdmin>
  <appSettings>
    
    <add key="RemoteSessionLog" value="false" />
    
    
    
    
    
    <add key="OASISApiKey" value="login to oasis admin and go to application for value" />
    <add key="OASISAppKey" value="login to oasis admin and go to application for value" />
    <add key="OASISAppID" value="login to oasis admin and go to application for value" />
    
    <add key="EnterpriseAdapter" value="Myrtille.Enterprise.ActiveDirectory, Myrtille.Enterprise" />
    <add key="EnterpriseAdminGroup" value="****** users" />
    <add key="EnterpriseDomain" value="ad.ourdomain.com" />
    <add key="EnterpriseNetbiosDomain" value="" />
    
    
    
    
    
    
    <add key="DrainDisconnectedSessions" value="false" />
    
    
    <add key="FreeRDPBpp" value="16" />
    
    <add key="FreeRDPGdi" value="sw" />
    
    <add key="FreeRDPWallpaper" value="false" />
    
    <add key="FreeRDPAero" value="false" />
    
    <add key="FreeRDPWindowDrag" value="false" />
    
    <add key="FreeRDPMenuAnims" value="false" />
    
    <add key="FreeRDPThemes" value="false" />
    
    <add key="FreeRDPSmoothFonts" value="true" />
    
    <add key="FreeRDPCertIgnore" value="true" />
    
    <add key="FreeRDPCompression" value="true" />
    <add key="FreeRDPMouseMotion" value="false" />
    <add key="FreeRDPBitmapCache" value="true" />
    <add key="FreeRDPOffscreenCache" value="false" />
    
    <add key="FreeRDPGlyphCache" value="false" />
    <add key="FreeRDPAsyncInput" value="false" />
    <add key="FreeRDPAsyncUpdate" value="false" />
    <add key="FreeRDPAsyncChannels" value="false" />
  </appSettings>`


Again, thank you for your continued help.
Reece

**Comment by cedrozor** [comment]
It seems there is a mix between the 2 modes (local admin and AD), maybe due to the fact you  disabled the local admin, but partially.

Instead of:

```
<localAdmin>
  <!-- <add key="LocalAdminUser" value="admin" /> -->
  <!-- <add key="LocalAdminPassword" value="xxx" /> -->
</localAdmin>
```
can you try to disable the whole node, as below?


```
<!--
<localAdmin>
  <add key="LocalAdminUser" value="admin" />
  <add key="LocalAdminPassword" value="xxx" />
</localAdmin>
-->
```

**Comment by Reece-Tantalus** [comment]
@codrozor Ok, tried that. Restarted myrtille.services and myrtille.admin.services...
No change, still unable to uncheck "check for credentials" and still have to input username and pass twice.

**Comment by cedrozor** [comment]
Can you try to enter the netbios name of the domain? it was optional before but now is required.

```
<add key="EnterpriseAdapter" value="Myrtille.Enterprise.ActiveDirectory, Myrtille.Enterprise" />
<add key="EnterpriseAdminGroup" value="****** users" />
<add key="EnterpriseDomain" value="ad.ourdomain.com" />
<add key="EnterpriseNetbiosDomain" value="" />
```

**Comment by Reece-Tantalus** [comment]
@cedrozor
AH, that's done it! 
I can uncheck "check for credentials" now and all it working as expected!

Thank you so much for your help Cedrozor, greatly appreciated!
