### ISSUE TITLE
can't connect in enterprise mode "Unknown error occured"

### ISSUE THREAD

**Issue by fgcorti** [cedrozor/myrtille#216]
Hello,

when I parameter the enterprise mode, I can connect to myrtille with a admin account member of a active directory group. I can create a RDP host. I can use the RDP host in the administrator interface.
In the "Domain Groups or Users Allowed (comma separated)" i try a active directory group or user, but i can't connect with this account and the message "Unknown error occured" is displayed.
If I don't use enterprise mode, the account work well.
Can you help me ?
Thanks

**Comment by cedrozor** [comment]
Hi, can you check the related entry into <myrtille path>\log\Myrtille.Services.log? is the problem only with this account or with anothers also?

**Comment by fgcorti** [comment]
Hi, there is all elements in the attached file. Thanks
[myrtille_error_fgcorti.docx](https://github.com/cedrozor/myrtille/files/4368086/myrtille_error_fgcorti.docx)

**Comment by cedrozor** [comment]
Could you please send me as a simple .log (text) file?

**Comment by fgcorti** [comment]
here there is the log file. Excuse me but I not read the end of the log file the first time.
You can find two account who's dont work  : oec\fcornet and oec\guidicelli
The oec\admin_cornet work.
Thanks
[Myrtille.Services.log](https://github.com/cedrozor/myrtille/files/4373838/Myrtille.Services.log)

**Comment by cedrozor** [comment]
I don't see any error into the logs; the connection of your admin_cornet user seems to work well.

Do you have something relevant into Myrtille.Web.log?

**Comment by fgcorti** [comment]
Hi,
the Myrtille.Web.log is empty.
But I think that I have find the reason.
My admin_cornet account in the admin myrtille group (in Myrtille.Services.exe.Config) is a active directory admin. It's the only user that worked.
If I put an other active directory admin account in the user group of myrtille (RDP host interface), this account can access to the myrtille dashoard without admin right and can access to rdp server.
is it a right access problem in IIs ?

Thanks

**Comment by cedrozor** [comment]
Hi, there are different access rights. The groups or users you enter for an RDP host is only to define the people who will see this host into their dashboard. It doesn't mean they _can_ connect it, such a thing is checked by the RDP host against the user credentials.

IIS is something else entirely and has nothing to do with the hosts dashboard or RDP access rights.

**Comment by cedrozor** [comment]
Hi @fgcorti, did you manage to make it work?

**Comment by fgcorti** [comment]
Hi,

no,
Now, we use Microsoft RD Gateway en Cisco Duo.

Thanks,

De : cedrozor <notifications@github.com>
Envoyé : mercredi 27 mai 2020 09:39
À : cedrozor/myrtille <myrtille@noreply.github.com>
Cc : Cornet Fabrice -OEC- <Fabrice.Cornet@oec.fr>; Mention <mention@noreply.github.com>
Objet : Re: [cedrozor/myrtille] can't connect in enterprise mode "Unknown error occured" (#216)


Hi @fgcorti<https://github.com/fgcorti>, did you manage to make it work?
