### ISSUE TITLE
A parameter cannot be found that matches parameter name 'FriendlyName'.

### ISSUE THREAD

**Issue by petemoore** [cedrozor/myrtille#218]
I get the following error in `C:\Program Files (x86)\Myrtille\log\Myrtille.Web.Install.log` when installing on Windows Server 2012 R2:

```


Path           : 
Online         : True
Restart Needed : False

Enabled IIS, WebSocket protocol, management console and tools

Path           : 
Online         : True
Restart Needed : False

Enabled .NET extensibility

Path           : 
Online         : True
Restart Needed : False

Enabled WCF/HTTP activation

A parameter cannot be found that matches parameter name 'FriendlyName'.
```

Many thanks.

**Comment by cedrozor** [comment]
Hi, thanks for your report. It looks like powershell doesn't like this line:
`$Cert = Get-ChildItem -Path "Cert:\LocalMachine\My" | Where-Object { $_.FriendlyName -eq "Myrtille self-signed certificate" }`

I don't remember having this issue with 2012 R2; is your machine up to date? (powershell mostly).

To avoid this issue, waiting for me to fix it, you can uncheck the SSL option during the myrtille install, and create a self-certificate manually afterward (using the IIS management console) or (better) install a production certificate (so your users don't need to add a security exception into their browser).

By the way, I will replace the self-signed certificate by a let's encrypt or equivalent SSL certificate into the next version.

**Comment by petemoore** [comment]
> Hi, thanks for your report. It looks like powershell doesn't like [this line](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1#L32):
> `$Cert = Get-ChildItem -Path "Cert:\LocalMachine\My" | Where-Object { $_.FriendlyName -eq "Myrtille self-signed certificate" }`
> 
> I don't remember having this issue with 2012 R2; is your machine up to date? (powershell mostly).

It is the default Windows Server 2012 R2 environment in AWS EC2.

> 
> To avoid this issue, waiting for me to fix it, you can uncheck the SSL option during the myrtille install, then create a self-certificate manually afterward (using the IIS management console) or (better) install a production certificate (so your users don't need to add a security exception into their browser). Don't forget also to bind this certificate to the myrtille web application into IIS.

Perfect, many thanks!

> By the way, I will replace the self-signed certificate by a let's encrypt or equivalent SSL certificate into the next version (to avoid the security exception into the browser).

Great, many thanks. 👍
