### ISSUE TITLE
Shift not working in standard mode

### ISSUE THREAD

**Issue by willkruss** [cedrozor/myrtille#221]
Hi Cedrozor,

It seems that in standard mode shift isn't working properly. CAPS lock seems to work - although often it's reversed. But Shift does not work most of the time. Often double pressing and then holding shift may work, sometimes holding shift for a few seconds before typing works, and other times it doesn't. Often after getting shift to function, letting go of shift and typing still results in capital letters.

Is there any chance of a fix for this issue as well as issue #204. I'd be happy to pay you a few hundred dollars to get this fixed.

Cheers,
Will

**Comment by cedrozor** [comment]
Hi, what are the local (OS, browser) and remote (OS) specs ?

**Comment by willkruss** [comment]
Hi,

 

Using Chrome locally. Myrtille is running on a Windows 2019 server, installed using your msi file.

 

The RDP is using GUID/PCB ID to connect via internal RDP (port 2179) on hyper-v back end.

 

We have a solution that works fine and has no keyboard issues with wsgate/freerdp but it hangs frequently due to them using outdated EHS integration – and hasn’t been updated in quite a long time.

 

Cheers,

Will

**Comment by willkruss** [comment]
Hi mate,

 

Just letting you know we have gone with the wsgate/freerdp solution at this stage. Your solution does look good, but requires the keyboard mapping issues to be fixed.

 

Cheers mate,

Will

**Comment by cedrozor** [comment]
Hi @willkruss, in order to help me to fix the keyboard issues, could you please tell me what was the OS used with Chrome and what was the OS of the target server? (Windows or Linux xRDP)

I'm trying to cross match the issue with https://github.com/cedrozor/myrtille/issues/222

Thanks

**Comment by willkruss** [comment]
Hi,

 

Windows 10 with Chrome.

 

OS of the host server is Windows 2016 Hyper-V RDP (connection using a PCID/UID) on port 2197.

 

The eventual target VM is both Linux and Windows, same behaviour on both.

 

Thanks,

Will

**Comment by philipe234** [comment]
Hey, we got the exactly same problem, Shift is not working. Tested with Chrome, Edge and Mozilla with latest myrtille version. Myrtille is installed on Windows Server 2019 Core

**Comment by cedrozor** [comment]
the next version will include an on-screen virtual keyboard in case of any keyboard or send text issue.
