### ISSUE TITLE
"Keyboard" doesn't always send the entire text field

### ISSUE THREAD

**Issue by jean-martial** [cedrozor/myrtille#222]
With Firefox on Debian, "Keyboard" doesn't always send the entire text field.
Here, the Send action stop after the "v":

![image](https://user-images.githubusercontent.com/25341843/82811016-5312d600-9e7f-11ea-82ed-1f0c320d3411.png)

**Comment by cedrozor** [comment]
> With Firefox on Debian, "Keyboard" **doesn't always** send the entire text field.

Is it random? or when using special chars like "@" which could mean an encoding issue? do you have any addon on Firefox and does the problem also occurs with Chrome on Debian? if yes, it would be useful to sniff the network trafic to see what is sent or not with Firefox.

Does the problem also occurs with the clipboard (requires an https connection)?

**Comment by cedrozor** [comment]
the next version will include an on-screen virtual keyboard in case of any keyboard or send text issue.
