### ISSUE TITLE
Clavier AZERTY perdu

### ISSUE THREAD

**Issue by jtotec** [cedrozor/myrtille#223]
Bonjour,

Le clavier change tout seul de mode QWERTY à AZERTY et vice versa. Une déconnexion/reconnexion peut parfois résoudre le souci.

José

**Comment by cedrozor** [comment]
Bonjour, il y a peut-être une désynchro entre la langue/clavier côté serveur et celle côté client; ou bien la session peut être buggée, ça arrive parfois; auquel cas se déconnecter/reconnecter ne suffit pas, il faut fermer et relancer une nouvelle session.

**Comment by jtotec** [comment]
Bonjour

Merci le logiciel est très très utile,

Merci encore, José

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
