### ISSUE TITLE
Oasis not working

### ISSUE THREAD

**Issue by AceMoneus** [cedrozor/myrtille#224]
It seems like Olive Innovations no longer support free accounts, or at least the link oasis.oliveinnovations.com doesn't work any more, and there is no new link to be found on their site. So, there seems to be no way for new users (and existing?) to use MFA :(

**Comment by cedrozor** [comment]
@bigpjo Hi Paul, this question is for you ;)

**Comment by bigpjo** [comment]
Hi.

Sorry the documentation should be updated.

Oasis was moved to its own domain. 

Available at www.oasis2fa.com

It is still free for 10 users per month.

Enjoy

**Comment by AceMoneus** [comment]
Ah, great. Thanx 😊👍

**Comment by cedrozor** [comment]
Documentation updated in next release. @bigpjo, I wasn't able to find the link to download the "Gateway application", for people who want to sync their Active Directory with Oasis when using Myrtille in Enterprise mode. Do you still have such feature?

**Comment by bigpjo** [comment]
Hi cedric.

Yes we are updating our site. Will be there within next 7 days
