### ISSUE TITLE
Transfert files like printer.

### ISSUE THREAD

**Issue by dgnice** [cedrozor/myrtille#225]
Is it possible to send file like printer ?
My idea is to send an Excel file .
Do you know the way to send file to Websockets ?
( exemple save to \\tsclient\webfile or another )
Thanks for you nce work !

**Comment by cedrozor** [comment]
Bonjour Dominique,
Oui, via websocket ou le classique http post (input=file); puis envoi en utilisant, en effet, le point de montage \\tsclient (redirection de lecteur) ou bien un virtual channel RDP dédié. Nous pourrons discuter de cela bientôt.
