### ISSUE TITLE
wallpaper not displaying.

### ISSUE THREAD

**Issue by eaymon** [cedrozor/myrtille#226]
Hi, 

I have been trying to get a background image to display but I am experiencing some issues in doing so. I can get it to load when i RDP in but not through Myrtille.

i saw this:
https://github.com/cedrozor/myrtille/issues/73

set both of the following to true, restarted the services and server and haven't had any luck
`<add key="FreeRDPWallpaper" value="false" />

<add key="FreeRDPAero" value="false" />
`

**Comment by cedrozor** [comment]
Hi, could you please enable the FreeRDP logs? (<myrtille install path>\bin\Myrtille.Services..exe.config, set `RemoteSessionLog` to "true" then restart Myrtille.Services, https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L210). Then check the <myrtille install path>\log folder, wfreerdp_<pid>.log

This is either a FreeRDP regression or, more probably, a configuration issue with the RDS role or target server.

Do you have other machines to test with ? (other than Windows Server 2012 R2)

**Comment by cedrozor** [comment]
@eaymon, did you found any relevant info into the FreeRDP logs?

**Comment by eaymon** [comment]
@cedrozor i've only been able to look into this today. 
this is a non issue(problem between the keyboard and the back of the chair)
we were modifying the wrong directory for myrtille. We have multiple branded websites but one instance of myrtille running from the program files directory. we had copied the files over for each site but the services were only using the program files instance... sorry to waste your time.
