### ISSUE TITLE
Myrtille 2FA with Azure AD

### ISSUE THREAD

**Issue by msantosh07** [cedrozor/myrtille#227]
Just want to understand whether Azure based MFA can be utilized for Myrtille tool to login the RDP session. We are planning to utilize this services for users who are accessing their corporate based servers/desktops over the internet through RDP/SSH session. So they will utilized existing MFA (Azure MFA) option which currently being utilized by other application.
Need your expert advice.

**Comment by cedrozor** [comment]
@bigpjo Paul (who implemented 2FA and SSH in Myrtille), could you please help me answer this question?

**Comment by bigpjo** [comment]
You would need to implement single signon using openid connect. This would allow you to authenticate against azure ad.

However, using this approach would lose all of the functionality supported by enterprise mode without major development to myrtille.

An example would be that would you would have to signon to each individual server

**Comment by msantosh07** [comment]
Thanks for your response & regret for my delayed replay.

I am not a developer & do not understand much more about programming. Could you please guide how to integrate Myrtille RDP connectivity with OpenID connect so we can utilize the Azure AD authentication.

Thanks in advance.

________________________________
