### ISSUE TITLE
2.9.0 Pre-Release

### ISSUE THREAD

**Issue by gabriele-v** [cedrozor/myrtille#228]
Hi,
is it possible to have the MSI of version 2.9.0? Maybe it could be issued a Pre-Release in Github?

Thanks

**Comment by cedrozor** [comment]
Hi, Myrtille 2.9.0 normally goes out of beta this month

**Comment by gabriele-v** [comment]
Ok, I can wait

**Comment by cedrozor** [comment]
2.9.0 is released
