### ISSUE TITLE
How can export the report of users & devices which registered in Myrtille solution (RDP/SSH)

### ISSUE THREAD

**Issue by msantosh07** [cedrozor/myrtille#229]
How can we export the report about the users & devices (servers/desktop) which got connected through Myrtille solution. What is way  to export such reports.

**Comment by cedrozor** [comment]
You can:

- Use the Myrtille `Connection API` which hooks all connection events (Myrtille.Admin.Services)
- Parse the `Myrtille.Services.log` file (Myrtille\log folder)
- Export the `Windows event logs` related to RDS (if you use a RD connection broker, it should also have many logs)
