### ISSUE TITLE
How to resize desktop to fit browser container?

### ISSUE THREAD

**Issue by seanvree** [cedrozor/myrtille#23]
First, this is amazing!!! THANK YOU!!!

Second, 

is there a way to set the desktop size?  I'm using https://github.com/mescon/Muximux as a "docker" to get to Myrtille.   However, the desktop is always cut off on the edges as the browers shows scroll bars. 

Is it my settings??? or is there a way to make the desktop size fit the browser dimentions?

THANKS AGAIN!

AWESOME!

**Comment by cedrozor** [comment]
Hi, thanks for your support! :)

Regarding the remote desktop size, Myrtille does autodetect it from the browser size. The session is not resized dynamically afterward (if you resize the browser after the connection); so make sure to adjust your browser size prior to connect (ie: F11, fullscreen).

You can also define it manually from the URL by setting "width" and "height" into the querystring as described [here](https://github.com/cedrozor/myrtille/wiki/Start-program-from-URL).

I didn't knew Muximux, it's interesting :)

**Comment by seanvree** [comment]
@cedrozor,

Yeah, I'm testing with Chrome, and if I go into full screen, then it's sized properly, or if I zoom out to 90%, then it fits, but if I launch a browser windows and go to my server, initially the desktop will be cut off vertically and horizontally. I've tested on Firefox as well.  You will see in my screenshot posted below the scroll bars on the x and y axis...they are always there unless i go into full screen, our zoom the browser viewing area to less than 90%. You'll see the bars when the browser in "maximised" and scaled:

See screen shots:

http://imgur.com/0WeLgXs

http://imgur.com/SSJzNAD

I'm testing without using Muximux, so It's not that.

**Comment by cedrozor** [comment]
Thanks for the screenshots.

I will investigate that. Maybe I should substract the scrollbars width from the browser size before sending it to the gateway.

I keep you updated.

**Comment by seanvree** [comment]
@cedrozor , Yup, I think that's it.
