### ISSUE TITLE
Program Arguments?

### ISSUE THREAD

**Issue by robdplatt** [cedrozor/myrtille#231]
I may have missed something, but I can't seem to figure out how to launch an application with a command-line parameter. I URL encoded the query string parameter...

For example, "c:\windows\system32\cmd.exe /c ping 127.0.0.1" is "program=c%3A%5Cwindows%5Csystem32%5Ccmd.exe%20%2Fc%20ping%20127.0.0.1"

But it fails to launch with an access denied error. 
I can launch cmd, and many others apps, without parameters. I'm also the owner of the server so there isn't any permission issues.

![image](https://user-images.githubusercontent.com/13525487/95383932-bf2b2f00-08a0-11eb-92aa-cdeeac690788.png)

I did see this thread https://github.com/cedrozor/myrtille/issues/41

**Comment by cedrozor** [comment]
This is a configuration issue. Check this link: https://social.technet.microsoft.com/Forums/windowsserver/en-US/9c78b735-2929-4f8c-ac7f-3d93efd0f322/using-dynamic-commandline-arguments?forum=winserverTS

![image](https://user-images.githubusercontent.com/17749498/95465701-beb39680-097b-11eb-895b-7e356c698154.png)

**Comment by robdplatt** [comment]
Thanks, @cedrozor! That's what I was missing.
