### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by fabioparra** [cedrozor/myrtille#232]
Hi @cedrozor, first, thanks for your excellent work on this project.
What I'm missing most is file transfer, without a network share.
Do you have plans to implement, like asked in #225 ?
What I really need is the core part: your fork of FreeRDP + a way to send files in the Named Pipes, like the inputs, updates and audio.

**Comment by cedrozor** [comment]
Hi, @fabioparra, yes I plan to improve file transfer in a future version but, unfortunately, I don't have the time for now (but I could find the time if it's a sponsored feature).
