### ISSUE TITLE
Interactive query for username / password!

### ISSUE THREAD

**Issue by dergizzle** [cedrozor/myrtille#234]
I am this close to what I wand using Myrtille, finally (a Windows based and easy to use RDP and SSH Web gateway). Maybe there's a chance for the last step as well.

The use case is this: for ease of use we created a sort of "virtual machine overview" system of our environment, web based. I want to add a button to a VM "Connect via RDP" (and also Connect via Hyper-V Console where applicable). Now, I know (how) I can call an RDP connection via Myrtille directly via URL. However it does require username / password directly in the URL. Which I will not get permission for, I know this much.

Same for any "user-side" workarounds (like: use jscript to query for credentials and then build the URL from that). 
Creating hashes for every user of this solution is not feasible too because they each would have to create their hash on the Myrtille machine and I'd have to save this into a database for sorts to build individual links and so on.

Is there any way to leave username & password free in the connection options and then have Myrtille query this from the user directly (comparable to mstsc)? That would be ideal because nothing gets passed around easily readable and I could finally implemnt this.

Thanks for listening. ;)

**Comment by cedrozor** [comment]
Yes, you have 2 solutions for that:
- [Disable the NLA requirement](https://kb.parallels.com/en/123661) on your target server then select "RDP" as security mode with Myrtille (or use `&securityProtocol=1` in url). The RDP communication is still encrypted (TLS) and is server side anyway (between the Myrtille gateway and your VM). If you don't pass credentials (from the Myrtille login page or URL), the user is prompted to enter its credentials into the Windows login screen. If you pass credentials , the connection is direct (like NLA).
- Use the Myrtille [Connection API](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Web/Default.aspx.cs#L126) (REST) to prepare the connection server side, then connect from the browser by passing a connection ID (`&cid`= in URL, usable once)

**Comment by dergizzle** [comment]
Disabling NLA will not be possible, our security guys would rain down fire if I'd ask. Solution number two is something I will look into, thank you! It's been a few moons since I've done coding beyond some PS scripting ...

**Comment by cedrozor** [comment]
Closing now. Please re-open if you have any issue with the connection API.
