### ISSUE TITLE
Microphone support in Myrtille

### ISSUE THREAD

**Issue by clusteruk** [cedrozor/myrtille#236]
I tried searching for this, but my use case requires Microphone input and FreeRDP does support it. However, I cannot find any documentation on whether Myrtille supports Microphone redirection.

So I wonder if you can say if this is possible, in the roadmap, or not possible.

Thanks in advance.

Steve

**Comment by clusteruk** [comment]
I have seen this so does that mean no?

        public override void OnMessage(byte[] message)
        {
            // no input is expected on the audio websocket
            // if such a thing should occur (i.e.: microphone support), handle the incoming data here
        }

Steve

**Comment by cedrozor** [comment]
Hi Steve, yes, I unfortunately don't have the time to do it. Any help would be appreciated.

**Comment by cedrozor** [comment]
related to #220
