### ISSUE TITLE
v2.9.0 copy & paste disconnected from session

### ISSUE THREAD

**Issue by kevinbaroro** [cedrozor/myrtille#237]
I think this issue is already solved on v2.8.0 but in the latest release when trying to copy & paste on myrtille i get disconnected.

**Comment by cedrozor** [comment]
A part of it was fixed yes, I fixed another case which will be present into the next release https://github.com/cedrozor/FreeRDP/commit/8caf2324527cb89e82b325310d7b1947bc0d8b81

**Comment by kevinbaroro** [comment]
Thanks for the response @cedrozor. This time i encountered on sticky notes when copy and pasting result to disconnection. May i ask if this fixed also addresses the issue i mentioned? Thanks

**Comment by cedrozor** [comment]
It could yes, but it remains to test

**Comment by cedrozor** [comment]
Closing. Please re-open if still not working in [latest Myrtille version](https://github.com/cedrozor/myrtille/releases/latest).
