### ISSUE TITLE
Remote app not started in myrtille

### ISSUE THREAD

**Issue by umeshpatil12** [cedrozor/myrtille#238]
I installed myrtille 2.9.0 on a Windows Server 2019.
I installed myrtille on 1st server and want to open the start app of 2nd server.
Everything works fine except for the "run a program" option.

This is an example that gives me the desktop and not the MSPaint
http://Servername:8008/MyrtilleAdmin/ConnectionService/GetConnectionId

{"User":{"Domain":"","UserName":"Administrator","Password":"***"},"Host":{"HostType":0,"SecurityProtocol":0,"IPAddress":"Servername2"},"VM":null,"AllowRemoteClipboard":true,"AllowFileTransfer":false,"AllowPrintDownload":true,"AllowAudioPlayback":true,"MaxActiveGuests":3,"StartProgram":"C:\Windows\System32\mspaint.exe","GatewayUrl":"http://Servername/Myrtille/"}

Am I missing anything?

**Comment by cedrozor** [comment]
It's probably a config issue, or maybe a Windows Server 2019 issue, which has been found to have some issues regarding RDS so far (see [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services)).

To register a remoteapp, read [this](https://www.beyondtrust.com/docs/privileged-identity/app-launcher-and-recording/installation/set-up-rds.htm).

You can find more information about this recurring issue by looking at the other (resolved) [issues](https://github.com/cedrozor/myrtille/issues?q=is%3Aissue+remoteapp), this one in particular: https://github.com/cedrozor/myrtille/issues/144
