### ISSUE TITLE
Tracking and limiting usage

### ISSUE THREAD

**Issue by birbilis** [cedrozor/myrtille#24]
I need to track and limit RDP access (say with allowed hours per day or week/month) of a number of users to a limited (less than the number of users) set of machines.

I'm considering changes that could be done to Myrtille to do this tracking & limit enforcing. Or should I do these changes to some other item in the whole pipeline?

Any tips? thanks in advance

**Comment by cedrozor** [comment]
You should track and enforce this at the rdp server level. See https://technet.microsoft.com/en-us/library/ee791741(v=ws.10).aspx and https://www.youtube.com/watch?v=5mV5WuSL5L4

**Comment by birbilis** [comment]
thanks, I wasn't meaning that. I will try to elaborate:

I setup a small lab where there is
- 1 Windows 2012 R2 server machine (server is connected to the Internet)
- 4 Windows 10 Workstations

users connect via a VPN to the server which provides access to the internal network where the 4 workstations are

I want to use the gateway to have the users login once and be passed on to one of the available machines:
1) without logging out an other user that is currently on any of those
2) counting the time they use the machine (maybe also using the policy you mention above to have them logged out if they forget to do it, although it doesn't matter much if they log out since an RDP connection will log them out - that is if I can find out via the HTTP gateway webpage if some machine is active or not)
3) not allowing them to log in if they've exceeded some time limits for this day/week/etc. in total for any of the 4 machines. This is cause the users are more in number than the available machines

btw, can Myrtille (or FreeRDP) do brokerage and pass an incoming RDP user to one of more RDP servers (workstations I mean)? Ideally without having to install an agent at the workstation to avoid users trying to mess with it.

if one only accesses RDP via the web browser I'd expect all the above can be implemented

**Comment by birbilis** [comment]
btw, I'd like to avoid the VPN connection step I mention above so that users don't try to connect to workstations directly via RDP, but it's a security policy of that organization that they shouldn't access the server via the RDP port etc. (have to access a VPN service at that server machine first)

**Comment by birbilis** [comment]
I'm also looking at CABS (https://github.com/birbilis/CABS) but that one uses an Agent at the client machine (since it doesn't use a web browser for access but HP RGS client instead). Don't mind the RGS since those are HP Workstation machines that support it (maybe it is even faster than RDP in that case), but would like to avoid installing an agent at client machines.

So is Myrtille not looking at adding such features? If you're interested I could look into implementing such, although I'm at a tight schedule and might go for adjusting CABS to fit my needs instead

**Comment by cedrozor** [comment]
You may want to have a look at the [RD Connection Broker](https://technet.microsoft.com/en-us/library/cc771419(v=ws.11).aspx). FreeRDP does support it, so should Myrtille (as it uses freeRDP at core).

Having a VPN to provide access to your intranet should not be an issue if you have it on the gateway (itself into a DMZ); it will be hidden from the end users (accessing myrtille through their browsers).

Regarding the monitoring of the active RDP sessions, you can use the [RD Services Manager](https://technet.microsoft.com/en-us/library/cc754930(v=ws.11).aspx) or the [RD Management Server](https://blogs.technet.microsoft.com/askperf/2012/10/30/windows-8-windows-server-2012-remote-desktop-management-server/) on Windows Server 2012 or above.

**Comment by birbilis** [comment]
thanks for the pointers, after looking those up a bit (was already aware of the RD connection broker and gateway, hadn't realized though that the RD Management Server on Win Server 2012 centralized in one place all those separate RD management tools the 2008 server had)

doing some search in Microsoft Technet Forum on Remote Desktop Services, came across this question
[](https://social.technet.microsoft.com/Forums/windowsserver/en-US/aad88949-82d9-4ad7-a9bd-b095bd303add/how-to-set-max-time-limit-for-a-windows-server-user-account?forum=winserverTS 
) where UserLock was being mentioned
http://www.isdecisions.com/products/userlock/restrict-user-logon-hours-force-logoff-windows-domain.htm
it is commercial but seems to be quite cheap (http://www.isdecisions.com/products/userlock/pricing.htm) and also mentions educational/non-profit discount (looking to use it for a university lab)

btw, at
http://www.isdecisions.com/products/userlock/restrict-user-logon-hours-force-logoff-windows-domain.htm
writes:
> Windows does provide logon time restriction functionality on a user-by-user basis but there is no way to manage it by group for multiple users

Not sure where that functionality is provided in Windows, but could possible tap to it programmatically to apply to more users, similar to how UserLock does

**Comment by cedrozor** [comment]
UserLock seems nice for your needs. There are alternatives, such as [LimitLogin](https://technet.microsoft.com/en-us/library/5199b8d4-e045-4bdf-b35c-779ec57c34d3) ([comparison](http://www.isdecisions.com/blog/it-security/limitlogin-vs-userlock/)).

Personnaly, I would check for a native solution such as a [GPO](http://www.rebeladmin.com/2014/06/use-of-group-policies-to-control-log-on-hours-to-the-network/), that you could [tap in programmatically](https://msdn.microsoft.com/en-us/library/ee840126(v=VS.85).aspx).

There are many commercial solutions to monitor the network activity, including the RDS layer. [PRTG](https://www.paessler.com/manuals/prtg/wmi_terminal_services_sensor_2008) seems quite complete.

**Comment by birbilis** [comment]
Did some extensive search on it at MS forum I mentioned above, seems LimitLogin is for up to server 2008 only and can't count usage time per user and limit it say per week, was mostly to avoid multilogin.

There is no group policy to do it, only limit continuous session time from what I understand. Would be nice to be able to do via GPO programmatically

There are some shell scripts to limit multilogin but condidered insecure

**Comment by birbilis** [comment]
In short I need something like screentime (on any remote workstation of the lab) limit of microsoft family safety but per week for my users. And need RDP connector usage so as not to steal active session from a user by someoneelse RDPing to machine (btw can that behavior of rdp be turned off? not log out other user I mean)

**Comment by cedrozor** [comment]
I'm not sure if something like this does exist natively for Windows. I stumbled on your post on the MS forum https://social.technet.microsoft.com/Forums/office/en-US/aad88949-82d9-4ad7-a9bd-b095bd303add/how-to-set-max-time-limit-for-a-windows-server-user-account?forum=winserverTS; if UserLock does it and is cheap, you should use it.

Regarding GPO, if I refer on what I see at http://www.rebeladmin.com/2014/06/use-of-group-policies-to-control-log-on-hours-to-the-network/, you can select and apply logon time for multiple users ().

About session stealing, it may occurs when you have a user restricted to a single connection (and have it login again from another workstation) or if you reached the maximum number of connections on an rdp server (and a new login need to free a slot). You can disable this restriction https://social.technet.microsoft.com/Forums/office/en-US/a26af954-c2ef-4beb-b892-9e7717518850/allowing-users-to-open-multiple-remote-sessions-on-windows-server-2012-rds?forum=winserverTS and extend this number https://technet.microsoft.com/en-us/library/cc753380%28v=ws.11%29.aspx.

**Comment by birbilis** [comment]
Limiting the number of connections on the session host might be useful on a server, in my case I guess the connector redirects directly to each workstation which can have 1 connection. Guess the connector is clever to not redirect to used machine, but since my users have to enter via vpn the lab network (that sec policy I mentioned) I'm afraid they might try to connect to machines directly, which logs out the other user. If I can set that limit you mention on each machine it would be nice, but not sure if it will disable that behaviour (when connector is bypassed I mean, assuming connector is clever enough). 

In fact since there are just four machines could even skip a connector and have some status shown them on which connections are available to try (not scalable of course). With default behaviour of RDP though this logs out the user on some machine if other tries to login

**Comment by birbilis** [comment]
also since I was speaking of MS Family Safety -like control but weekly instead, looked a bit into parental control software that might do the same job with weekly usage limit: Time Boss Pro - http://nicekit.com/computer-time-limit-free-pro.htm seems to be able to do both daily and weekly usage limits  (judging from screenshot and their FAQ) but more home-oriented than enterprise (one license handles 3 PCs). FAQ says one can share time limits on multiple PCs by making sure user's "Full name" is the same on each one (and setting the software to have its database and settings on a server share)

**Comment by cedrozor** [comment]
When you say "connector", you mean an RD connection broker? if yes, its role is to make users to reconnect their previously opened sessions, avoid stealing someone else session, and dispatch the new sessions to available session host servers into the farm. The configuration of a server, regarding the single session restriction and maximum number of connections (and even CALs), will be enforced even if the broker is bypassed. Also, if your servers and users are into a domain, the time limits for your users will be enforced whatever the server connected.

If your users enter the lab through Myrtille, they won't have to use a vpn because they just need a browser, either from the university intranet or internet. You can setup a vpn on the gateway (the machine on which myrtille is installed) if you wish, if it's into a DMZ.

Regarding the parental control software you mention, it seems a bit old school. When I read 
> one can share time limits on multiple PCs by making sure user's "Full name" is the same on each one

I think you should have your servers and users into the AD and setup a domain GPO (as detailed here http://www.rebeladmin.com/2014/06/use-of-group-policies-to-control-log-on-hours-to-the-network/).

Nice use case for Myrtille anyway :)

**Comment by birbilis** [comment]
Wasn't sure the workstations would always consult connection broker even when contacted directly, thus avoiding logout of currently loggedin user, thanks for the tip. 

That Time Boss one is old school indeed, but seems to be well crafted - it even claims even admin on workstation can't bypass it. Only problem it has is it may need reinstallation after big windows updates (like win10 anniversary update accordingbto their FAQ). 

UserLock in contrast is more appropriate to enterprise environments and have many clients in that area, the other one is more targeted to home environments or maybe smallbiz/schools too.

Regarding GPOs and login hours, Microsoft didn't even think of implementing a daily total logon hour limit, just allowed timeframe. One explanation I read was that Active Directory uses distributed db or something and would need some work to track usage time consistently. However LimiLogin (for up to server 2008) was keeping data in ActiveDirectory (just for limiting simultaneous login though), so probably one could implement similar logic to track logon time, with some agent though on each pc like UserLock has

**Comment by cedrozor** [comment]
No, I don't think a session host server will consult the connection broker if contacted directly; it's the [server configuration](https://technet.microsoft.com/en-us/library/cc731496%28v=ws.11%29.aspx) which will be enforced. See the [settings](https://technet.microsoft.com/en-us/library/cc726044(v=ws.11).aspx)) regarding the connections handling to avoid to logout a currently loggedin user. 

Yes, it's surprising that Microsoft didn't implemented an user logon time quota. So, UserLock does it if I understood well? you should use it over Time Boss I think.

**Comment by birbilis** [comment]
A sorry, I thought from your text above that was the case with the connection broker, since I had read somewhere that it consults the connection broker. However it may have been when connection is done via RD connection gateway (connection request going via gateway resulting in consulting the connector or something like that). Have seen the settings you had already mentioned before, hope they also apply on Windows 10 Pro Workstations, not just on Windows Server. I need incoming RD requests there to not logout the current user. With that one could avoid the broker too when there are very few connections that one can try one by one (apart from the helpful feature of the broker that reconnects you to previous session on the same machine if you had lost connection and session hasn't still timed out)

UserLock does indeed can count user logon quota per day and per week too (maybe other periods too) from what I've seen in their screenshots. Seems quite robust and definitely enterprise-grade s/w

Regarding their pricing, from what I understood by replies (from their CEO or something) at Technet Forum on Remote Desktop that I had mentioned above, it is for simultaneous connections that they charge. So it is by number of workstations usually when not doing VDI but have real machines. They can also limit sessions to IIS, limit wifi users etc. and need separate licenses per each such session if one wants to do such limits. So it looks very cheap, looking into it. 

They also told me their educational discount is on top of a reseller discount they offer which is handy if one's client is an educational institution (where such scenario of usage is probable - multiple users wanting to use a limited number of powerful workstations for Graphics/Sound/etc. design & processing).  Btw, Time Boss offers free Pro license (for 3 machines) if one contributes translations, so will probably contribute one for my native language to get the chance to check it out a bit more.

**Comment by birbilis** [comment]
just for the record: seems UserLock has a minimum number of 50 licenses one needs to purchase which is quite unfortunate (hadn't notice it)

**Comment by cedrozor** [comment]
Closed (no connection monitoring/limitation planned for myrtille). Left for reference (interesting thread) into https://github.com/cedrozor/myrtille/projects/1
