### ISSUE TITLE
Responsive display in Session & Help in creating MSI 

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [cedrozor/myrtille#240]
Dear @cedrozor 

I have been able to modify the solution for several use, and, I have to tell you it's a brilliant solution.

May I request for help in two of the below aspects:

- I have been working on creating the display responsive, but, I understand the fundamental problem of windows RDP session connects to a specific resolution during session creation. But, I was trying if I can adjust the resolution post a modified browser window(potentially considering session.height and session.width) either on click of a button or listening to browser event by refreshing the session for the user.

- Second, I have strictly followed your documentation but was never able to load all projects in the MSI creation sub-project, may you please guide me how I may do the same. (note: I am able to build each individual project and Build the UI and service contents separately and manually host the solution.) I have visual studio 2019 Version 16.7.7 & .Net 4.8.04084

Thank you in advance!

**Comment by cedrozor** [comment]
Myrtille have 2 modes to adjust the remote session display to the browser size:
- Reconnect:  you noticed that, once connected and due to RDP limitations, the remote session can't be resized afterward. The "reconnect" mode disconnects the session and reconnect it with the new browser size.
- Scale: The remote session display is stretched or reduced dynamically to fit the new browser size (preserving the aspect ratio or not). This operation is done server side, so that all guests in a shared session will see exactly what the session owner see, but this could possibly be done client side too.

Both options are disabled by defaut into in `config.js` because, unfortunately, there is an issue with Windows Server 2019 which prevents to reconnect a disconnect session under normal circumstances (https://github.com/cedrozor/myrtille/issues/239). The scale feature works fine but, because it interpolates graphic coordinates, it suffers from a little loss of image sharpness and tends to blur the display.

To reply to to your 2nd question, this is because the FreeRDP projects don't have the same GUIDs across cmake runs.  You have to add them manually to the installer project, as explained here: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#build
-  winpr
-  winpr-tools
-  freerdp
-  freerdp-client
-  wfreerdp-client

**Comment by sabyasachi-basu-i** [comment]
I'll comment more on the reconnect feature soon, but I followed the document to it's nick. But, I'm unable to build this yet. I am getting the attached error. May you please look into it once.

`PS C:\Users\SabyasachiBasu\Documents\TestCode\myrtille\Myrtille.RDP\FreeRDP> cmake .
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMake Warning at cmake/ClangFormat.cmake:14 (message):
  clang-format not found in path! code format target not available.
Call Stack (most recent call first):
  CMakeLists.txt:55 (include)


-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
FREERDP_VERSION=3.0.0-dev
-- Git Revision 69c8926de
-- MSVC: using dynamically-linked runtime (/MD and /MDd).
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping disabled feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature OpenCL for codec (use OpenCL library)
--     Enable feature OpenCL using "-DWITH_OPENCL=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature LAME for codec (lame MP3 audio codec library)
--     Enable feature LAME using "-DWITH_LAME=ON"
-- Skipping optional feature FAAD2 for codec (FAAD2 AAC audio codec library)
--     Enable feature FAAD2 using "-DWITH_FAAD2=ON"
-- Skipping optional feature FAAC for codec (FAAC AAC audio codec library)
--     Enable feature FAAC using "-DWITH_FAAC=ON"
-- Skipping optional feature soxr for codec (SOX audio resample library)
--     Enable feature soxr using "-DWITH_SOXR=ON"
-- Skipping optional feature GSSAPI for auth (add kerberos support)
--     Enable feature GSSAPI using "-DWITH_GSSAPI=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- Using OpenSSL Version: 1.1.1h
using default plugins location
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find Cairo (missing: CAIRO_LIBRARIES CAIRO_INCLUDE_DIR)
CMake Warning at libfreerdp/CMakeLists.txt:102 (message):
  -DWITH_SWSCALE=OFF and -DWITH_CAIRO=OFF, compiling without image scaling
  support!


-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Adding STATIC channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding DYNAMIC channel client "video": Video optimized remoting Virtual Channel Extension
-- Adding DYNAMIC channel client "urbdrc": USB Devices Virtual Channel Extension
-- Adding DEVICE channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding STATIC channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding STATIC channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding DYNAMIC channel client "rdpgfx": Graphics Pipeline Extension
-- Adding DYNAMIC channel client "rdpei": Input Virtual Channel Extension
-- Adding STATIC channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding STATIC channel client "rdp2tcp": Tunneling TCP over RDP
-- Adding STATIC channel client "rail": Remote Programs Virtual Channel Extension
-- Adding DEVICE channel client "printer": Print Virtual Channel Extension
-- Adding DYNAMIC channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding STATIC channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding DYNAMIC channel client server "echo": Echo Virtual Channel Extension
-- Adding DEVICE channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding DYNAMIC channel client "disp": Display Update Virtual Channel Extension
-- Adding STATIC channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding DYNAMIC channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_1_INCLUDE_DIR
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client/libusb
LIBUSB_1_LIBRARY
    linked by target "urbdrc-client-libusb" in directory C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP/channels/urbdrc/client/libusb

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`

![errVS](https://user-images.githubusercontent.com/59440889/98818795-0a150500-2452-11eb-8afa-fc03822380e8.PNG)

**Comment by cedrozor** [comment]
Myrtille doesn't use usb redirect. You did checked out the Myrtille's FreeRDP fork isn't it? https://github.com/cedrozor/FreeRDP

**Comment by sabyasachi-basu-i** [comment]
I am still getting some error. Attaching the image now. I deleted everything and created make and build.
![errVS2](https://user-images.githubusercontent.com/59440889/98825151-2ddc4900-245a-11eb-87f1-8b8fc1258a08.PNG)


````
`-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding dynamic channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding device channel client "printer": Print Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client "rdp2tcp": Tunneling TCP over RDP
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "video": Video optimized remoting Virtual Channel Extension
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/SabyasachiBasu/Documents/TestCode/myrtille/Myrtille.RDP/FreeRDP
```

**Comment by cedrozor** [comment]
You need to use https://github.com/cedrozor/FreeRDP. Myrtille have custom code into FreeRDP and won't work with the FreeRDP master repository.

**Comment by sabyasachi-basu-i** [comment]
Dear @cedrozor 

Thank you for the quick guide. It helped. When I reverted back to VS 2017. It's working mostly now. But, I had to install Visual Studio Express 2017 to Build the FreeRDP code. And, then run VS 2017 in Admin mode to Load all projects. But, during the Build of Myrtille Setup, I am not getting any error. But, I do not see any file being generated under Release or Build. Adding teh screenshots below.

![warnScr](https://user-images.githubusercontent.com/59440889/99049237-a0653a00-25bc-11eb-8382-93424d371af4.PNG)
![FreeRDPBuildSuccess](https://user-images.githubusercontent.com/59440889/99049231-9e02e000-25bc-11eb-9d9d-a65ed8bd7103.PNG)
![ReleasendBuildFolder](https://user-images.githubusercontent.com/59440889/99049235-9fcca380-25bc-11eb-814b-0e2c29941ae9.PNG)

**Comment by sabyasachi-basu-i** [comment]
Dear @cedrozor ,

If you may had the chance to see the error?

**Comment by cedrozor** [comment]
I built Myrtille and FreeRDP last week with Visual Studio 2019 Community Edition and all went fine. I just had to upgrade first cmake (3.18.4), openssl 32 bit (1.1.1h) and use the Visual Studio 2017/2019 installer project extension (.vsix).

cmake will search for openssl into the `C:\OpenSSL` folder by default, so you should have it there, then build the solution files against a 32 bit architecture (`cmake -A Win32 .`).

You need to have the `winpr`, `winpr-tools`, `freerdp`, `freerdp-client` and `wfreerdp-client` projects outputs into the Myrtille installer (`Myrtille.Setup`), as explained into the documentation and ealier in this thread, then build it to have the Myrtille MSI file created into the Myrtille.Setup output directory.

The Myrtille installer will build the FreeRDP projects if they are not already, but I suggest to build FreeRDP separately, like you did, using the `ALL_BUILD` predefined target. Make sure to use the same config (debug/release) in both solutions (prefer the `AnyCPU` platform for the Myrtille solution and `Win32` for the FreeRDP one).

**Comment by sabyasachi-basu-i** [comment]
Dear @cedrozor ,

Now I know what I was missing all this time. The documentation in FreeRDP requested for a standard build ```cmake .``` but what we needed was ```cmake -A Win32 .``` and it worked.(also, I'm sure if we do 64bit on both sides, that'll work as well.)

Thank you! it's working perfectly with VS2019 itself. No additional modifications. Also, may I request for a branch in case I can modify something interesting(can't guarantee), I'll send it to you.

**Comment by cedrozor** [comment]
You are welcome, Yes, please proceed with a pull request if you want to contribute! :)
