### ISSUE TITLE
BUG: v2.9.0 --> Hidding toolbar: failed to start myrtille

### ISSUE THREAD

**Issue by lars18th** [cedrozor/myrtille#241]
Hi @cedrozor ,

After updating to v2.9.0 from the previous version, I see this error when connecting:
`failed to start myrtille: Cannot set property 'value' of null`

The root cause is this change that I have inside the `Web.config` file:
`<add key="ToolbarEnabled" value="false" />`

So, please can you check and fix it?
Thank you!

**Comment by cedrozor** [comment]
Hi @lars18th thanks for reporting this regression, I fixed it into 86c6d9ce6cc1cd360ae706bfd5e9673407b9b6e1 and it would be integrated into the next release. Meanwhile, you can report the fix into the 2 related js files (`display.js` and `mouse.js`).

**Comment by lars18th** [comment]
Hi @cedrozor ,

> Hi @lars18th thanks for reporting this regression

Thank you for fixing this problem. It's fixed with this patch replacing the two pointed files.

So, I close this issue.
Regards.
