### ISSUE TITLE
Suggestion: Config options to configure the main page

### ISSUE THREAD

**Issue by lars18th** [cedrozor/myrtille#243]
Hi @cedrozor ,

I edit the main page (login page) to hide some input boxes. I do this change editing the file `Default.aspx` and changing to somethig like this: `<div class="inputDiv" style="visibility:hidden;display:none;">`.

My suggestion is to provide inside the configuration the options to hide (or disable) some parts of the main page. For example: Type, Security, Server, Program to run, etc.

I hope you want to consider this.
Thank you!

**Comment by cedrozor** [comment]
Such customization is unusual for most users and, when done, it's better to change the elements styles into `Default.css`.  `Default.aspx` is the markup code for whetever you can't do with css.

On top of that, there is already a lot of things in the config files that most users don't even know exists, so I'd rather not add more; and it would even complicate the update process between 2 versions of Myrtille (in reference to https://github.com/cedrozor/myrtille/issues/242).

**Comment by lars18th** [comment]
Hi @cedrozor ,

Even I can understand your point of view, I'm sure a lot of users can want to _limit_ the user interface.
Please, see the attached screenshot:
![Myrtille](https://user-images.githubusercontent.com/9989964/99228886-89595e80-27ed-11eb-8b0d-97fd87d00cda.jpg)

That's my frontend webpage to access to an specific service inside a server using Myrtille. And I don't want to use Myrtille as a _proxy_ or _bastion_ to access to RDP servers. And I suspect that a lot of other users want a similar environment. In this case, a _simple_ method to configure/edit the homepage will be useful. Moreover, a method to limit to restricted default values will be interesting too.

So, please consider if you can provide a good option to support this.
Regards.

**Comment by lars18th** [comment]
Hi, I close this issue as a similar solution is proposed here: https://github.com/cedrozor/myrtille/issues/246#issuecomment-731095181
So, we can continue in this other issue.
