### ISSUE TITLE
Docker image of release 2.9

### ISSUE THREAD

**Issue by niklaslundberg** [cedrozor/myrtille#245]
Do you have any plans to release a new Docker image for release 2.9? At Docker Hub I can only find cedrozor/myrtille:2.8.0.

**Comment by cedrozor** [comment]
Indeed you are right; I wanted to have a look to the printer and audio support into the next Docker image but I didn't had much time lately. 

If you want, you can build a Docker image against the Myrtille 2.9.0 installer (msi), using the Myrtille [Dockerfile](https://github.com/cedrozor/myrtille/blob/master/Dockerfile) , following these [instructions](https://github.com/cedrozor/myrtille/blob/master/Dockerfile#L68). Then run the image as usual.

**Comment by cedrozor** [comment]
done with Myrtille 2.9.1
