### ISSUE TITLE
Restrict server ip to private address range

### ISSUE THREAD

**Issue by H4R0** [cedrozor/myrtille#246]
Myrtille allows to enter any server ip and thus connect to any server on the wan.

It is easy to abuse this by searching for public instances and use them as proxy for malicious intends like brute forcing or ddos.

There should be an option to limit connection ip server side to the private network range. https://en.wikipedia.org/wiki/Private_network

e.g 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16

This could be added to the installer and should be the default imho.

**Comment by sabyasachi-basu-i** [comment]
food for thought, you'd still need to have:
```
1. Myrtille installed in the server
2. Know the UN and PW for login (and domain name also)
3. lastly the IP address.
```

And as far as the ddos or brute force; that can anyway happen if someone has the IP and it's a public IP.

Also, with the current approach, we need to have one IIS server(hosted and certified), and use it connect to all hosted servers in the domain. (you do not need multiple urls, that way.

I personally feel the approach of connection to any server is good. 

I did think to add it as a configuration where it'll only connect to ```localhost``` @ #243 it may be added if found useful.

**Comment by cedrozor** [comment]
This is network configuration. You can restrict the machine running Myrtille to a given range of outgoing IP addresses, and problem solved. It can be done with a firewall or a proxy.

For the other way around, you can use a reverse proxy (nginx, pfsense, etc.) to filter the incoming connections (this could also be done at the IIS level, but I would suggest a reverse proxy instead).

**Comment by H4R0** [comment]
If I visit public instances I'm often greeted with a login form, my instance directly allows to connect to a server. I cant find anything in the documentation on how to setup authentication. I can login to the "host management" but there is also no option to enable authentication it only allows to setup shortcuts.

My Myrtille instance is usually also the host I connect to e.g I connect to localhost and thus I can not block connections on the gateway as the host should have rdp and ssh access, just Myrtille should not.

I ended up creating windows firewall rules to limit Myrtille.SSH.exe and wfreerdp.exe which is working fine. Still I would like to know how to enable authentication, I would prefer not to use http basic auth.

**Comment by lars18th** [comment]
Hi,

I understand the point of view from @cedrozor to not make the wheel again. And yes, a firewall can be a good solution to protect the servers where Myrtille is in use.

However, I suggest to target two security issues:

1. Describe inside the Myrtille documentation how to protect the server and the network where Myrtille is running. In a short sentence: write a document of best practices concerning the security. This is a powerful service and can be abused _without_ proper protection. So it's mandatory to configure it before enable it in a public network.
2. The current default page that enables the option to select a target server with _all_ the options enabled is a very relaxed frontpage. So, I suggest to consider this enhancement to remove/hide/pre-configure the homepage: #243 .

I hope that the project will continue improving the security aspects.
Regards.

**Comment by sabyasachi-basu-i** [comment]
Yes, @lars18th . I agree with you as well. But, quick ask, what do you think is more practical, a selection box to switch between advanced controls. or a web config settings? Or, maybe both with a settings in web config.

I was trying to achieve something similar. Since, I personally like that idea. Check the reference for more details.
#247

**Comment by lars18th** [comment]
Hi @sabyasachi-basu-i ,

Very good job in the PR #247 ! :+1: 

> Or, maybe both with a settings in web config.

That's my opinion: Provide a config option (inside the `Web.config` file) to hide and disable the "Advanced Controls". This will improve the security a bit. The toggle is fine, but the _administrator_ needs to have the _control_ over the UI. So the perfect solution is a config option (like now exists for some other options) to _hide this switch and disable all advanced options_.

So, thank you and @cedrozor for this good tool.
Regards.

**Comment by cedrozor** [comment]
> Still I would like to know how to enable authentication, I would prefer not to use http basic auth.

If you speak about RDP authentication, this is handled by FreeRDP (using RDP, NLA, etc.). Myrtille doesn't perform any authentication by itself, it just forwards the connection params to FreeRDP. This is done either using a form (POST) or from URL (GET). If you want more control over this, you can use the Connection API (REST), as described in the documentation.

> - Describe inside the Myrtille documentation how to protect the server and the network where Myrtille is running. In a short sentence: write a document of best practices concerning the security. This is a powerful service and can be abused without proper protection. So it's mandatory to configure it before enable it in a public network.

Ok, but you should know that most people already don't read the documentation (which is already quite large) :p

> - The current default page that enables the option to select a target server with all the options enabled is a very relaxed frontpage. So, I suggest to consider this enhancement to remove/hide/pre-configure the homepage: #243 .

RDP connection options (RDP, NLA, TLS, etc.) are ultimately accepted or not by the RD host (based on RDS config).

**Comment by cedrozor** [comment]
Closing. I will need to find a moment to integrate #247 with a toggle into `web.config`, as suggested by @lars18th
