### ISSUE TITLE
Is it possible to forbid drive redirection on Enhanced Session Mode?

### ISSUE THREAD

**Issue by xNitro99** [cedrozor/myrtille#249]
Good morning,

we would like to activate the Hyper-V enhanced session mode and are afraid of the security risks that this causes.

We want to forbid a possible drive redirection from a host machine, when entering the console via myrtille. 

I couldn't find any configuration in the documentation about that specific case. Is there anywhere to forbid that or does that even work?

**Comment by cedrozor** [comment]
Hi, [drive redirection](https://github.com/FreeRDP/FreeRDP/blob/master/client/common/cmdline.h#L126) is not handled by Myrtille and disabled by default into FreeRDP, so there is no security risk actually.

**Comment by xNitro99** [comment]
Hey again,

is that 100% safe, that Myrtille is not handling drive redirection?
Is there some kind of a config file i can view in Myrtille, where I can make sure, that this setting is not activated?

**Comment by xNitro99** [comment]
@cedrozor

**Comment by cedrozor** [comment]
```
is that 100% safe, that Myrtille is not handling drive redirection?
Is there some kind of a config file i can view in Myrtille, where I can make sure, that this setting is not activated?
```
Yes, here: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L236
