### ISSUE TITLE
Enhanced Session mode not activated

### ISSUE THREAD

**Issue by xNitro99** [cedrozor/myrtille#250]
Hi, 

we're trying to implement the enhanced session mode feature.
The feature does work by manually connecting to a VM with the myrtille admin interface in browser.

When using the Connection Service and the cid, it doesnt seem to work. The console is still standard mode, because I only have the en-us keyboard layout available.

This is the post request to "http://localhost:8008/MyrtilleAdmin/ConnectionService/GetConnectionId" :
{
    "User": {
        "Domain": "domain",
        "UserName": "administrator",
        "Password": "password"
    },
    "Host": {
        "IPAdress": "hostip"
    },
    "VM": {
        "Guid": "vmid"
    }
    "AllowRemoteclipboard": false,
    "AllowFileTransfer": false,
    "AllowPrintdownload": false,
    "AllowAudioPlayback": false,
    "AllowSessionSharing": false,
    "MaxActiveGuests": 0
}

Then we are inserting the CID to this link:
https://localhost/Myrtille/?cid=[cid]&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect%2&vmEnhancedMode=checked

Is there any misconfiguration or a log where i can see the cause?

**Comment by cedrozor** [comment]
Hi,

Yes, try that:

{
"User": {
"Domain": "domain",
"UserName": "administrator",
"Password": "password"
},
"Host": {
"IPAdress": "hostip"
},
"VM": {
"Guid": "vmid",
**"EnhancedMode" : true**
}
"AllowRemoteclipboard": false,
"AllowFileTransfer": false,
"AllowPrintdownload": false,
"AllowAudioPlayback": false,
"AllowSessionSharing": false,
"MaxActiveGuests": 0
}

This is JSON serialization of [this class](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services.Contracts/Models/ConnectionInfo.cs).

**Comment by xNitro99** [comment]
Hi, 
thanks for the tip. I will try that out. Now I do have another problem, regardless of whether the enhancedmode is set to true or not set at all in the post request.

When inserting the &cid= into querystring, I dont get a console screen.
Thats an example of an url, where the browser hangs:
![myrtille](https://user-images.githubusercontent.com/12881063/101756067-e9ce7980-3ad5-11eb-989b-2e84ba29ee1e.PNG)

https://localhost/Myrtille/(S(20410rgasx5o4bcwje5zrmwe))/Default.aspx?cid=6c06088e-9947-4100-ba5c-8d31e2fbf817&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect%2&width=1024&height=758

**Comment by cedrozor** [comment]
Hi, you miss a single letter (in bold) into the URL: .../Default.aspx?cid=6c06088e-9947-4100-ba5c-8d31e2fbf817&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect%2**1**&width=1024&height=758

Or you can write it as is: .../Default.aspx?cid=6c06088e-9947-4100-ba5c-8d31e2fbf817&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect!&width=1024&height=758

The exclamation mark is required and makes sense in this context! :)

**Comment by xNitro99** [comment]
Hi, 

I've tested this:
&connect=Connect%21
&connect=Connect%2
&connect=Connect%!

Regardless of what I try, It doesn't show me a console.

Funny about this, when attempting this from remote network exactly like this without exclamation mark and the missing "1":
https://[external-ip]/Myrtille/?cid=836b987a-1606-4053-aa26-137eb7a7c316&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect%2

it works without problems. 

For testing purposes, of course I'm trying to test the console from the localhost.

**Comment by cedrozor** [comment]
If the same URL works from outside and not from localhost, it must be a network config issue. Also, did you tried to access myrtille in `http` to exclude any SSL certificate or 443 port redirection issue?

Could you check the logs (`Myrtille.Web.log`, `Myrtille.Services.log` mostly, into the myrtille log folder) to see if there is anything relevant?

**Comment by xNitro99** [comment]
Same error when only including "http".
There is no log created at all.

**Comment by cedrozor** [comment]
Can you open the browser devtools (Ctrl+Shift+I with Firefox and Chrome) and see if you have errors into the network and console tabs?

**Comment by xNitro99** [comment]
Sure, this is the error I saw:

DevTools failed to load SourceMap: Could not load content for https://localhost/Myrtille/js/xterm/xterm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://localhost/Myrtille/js/xterm/addons/fit/fit.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

It says some content could not be loaded. I'm not experienced in JSON so I just tried copying these files and renaming it from ".js" to ".js.map". 
Then this error appears:

DevTools failed to load SourceMap: Could not parse content for https://localhost/Myrtille/js/xterm/addons/fit/fit.js.map: Unexpected token ( in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://localhost/Myrtille/js/xterm/xterm.js.map: Unexpected token ( in JSON at position 0

I've found out that these errors also appear when accessing https://localhost/Myrtille. A connection to a VM does work when doing it manually with the Myrtille User Interface.

**Comment by cedrozor** [comment]
Yes, I know about this; I forgot to embed the .map files when I integrated xterm.js... I should remember to add them in a future version of Myrtille, but they are not mandatory and this have nothing to do with your current issue.

Does the connection works from the login page, using the same connection details as those you pass to the connection API? some values might be invalid.

For example, I'm not sure the vmid should be surrounded by double quotes (I should re-check it). try this instead:
```
"VM": {
"Guid": XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX,
"EnhancedMode" : true
}
```

**Comment by xNitro99** [comment]
Hey there,

the case can be closed now :)

The issue was a missing "d" in the body of the post request.
The "IPAdress" had to be changed to "IPAddress".

Either way, thanks for your support!
