### ISSUE TITLE
Can't connect, invalid auth.

### ISSUE THREAD

**Issue by wolfy01** [cedrozor/myrtille#251]
I put in my auth credentials like I would with normal RDP, except my User is `<name>@gmail.com`, which doesn't seem to work with myrtille?

**Comment by wolfy01** [comment]
Even creating a user using Computer Management doesn't work

**Comment by sandrickn** [comment]
Did you assign the user to "Remote Desktop Users" or enabled RDS?

**Comment by wolfy01** [comment]
@sandrickn Yes. I'm using windows 10 pro RDP if that matters

**Comment by cedrozor** [comment]
Myrtille expects a user that exists on the target OS (or domain, if using Active Directory). `<name>@gmail.com` could be confused with an [UPN](https://docs.microsoft.com/en-us/windows/win32/secauthn/user-name-formats) which relies on a similar syntax but is different from an email. An alternative to UPN is down-level logon name (using netbios), with the `DOMAIN\user` syntax.

To avoid any confusion, try enter `gmail.com` into the "domain" field and `<name>` into the "user" field of the Myrtille login screen.

**Comment by wolfy01** [comment]
@cedrozor Something weird happens. If I proxy the ports but do not allow websockets, it brings me to the login page, only the user is put in, without `@gmail.com`. It is very slow to type the rest of the user and pass (About 1000ms) I'm guessing this is because it is not using websockets. Allowing websockets through forwarding causes the invalid auth error because it isn't putting in the right username.

**Comment by cedrozor** [comment]
Websocket doesn't have anything to do with the RDP login process, it's just a way for the browser to communicate with the Myrtille gateway. `TLS` is a secure transport layer between the RDP client and the target server and have normally nothing to do with the windows logon screeen; the latter should only be displayed when using the `RDP` security mode with empty username and password and given NLA is not enforced on the target.

Remote audio actually requires the myrtille gateway to have a physical or virtual sound card. This is something I will try to workaround into FreeRDP in a future version of Myrtille.

**Comment by cedrozor** [comment]
I hope I replied to your question; please re-open if needed.
