### ISSUE TITLE
Connect to one Private IP VM using a another Private IP VM

### ISSUE THREAD

**Issue by umeshpatil12** [cedrozor/myrtille#254]
Want to connect to one Private IP VM using a second Private IP VM.
I have installed myrtille on one VM, and I use the first machine as a mediator to connect the second VM from the local computer chrome. In Postman I have passed the following parameters:
Post: http://*.*.*.*:8008/MyrtilleAdmin/ConnectionService/GetConnectionId
Body:{"User":{"Domain":"","UserName":"Administrator","Password":"*.*.*.*"},"Host":{"HostType":0,"SecurityProtocol":0,"IPAddress":"*.*.*.*"},"VM":null,"AllowRemoteClipboard":true,"AllowFileTransfer":false,"AllowPrintDownload":true,"AllowAudioPlayback":true,"MaxActiveGuests":3,"StartProgram":"","GatewayUrl":"http://*.*.*.*/Myrtille/"}
![Postman Data](https://user-images.githubusercontent.com/53421409/101983921-e852ac00-3ca3-11eb-9070-30e7b860bb5d.png)

This gives me no response, but when I connect using public Ip for both machines it returns **cid** as a response.

**Comment by cedrozor** [comment]
If it works from outside (public ip), this is probably a network config issue. Did you opened the port 8008 (Myrtille admin services) on the Myrtille VM? what is the http error code returned by postman into the http response?

**Comment by umeshpatil12** [comment]
Yes, I have opened port 8008 in both VM. Post Man Gives below error message:
![image](https://user-images.githubusercontent.com/53421409/102045522-4f38a800-3dff-11eb-9358-d73a0299e734.png)

**Comment by cedrozor** [comment]
On the myrtille vm, you need only the ports 80 (http), 443 (https) and 8008 (myrtille admin) and the port 3389 (rdp) on the target vm.

From which machine do you try to call myrtille? can you ping the myrtille's ip from there? maybe try to open the port 8008 as outbound rule from this machine. You can also temporarily disable firewalls just per see if it works. It's definitely just a network config issue.
