### ISSUE TITLE
can I start a certain application in Windows through a URL address? 

### ISSUE THREAD

**Issue by yoyomule** [cedrozor/myrtille#256]
Hello, can I start a certain application in Windows through a URL address? Instead of pushing the entire desktop into the browser, just push one of the applications into the browser. Thank you.

**Comment by cedrozor** [comment]
Yes, as detailed in the [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url).
