### ISSUE TITLE
Failed to call service start process

### ISSUE THREAD

**Issue by wangguotao** [cedrozor/myrtille#257]
debug with vs2019, catch the exception "System. ServiceModel. Channels. ServiceChannel cannot be used for communication, because it is in a state of "error"". how to solve it. thanks

**Comment by cedrozor** [comment]
Have a look  into the log folder for myrtille web and services projects. It look like a WCF issue, did you enabled http activation into the .NET role features? You can run `Myrtille.Web.Install.ps1` which will enable all the Myrtille pre-requisites (IIS, websocket protocol, .NET, etc.).
