### ISSUE TITLE
GetProcessIdentity Timeout

### ISSUE THREAD

**Issue by LFXiaoFei** [cedrozor/myrtille#258]
Using vs2019 to debug RDP to connect to the server and throw an exception.

RemoteSessionPipes=>CreatePipes=>new PipeAccessRule=>GetProcessIdentity Timeout.

VS2019 running as Administrator. Help me.

Please help me.Thank you!

**Comment by cedrozor** [comment]
Are the Myrtille services running? [GetProcessIdentity](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services.Contracts/IRemoteSessionProcess.cs#L58) is a method of the `RemoteSessionProcess` service

**Comment by LFXiaoFei** [comment]
Yes, Myrtille services is running. Debugging by VS2019.

**Comment by cedrozor** [comment]
This looks like a WCF issue, related to https://github.com/cedrozor/myrtille/issues/257

> Into the roles and features management, ensure you have enabled HTTP Activation under ".NET Framework 4.5+ Features" : "WCF Services" (required by the Myrtille services and REST API).

**Comment by cedrozor** [comment]
Any news?
