### ISSUE TITLE
IIS reverse proxy setup with Myrtille

### ISSUE THREAD

**Issue by mrdibb40** [cedrozor/myrtille#260]
Sorry if this isn't the right place to post this question but i wasn't sure where else to post where enough people who have used Myrtille would see it.  

We have an IIS 10 reverse proxy setup on a 2016 server and it works well for a mix of windows and linux sites .  We were hoping to add a Myrtille deployment to it for our external users.  The inbound rule works properly, the user gets redirected to the Myrtille server and can log in.  The problem we are having is with the outbound rules, when they are enabled, no matter how we have tweaked the proxy rules we keep getting "ERR_TOO_MANY_REDIRECTS".  When the Myrtille URL is rewritten and the server adds the secure session ID, it does a 302 redirect to its full URL with its local server address, the proxy server then rewrites the URL again to change the http-host back and this causes a loop until the browser shuts it down with the error.

We have tried several strategies to fix this by overwriting or suppressing the 302 rule but nothing has worked.  This is our basic rule we use for the rest of the proxy sites and it works with everything from dotnetnuke to nextcloud. 

Any advice from someone who has successfully gotten Myrtille to worth with an IIS reverse proxy would be greatly appreciated.

	<rules>
		<rule name="Reverse Proxy7 RDPGateway In" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions>
                        <add input="{CACHE_URL}" pattern="^(https?)://" />  				
			<add input="{HTTP_HOST}" pattern="proxy7(.*)" />
			<add input="{PATH_INFO}" pattern="^/logon.aspx" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="http://rdpgateway.mygatewayserver.local/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_X_ORIGINAL_ACCEPT_ENCODING" value="{HTTP_ACCEPT_ENCODING}" />
                        <set name="HTTP_ACCEPT_ENCODING" value="" />  
                    </serverVariables>   
                </rule> 
 	</rules>
 
 
 

	<outboundRules>
                <rule name="Reverse Proxy7 RDPGateway Out" preCondition="ResponseIsAnyContent" patternSyntax="ECMAScript" stopProcessing="false">
                    <match filterByTags="A, Area, Base, Form, Head, IFrame, Img, Input, Link, Script" pattern="(.*)rdpgateway.mygatewayserver.local/(.*)" />
                    <action type="Rewrite" value="https://proxy7myproxyserver.net/{R:2}" />
                </rule>
 
                <rule name="RestoreAcceptEncoding" preCondition="NeedsRestoringAcceptEncoding" patternSyntax="ECMAScript" stopProcessing="false">
                    <match serverVariable="HTTP_ACCEPT_ENCODING" pattern="^(.*)" />
                    <action type="Rewrite" value="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" />
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsAnyContent" logicalGrouping="MatchAny">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
						<add input="{RESPONSE_CONTENT_TYPE}" pattern="text/css" />
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="text/javascript" />
                    </preCondition>
                    <preCondition name="NeedsRestoringAcceptEncoding">
                        <add input="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" pattern=".+" />
                    </preCondition>
                </preConditions>
  	</outboundRules>

**Comment by cedrozor** [comment]
Hello, yes this is the right place to post because someone else may have encountered such a problem and therefore can advise you on it.

Myrtille does indeed make a server redirect (http 302) in order to change the page method from http post to http get, acquire a new http session id (to prevent session fixation attacks) and remove all querystring parameters from url, if any.

From my understanding, this goes into infinite loop because your proxy (IIS URL rewrite?) is also rewriting the url. Do you really need outbound rules with Myrtille? all css and js paths are relative and the http 302 redirect does re-enter your inbound rule, so you could try to remove or disable them with Myrtille (web.config).

**Comment by mrdibb40** [comment]
Cedrozor, 

thanks for replying!

> From my understanding, this goes into infinite loop because your proxy (IIS URL rewrite?) is also rewriting the url. Do you really need outbound rules with Myrtille? all css and js paths are relative and the http 302 redirect does re-enter your inbound rule, so you could try to remove or disable them with Myrtille (web.config).

yes you are correct the the reverse proxy is IIS URL Rewrite.  We need the outbound rules because otherwise the url of the Myrtille site gets rewritten to the internal host name of that server, or we get the to many redirects error, depending on whether 'Reverse rewrite host in response header' is turned off or on in the ARR settings. 

I did find this section in the Myrtille web.config:

`<!-- CAUTION! cookieless="UseUri" allows multiple connections/tabs but, as the http session id is passed into the url, it also implies a risk of session spoofing to mitigate that risk, an authentication cookie is stored into the browser initiating the http session; any other client accessing the http session without it will be rejected  please note that, even if the http session is cookieless, this mechanism requires cookies to be enabled client side the "cookieless=" attribute is really confusing because it's in fact the method used by the browser to send the http session id... and using a cookie is the standard way to do it if using myrtille within iframe(s) on a same page, cookieless="UseUri" must be used -->`


`<!-- <sessionState mode="InProc" cookieless="UseUri" timeout="60" /> -->`

`<sessionState mode="InProc" cookieless="UseCookies" cookieName="AuthSecToken" timeout="60"/>`


The cookieless="UseUri" version was enabled by default and the cookieless="UseCookies" version was disabled.  When i reversed this and used the cookie version i no longer get the 302 problem, presumably because the the session is stored in the cookie and not put in the Url.  So my question is, how much less secure is running the site this way if we are also keeping it behind the reverse proxy?

**Comment by cedrozor** [comment]
This is equally secure. The downside is, you won't be able to have multiple connections/tabs this way; each tab will display the same remote session because it will use the same http session stored in the domain cookie.
