### ISSUE TITLE
test dev code

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [cedrozor/myrtille#263]
Dear @cedrozor ,

Need one help!

I want to test the code during development from a Windows 10 system.

Currently I am writing my code, building the code and installer; then installing and testing in a a cloud server, Win Server 2019.

Is there any way I can do this with local service and local IIS all running in sync from my Windows 10 Laptop.

Regards,
Sabyasachi Basu

**Comment by cedrozor** [comment]
Hi @sabyasachi-basu-i,

Of course yes! it's always better to dev and test locally. You can enable IIS, .NET and all Myrtille pre-requisites on your Win10 laptop (see documentation) or run the following powershell commands: ([Myrtille.Web.Install.ps1](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1))

```
# enable IIS, WebSocket protocol, management console and tools
Enable-WindowsOptionalFeature -NoRestart -Online -FeatureName IIS-WebServerRole, IIS-WebServer, IIS-CommonHttpFeatures, IIS-DefaultDocument, IIS-DirectoryBrowsing, IIS-HttpErrors, IIS-StaticContent, IIS-HttpRedirect, IIS-HealthAndDiagnostics, IIS-HttpLogging, IIS-Performance, IIS-HttpCompressionStatic, IIS-Security, IIS-RequestFiltering, IIS-ApplicationDevelopment, IIS-ISAPIExtensions, IIS-ISAPIFilter, IIS-WebSockets, IIS-ManagementConsole, IIS-ManagementScriptingTools
Write-Output "Enabled IIS, WebSocket protocol, management console and tools`r`n"

# enable .NET extensibility
Enable-WindowsOptionalFeature -NoRestart -Online -FeatureName IIS-NetFxExtensibility45, IIS-ASPNET45 -All
Write-Output "Enabled .NET extensibility`r`n"

# enable WCF/HTTP activation
Enable-WindowsOptionalFeature -NoRestart -Online -FeatureName WAS-WindowsActivationService, WAS-ProcessModel, WAS-ConfigurationAPI, WCF-HTTP-Activation45
Write-Output "Enabled WCF/HTTP activation`r`n"
```

Then you need Visual Studio on your laptop (enable C# and also C++ if you want to build the FreeRDP fork) and voila :)

You can use your Server 2019 cloud server as target host.

**Comment by sabyasachi-basu-i** [comment]
@cedrozor , But, if I change my service and FreeRDP fork code(winpr and additional dependencies) I still need to separately build and deploy in the Win Server. right ? to reflect when I an connecting to the target host.

**Comment by cedrozor** [comment]
No, you don't have to deploy FreeRDP on the Server 2019. It will run as RDP client on your Win10 laptop, along with Myrtille. You need to clone it into the Myrtille.RDP\FreeRDP folder and build it from there, after running cmake. I had this described in the documentation and you can find many closed issues about it.

**Comment by sabyasachi-basu-i** [comment]
Got it. thank you!!
