### ISSUE TITLE
Start RDP session from API

### ISSUE THREAD

**Issue by ChrML** [cedrozor/myrtille#264]
This is a question or a feature-request, not sure yet.

I'm implementing an external admin management application which will handle the hosts to use, and the credentials. The external system will create the session once a user wants to begin an RDP session, and give the user the URL to enter the session directly (skip the Myrtille login dialog).

Flow as follows:

1. External applications calls API in Myrtille to create a new session ID:
    POST https://my-server/myrtille/NewSession?host=10.0.0.10&domain=my-domain&user=my-user&password=my-password
2. The API returns the URL to use, similar to the "Create Host Session"- dialog in the admin interface.
3. External application redirects the user to that session: https://my-server/myrtille/(S(blablabla123))/

 If the feature is missing I can make a PR with this feature if someone can point me in the right direction. :)

**Comment by ChrML** [comment]
@cedrozor If possible we'd like to order this feature from you. We can pay for the time you need.

**Comment by cedrozor** [comment]
Hi, there is already a [REST API in Myrtille](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#rest-apis) to do it.

Basically, you provision a connection by making a POST request to
`/server:8008/myrtilleAdmin/ConnectionService`, providing connection details as JSON structure.

It returns a connection ID, usable once, you can use to establish the connection, with the following syntax:
`https://server/myrtille?cid=connectionID&__EVENTTARGET=&__EVENTARGUMENT=&connect=Connect%21`

See an example [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Web/Default.aspx.cs#L142) to tap in these APIs programmatically or the `{ REST:API }` tutorial video on the [Myrtille website](https://www.myrtille.io) for a simple browser access.

Thanks for the payment proposal, you can [donate](https://www.paypal.me/costecedric) if you want ;)

**Comment by ChrML** [comment]
Thanks, I will try this! :)
