### ISSUE TITLE
FreeRDP upgrade to 2.2.0

### ISSUE THREAD

**Issue by sarathy365** [cedrozor/myrtille#266]
FreeRDP needs to be upgraded.

I can see, FreeRDP(wfreerdp.exe) used by Myrtille contains commits only upto Jan23, 2020. Even that commit changeset is not a tagged one.
![image](https://user-images.githubusercontent.com/20512947/105041709-551e4a80-5a89-11eb-9ed1-4d0111cf4c8d.png)

**Comment by cedrozor** [comment]
Yes, indeed, I will update it into a next version.
