### ISSUE TITLE
Failed to connect to RDConnectionBroker

### ISSUE THREAD

**Issue by Ni101** [cedrozor/myrtille#279]
Hi,
I have a RDS setup, with RDConnectionBroker and RDWebAccess on one VM and another VM as the RDSessionHost.
I want to use myrtille to access that rds setup

on the same myrille machine, the connection works using the RDWeb rdp file
but then when i try using myrtille, it connects successfully to the RDSessionHost directly but fails when i try to connect to RDConnectionBroker
in the Services.log file, myrtille exists with error code 65545, also security is auto
I did enable the freerdp log file and it exists with error ERRINFO_SERVER_INSUFFICIENT_PRIVILEDGES

I did try to disable NLA.
Any suggestions I should try?

**Comment by cedrozor** [comment]
A dumb question, is the RDWeb rdp file targeting the RD connection broker? you can check this by opening the file and search the target address. You may also have a "password 51" entry (hashed password), you should use the plain text password to connect from the Myrtille login screen or the same hash to connect  from url.

**Comment by Ni101** [comment]
The rdp file is indeed targeting the RDConnectionBroker.
I dont know if it is using a hashed password, how do i check it?
i type the username and password in the Myrtille login screen, if that helps.

**Comment by cedrozor** [comment]
See this thread: https://www.reddit.com/r/sysadmin/comments/azflsc/create_rdp_file_with_encrypted_password_in_it/
