### ISSUE TITLE
Init error attachEvent

### ISSUE THREAD

**Issue by MTBEnthusiast** [cedrozor/myrtille#28]
Hi,

on some machines i received the error: Init error attachEvent.
The object doesn't support the "attachEvent" method.
In the MSN the attachEvent will not supported on IE11 ans ist replaced since IE9 with addEventListener.

What is the solution for 'old' IE (<9) and 'new' IE (>9)?

Regards
Rolf

**Comment by cedrozor** [comment]
Hi Rolf,

Indeed, attachEvent is no longer supported in IE 11 (https://msdn.microsoft.com/en-us/library/ms536343%28v=vs.85%29.aspx). It goes through tests, my IE11 was probably set in compatibility mode (IE9 engine).

I will update it as described here : http://stackoverflow.com/a/20180298

Thanks for the report :)

Cedric

**Comment by sumbul-811** [comment]
I'm a beginner in this field. I know core java and also made a small desktop software.Can you guys please give me some code to get resolved or can guide me how I start working through this.
