### ISSUE TITLE
Detected as Trojan:Script/Woreflint.A!cl

### ISSUE THREAD

**Issue by FrBillyD** [cedrozor/myrtille#280]
Hello,
Like the #233 issue, the installation executable is now detected as malicious with code "Trojan:Script/Woreflint.A!cl" under Windows Defender.
Thank you in advance for details.

![image](https://user-images.githubusercontent.com/4552702/109164296-8cfc6a00-777a-11eb-8ab6-6d0788854aea.png)

https://www.virustotal.com/gui/file-analysis/MTlmZmI4OTQ5MDZiNmIxN2IxZmEwMzg1YTg0MTA4Y2M6MTYxNDI2MjI3OA==/detection

**Comment by cedrozor** [comment]
Thanks, it's probably again a false positive... I'll report it again to https://www.microsoft.com/en-us/wdsi/filesubmission, but it becomes annoying :/

Generally, when you have 10 AV reporting 10 different threats, it's often a false positive.

I tried to build wfreerdp against 3 different machines, with 1 a fresh Win 2019 Server and I had detection straight after the build process. I didn't knew viruses could link an executable without it being executed first...

I need help on this one. I invite people to build wfreerdp (the FreeRDP's Myrtille fork here: https://github.com/cedrozor/FreeRDP) against the source code and tell me if they have a detection after that. The procedure is described here: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#build

I will build the FreeRDP master code (https://github.com/FreeRDP/FreeRDP) and see if it's the same. But I can guarantee the Myrtille code into FreeRDP is perfectly clean. You can check it if you want, everything is tagged under the `#pragma region Myrtille` and `#pragma endregion tags`.

**Comment by cedrozor** [comment]
Fixed into [Myrtille 2.9.2](https://github.com/cedrozor/myrtille/releases/tag/v2.9.2)

FreeRDP is now built as a dll instead of an exe; this removed the false positive detection (down to 2 AV, I will report this to editors). https://www.virustotal.com/gui/file/f894dffe58325dd1dc66776524e127ff6f8c1d71ae13d73fc9492e86be034b97/detection
