### ISSUE TITLE
Auth proxy

### ISSUE THREAD

**Issue by sash2222** [cedrozor/myrtille#281]
Hi guys. Tell me, is such an authorization scenario possible for you? https://guacamole.apache.org/doc/gug/header-auth.html.  I want to move the authorization level to Auth proxy (https://www.pomerium.io/) and send a header with a username or email to Myrtille.
Myrtille in this case should parse the header and automatically authorize a user with this name or email.

**Comment by cedrozor** [comment]
Hi, yes this is possible, but you would also need to pass the user credentials in addition to the user name or (better) pass an authentication token.

You can also connect from URL, with a proxy adding the connection details to the URL (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url)
