### ISSUE TITLE
Login screen ends in error

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [cedrozor/myrtille#283]
Sometimes after use for a while the login screen ends up in a screen with only UN and PW and nothing works. Even the admin login fails. MSI repair does not help in any resolution. Only way to mitigate is when i uninstall and reinstall. Adding screenshot for reference.

![err_myrtille](https://user-images.githubusercontent.com/59440889/110816307-3da55600-82b1-11eb-8838-812fec962d52.png)

**Comment by cedrozor** [comment]
Did you enabled the enterprise mode (this screen is normally displayed only in this mode)?

When this happens, can you try to recycle the myrtille application pool ("MyrtilleAppPool"), or just kill its process (w3wp.exe process) and refresh the page.

**Comment by sabyasachi-basu-i** [comment]
I did the same. It didn't help. I checked all logs. Could not find anything that reflects this problem. I'll try with my local code again. But, the reinstall worked again.(it's working now.)

**Comment by cedrozor** [comment]
Did you identified the problem?

**Comment by sabyasachi-basu-i** [comment]
no. It was one of our prod server, so, resolution was more important than identification. I'm trying to recreate the issue in other servers. But so far no luck. :( It is very random, but happened with me few times(maybe 5-6) and every time it was out of the blue. I'll inform you more in case I can find anything. Also, about the video rendering, i've got very little time last few months. I'll surely work whenever I get time. Sorry! I couldn't do anything.
