### ISSUE TITLE
Myrtille FreeRDP build error

### ISSUE THREAD

**Issue by goldenskygiang** [cedrozor/myrtille#285]
Hi there,
I followed the build instruction of FreeRDP on this [link](https://github.com/FreeRDP/FreeRDP/wiki/Build-on-Windows-Visual-C---2012-(32-and-64-bit)). I edited sysinfo.c file to make an x64 VS project.
My machine runs on Windows 10 19042.867 x64, Visual Studio 2019 16.9.1
Then I encountered this error:

30>   Creating library D:/Startdown/myrtille/Myrtille.RDP/FreeRDP/Release/wfreerdp-client.lib and object D:/Startdown/myrtille/Myrtille.RDP/FreeRDP/Release/wfreerdp-client.exp
30>wf_myrtille.obj : error LNK2019: unresolved external symbol WebPConfigInitInternal referenced in function wf_myrtille_start
30>wf_myrtille.obj : error LNK2019: unresolved external symbol WebPPictureInitInternal referenced in function "void __cdecl webPEncoder(struct wf_context *,class Gdiplus::Bitmap *,int,struct IStream *,float,bool)" (?webPEncoder@@YAXPEAUwf_context@@PEAVBitmap@Gdiplus@@HPEAUIStream@@M_N@Z)
30>wf_myrtille.obj : error LNK2019: unresolved external symbol WebPPictureFree referenced in function "void __cdecl webPEncoder(struct wf_context *,class Gdiplus::Bitmap *,int,struct IStream *,float,bool)" (?webPEncoder@@YAXPEAUwf_context@@PEAVBitmap@Gdiplus@@HPEAUIStream@@M_N@Z)
30>wf_myrtille.obj : error LNK2019: unresolved external symbol WebPPictureImportBGRA referenced in function "void __cdecl webPEncoder(struct wf_context *,class Gdiplus::Bitmap *,int,struct IStream *,float,bool)" (?webPEncoder@@YAXPEAUwf_context@@PEAVBitmap@Gdiplus@@HPEAUIStream@@M_N@Z)
30>wf_myrtille.obj : error LNK2019: unresolved external symbol WebPEncode referenced in function "void __cdecl webPEncoder(struct wf_context *,class Gdiplus::Bitmap *,int,struct IStream *,float,bool)" (?webPEncoder@@YAXPEAUwf_context@@PEAVBitmap@Gdiplus@@HPEAUIStream@@M_N@Z)
30>..\..\webp\lib\libwebp.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
30>D:\Startdown\myrtille\Myrtille.RDP\FreeRDP\Release\wfreerdp-client.dll : fatal error LNK1120: 5 unresolved externals
30>Done building project "wfreerdp-client.vcxproj" -- FAILED.

Could anyone help me with this?

**Comment by cedrozor** [comment]
Hi, it's probably the webP library which is 32 bits only. I also had troubles with openssl in 64 bits back in time, that's why I preferred a 32 bits build. Anyway, the memory usage of FreeRDP is way below 4GB, so I'm not sure there is any benefit having a 64 bits build.

**Comment by yesihaveidea** [comment]
> Could anyone help me with this?

Simply replace /webp/* files with x64 ones from https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.5.1-windows-x64.zip
