### ISSUE TITLE
Question: Windows Authentication

### ISSUE THREAD

**Issue by flamingwitch** [cedrozor/myrtille#288]
Hi,

First, thank you very much for your great project.

I have set up myrtille to be used as a remote app replacement. Originally a user would be served up an RDP using the remote app active X plugin, their windows credentials were passed along thanks to GPOs.

With myrtille I build a url with a connection ID by providing connection details to the connection service, this uses a single windows account for all users so that I can provide the windows username/password.  I was wondering if there was already some way to pass along user's windows credentials instead? Or is this perhaps something I'd have to implement myself?

Thanks!

**Comment by cedrozor** [comment]
Hi, you can pass the user credentials, with a plain text or hashed password, into the url (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url) or, as you do, by using the Myrtille connection API (REST) after provisioning the connection details, but there is no Windows authentication into Myrtille (it needed IE back int the past and IIS configured to accept Windows authentication, using NTLM or Kerberos if I remember well).

There are still ways to accept Windows authentication into modern browsers, but you will have to do some additional development into Myrtille to handle it: https://specopssoft.com/blog/configuring-chrome-and-firefox-for-windows-integrated-authentication/
