### ISSUE TITLE
RTC startup problem after login screen ( after 2.5.5)

### ISSUE THREAD

**Issue by sinanyvz** [cedrozor/myrtille#290]
Hi Cedric,
I am using version 2.5.5 without any problems. I am grateful 
I checked the updates and wanted to install version 2.9.2 but. somehow i couldn't get it to work. 
I am using Windows Server 2019 Datacenter. windows defender and firewall have been turned off. It doesn't even have a virus program.

Login screen comes up, I enter the information. After that, the blank screen remains. There is a menu on the top.
I have tried many things but have not been successful. And I decided to ask you for help :)

I'm sending the log files to help.
[Myrtille.Services.log](https://github.com/cedrozor/myrtille/files/6469054/Myrtille.Services.log)
[Myrtille.Web.log](https://github.com/cedrozor/myrtille/files/6469055/Myrtille.Web.log)

Thank you so much for your effort and support...

**Comment by cedrozor** [comment]
Hi, from the logs it looks like the Myrtille frontend and backend can't communicate, but there is nothing changed on that side since 2.5.5. The Myrtille services are started, listening on local port 8080 (tcp), but the Myrtille web application can't communicate with them. Do you have something also using the port 8080 besides Myrtille? You can change the default port into Myrtille.Services and Myrtille.Web config files; restart Myrtille.Services (Windows service) then.

**Comment by sinanyvz** [comment]
Hi Cedric,
Thank you for the answer.
As I said before, the 2.5.5 installation works without any intervention.
I uninstall version 2.5.5 and install version 2.9.2 on the same machine, but it doesn't work.
Like you said I changed port 8080 to 9090. To avoid mistakes, I uninstalled and reinstalled the program (9090) but the result still didn't work. I am posting the attached log folder as it may help you.

[log.zip](https://github.com/cedrozor/myrtille/files/6479620/log.zip)

**Comment by cedrozor** [comment]
Could you check if the windows service "`Myrtille.Services`" is started? the log file `Myrtille.Services.log` doesn't show any entry, unlike the previous logs you posted, and this is not normal. This service must be set to "automatic" start type, started and running under the LocalSystem account.

You still have the same issue, the Myrtille frontend (Myrtille.Web) can't communicate with the backend (Myrtille.Services). This is normally done by the installer, but could you check if you enabled WCF HTTP activation? (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#installation):

> Into the roles and features management, ensure you have enabled HTTP Activation under ".NET Framework 4.5+ Features" > "WCF Services" (required by the Myrtille services and REST API).

**Comment by sinanyvz** [comment]
yes, both services are working correctly. 
I read the installation documentation many times before notifying you a problem.
(https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#installation): 
Windows Server 2019 Datacenter,IIS 10 and .NET Framework 4.7 is installed on my server 
windows defender disabled. There is no virus program. no firewall and no proxy 
I'm doing the tests on the local network. 
I don't know if it makes the difference, but the operating system is Turkish and the regional options are Turkey.

**Comment by cedrozor** [comment]
From the myrtille machine, could you try to access the urls of the myrtille services? for example, using a browser: `http://localhost:8080/Myrtille/MFAAuthentication`

What is the output you have?

**Comment by sinanyvz** [comment]
I've tried.
HTTP Hatası 404.0 - Not Found

**Comment by sinanyvz** [comment]
I've tried.

MFAAuthentication Hizmeti

Bir hizmet oluşturdunuz.

Bu hizmeti sınamak için bir istemci oluşturmanız ve hizmeti çağırmak için onu kullanmanız gerekir. Komut satırında aşağıdaki sözdizimiyle svcutil.exe aracını kullanarak bunu yapabilirsiniz:


svcutil.exe http://localhost:9090/Myrtille/MFAAuthentication?wsdl
Hizmet açıklamasına tek bir dosya olarak da erişebilirsiniz:

http://localhost:9090/Myrtille/MFAAuthentication?singleWsdl
Bu, istemci sınıfını içeren bir yapılandırma dosyası ve kod dosyası oluşturur. İki dosyayı istemci uygulamanıza ekleyin ve Service işlevini çağırmak için oluşturulan istemci sınıfını kullanın. Örneğin:

C#

class Test
{
    static void Main()
    {
        MFAAuthenticationClient client = new MFAAuthenticationClient();

        // Hizmetteki işlemleri çağırmak için 'client' değişkenini kullanın.

        // Her zaman istemciyi kapatın.
        client.Close();
    }
}

Visual Basic

Class Test
    Shared Sub Main()
        Dim client As MFAAuthenticationClient = New MFAAuthenticationClient()
        ' Hizmetteki işlemleri çağırmak için 'client' değişkenini kullanın.

        ' Her zaman istemciyi kapatın.
        client.Close()
    End Sub
End Class

**Comment by cedrozor** [comment]
Myrtille services are running (`Myrtille.Services.log` is now ok), but you have the following into `Myrtille.Web.log`:

> 2021-05-14 18: 03: 17,482 [9] ERROR System.Diagnostics redirection [(null)] - Failed to get enterprise adapter mode (System.ServiceModel.EndpointNotFoundException: Listen at http://localhost:9090/Myrtille/EnterpriseService This is usually due to an incorrect address or SOAP action. For details, see InnerException if available. ---> System.Net.WebException: Cannot connect to remote server ---> System.Net.Sockets. SocketException: Connection failed because target machine actively refused 127.0.0.1:9090

This means you have something preventing communication from the Myrtille web application (hosted by IIS) and the Myrtille services (self-hosted WCF). Do you have a specific IIS configuration on the machine? did you changed the application pool used by Myrtille?

and you have this later:

> 2021-05-14 23: 34: 51,133 [10] ERROR System.Diagnostics redirection [(null)] - Failed to get enterprise adapter mode (System.ServiceModel.EndpointNotFoundException: Listen at http://localhost:9090/Myrtille/EnterpriseService There was no endpoint to accept the message. This is usually due to an incorrect address or SOAP action. See InnerException for details if available. ---> System.Net.WebException: The remote server returned an error: (404) Not found.

It's because Myrtille.Services (Windows service) was stopped at this time.

Is `http://localhost:9090/Myrtille/EnterpriseService` working from a browser? (like it was working with `http://localhost:9090/Myrtille/MFAAuthentication`).

**Comment by sinanyvz** [comment]
I am sending all settings visually so that I can help you and avoid any misunderstanding. 
I did not make any settings in IIS in 2.5.5. 
deneme yanılma yaparken bazı ayarları değiştirmiş olabilirim.

[MySettings.docx](https://github.com/cedrozor/myrtille/files/6481273/MySettings.docx)

**Comment by cedrozor** [comment]
Yes, please try to install Myrtille on a fresh machine. It's probably a system/config issue after you uninstalled 2.5.5 and installed 2.9.2. If you didn't uninstalled 2.5.5 before installing 2.9.2, the installer tried to upgrade Myrtille but something might have gone wrong (the upgrade support was introduced into 2.8.0).

**Comment by cedrozor** [comment]
Did it worked with a fresh install? please keep us updated

**Comment by sinanyvz** [comment]
Hi Cedric,
Unfortunately I couldn't try.
I will try and get back to you as soon as possible.
