### ISSUE TITLE
Security/Bug: User accessing same shared session URL too many times opens the VM session

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [cedrozor/myrtille#292]
If we create a shared session, and while keeping the primary session active, use the same url too many times(10-15 appox) the session URL starts working.

**Comment by sabyasachi-basu-i** [comment]
More Info: https://***/Myrtille/?gid=14a275f0-da68-49d3-11a2-ee308a078de0

Consider this your shared session URL.

Open once and it works - Correct.

Open more than once (it should not work), but try repeatedly, it'll start working.

**Comment by cedrozor** [comment]
Hi, is the guest session still active by the time the shared url starts working again?

**Comment by sabyasachi-basu-i** [comment]
This is excellent. I guess I also can modify the usage replicating enterprise mode. Or, maybe remove it permanently from the collection post one use. Thank you!
