### ISSUE TITLE
HTTP Error 500.24 - Internal Server Error

### ISSUE THREAD

**Issue by seanvree** [cedrozor/myrtille#30]
OS: Windows 10E
Webserver: IIS7

After the new version, i'm getting this error:

========================================
HTTP Error 500.24 - Internal Server Error
An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode.

Most likely causes:
system.web/identity@impersonate is set to true.
Things you can try:
If the application supports it, disable client impersonation.
If you are certain that it is OK to ignore this error, it can be disabled by setting system.webServer/validation@validateIntegratedModeConfiguration to false.
Move this application to an application pool using Classic .NET mode - for example, %SystemRoot%\system32\inetsrv\appcmd set app "Default Web Site/" /applicationPool:"Classic .NET AppPool"
(You can set "Classic .NET AppPool" to the name of another application pool running in Classic managed pipeline mode)
========================================

I've tried setting that attribute in IIS, but then I get an invalid setting remark. 

Was running fine on the old version. 

Ideas?

**Comment by cedrozor** [comment]
Hi, you should check the authentication configuration into IIS manager: http://stackoverflow.com/questions/14445252/http-error-500-24-internal-server-error-an-asp-net-setting-has-been-detected-t

Only "Anonymous Authentication" should be enabled.

**Comment by seanvree** [comment]
@cedrozor ,  when I do that, I get this:

Server Error in '/Myrtille' Application.

The specified network password is not correct.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Cryptography.CryptographicException: The specified network password is not correct.


Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[CryptographicException: The specified network password is not correct.
]
   System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) +41
   System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx) +0
   System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags) +272
   System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password) +137
   Myrtille.Web.Global.Application_Start(Object sender, EventArgs e) +1480

[HttpException (0x80004005): The specified network password is not correct.
]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +540
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +186
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): The specified network password is not correct.
]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +539
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +125
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +731

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1586.0

**Comment by seanvree** [comment]
Found the issue:

when you install this application using the setup.exe, it will change the defaultappool to Myrtille.  This is fine if you're not deploying MYrtille behind a  parent IIS site, But if you deploying this as an "application" behind an IIS site, you will get this error. In this case, you need to go to the IIS Application setting of Myrtille and change the default appool from Myrtille to "defaultapppol".  

Not sure if you want to put a note on the installation page, or somehow change that option in the installer to prompt the users to ask if this is going to be an application on an ISS website, or a parent site within ISS.

**Comment by cedrozor** [comment]
Hmm yes, I wanted to make things simple with the installer and deploy myrtille under the default website (not under a custom website or parent application).

MyrtilleAppPool" is inherited from "DefaultAppPool"; It allows to run myrtille in a separate IIS worker process and not interfere with the others IIS applications.

It's strange that you had such issue but, also, I didn't tested this use case....

**Comment by seanvree** [comment]
Yeah, all good, I'm sure there are only a few  people out there. I would suggest to add a note to your docs.

**Comment by cedrozor** [comment]
Indeed, I will. Thanks.
