### ISSUE TITLE
Blazor WASM

### ISSUE THREAD

**Issue by michalss** [cedrozor/myrtille#300]
Hi is there a way to use it with Blazor WASM please ? This would be revolution :)

Regards

**Comment by cedrozor** [comment]
Hi, do you mean having an RDP or SSH client into a web assembly?

**Comment by michalss** [comment]
Yes

**Comment by cedrozor** [comment]
I don't know if it's possible to port the FreeRDP/Myrtille C/C++ code into a web assembly (without speaking about the security/sandboxing aspects), but it wouldn't be easy for sure. If someone want to try, I would be happy to help!
