### ISSUE TITLE
The remote connection failed due to missing or invalid credentials

### ISSUE THREAD

**Issue by Git-Kyro** [cedrozor/myrtille#301]
hi i install myrtille on winServer2012R2, after the service started normally
when i access it to connect to other win servers remotely the prompt: 
   The remote connection failed due to missing or invalid credentials
  ask for your help, how can i solve it. thanks

**Comment by cedrozor** [comment]
Did you tried to connect with mstsc from the 2012 machine? is it working?

**Comment by Git-Kyro** [comment]
I am sorry, this problem has been solved
