### ISSUE TITLE
Install on Linux (docker)

### ISSUE THREAD

**Issue by hubermarkus** [cedrozor/myrtille#302]
Hi, 
would it be possible to run myrtille in a linux docker image?
what things need to be changed to get it in depended from windows?

**Comment by cedrozor** [comment]
You can run Linux containers under Windows, but not the other way around (see https://newbedev.com/docker-why-use-linux-containers-on-windows and https://stackoverflow.com/questions/42158596/can-windows-containers-be-hosted-on-linux).

Myrtille requires Windows as OS, so it was obvious to use a Windows container. Also, Windows containers are better supported by Windows and Docker for Windows (using Hyper-V isolation, etc.).

So no, to answer your question. But what you can do is create a Windows Server core VM on Linux and install Myrtille on it.

**Comment by mnaiman** [comment]
Which dependecies are on Windows OS? .NET FW can be migrated to Core and run on Win/Lin/Mac without problems.

**Comment by cedrozor** [comment]
These: https://github.com/cedrozor/myrtille#third-party
