### ISSUE TITLE
Clipboard Redirection Is Stripping All But One Character

### ISSUE THREAD

**Issue by navas** [cedrozor/myrtille#306]
Hi,

Is anyone can confirm if the freeRDP build comes with myrtille has the following issue fixed?

https://github.com/FreeRDP/FreeRDP/issues/2287

We use EHR software and when we copy from local machine to RDP, it only copies the first letter. Ex , if you copy "Amazon" and paste it in the remote session it only pasting "A" and stripping out rest of the characters.

**Comment by cedrozor** [comment]
Which version of Myrtille do you use? this was normally fixed many releases ago (https://github.com/cedrozor/myrtille/blob/master/CHANGELOG#L64)

```
2020-01-26 Version 2.8.0 (stable)
	...
	fixed an issue where only the first letter of the clipboard content was displayed on clipboard paste
```

Does the problem occurs only with your software or also with other applications? some applications have a custom handling of the clipboard which could lead to some issues through RDP.

**Comment by navas** [comment]
Hi ,

I really appreciate your response.

We use the latest version, and the copy / paste working for other applications such as notepad, it is just one software called eClinicalWorks which pastes only the first char and strips rest of the characters. We tried reaching out the software vendor but they aren't much helpful.  I can send you a video if you want.

**Comment by cedrozor** [comment]
Does the problem also occurs if you paste the clipboard from the contextual menu (menu right click)?

**Comment by navas** [comment]
Yes, it also happens when you use the contextual menu. 

Can I have your email ID please, I would like to communicate with email, so that I can explain the issue better.

**Comment by cedrozor** [comment]
Closing. Follow up in PM
