### ISSUE TITLE
Custom SSL cert

### ISSUE THREAD

**Issue by johnwmail** [cedrozor/myrtille#307]
Hi, how to setup custom ssl cert?
![image](https://user-images.githubusercontent.com/1752235/127948226-34e38dc4-a113-4ac5-8bf4-6123265785d2.png)
Thanks.

**Comment by cedrozor** [comment]
https://en.wikipedia.org/wiki/HTTPS

A good start: https://letsencrypt.org/

**Comment by johnwmail** [comment]
Sorry, my bad, let me explana more.
I am an Linux user, and I know how to setup SSL (letsencrypt) with nginx/apache on Linux.
But I know nothing IIS, and I when I googling "IIS setup SSL", a lot of documents is on window with GUI.
But I install Myrtille with docker, and there seems to be no GUI in the docker image.

When I use docker on Linux world,  the image author (usually) will use some parameters, to setup customer config, like "docker run -e cert /path/ssl-cert", so I wondering, will Myrtille docker support something like this?
If not , is there any documents for setup Myrtille docker customer SSL certificate?
Thanks.

**Comment by cedrozor** [comment]
Yes, you can do it through powershell, have a look to this tutorial: https://dejanstojanovic.net/powershell/2018/february/use-powershell-to-install-ssl-certificate-on-iis/

Then choose a store to save the trusted certificate, see https://www.jorgebernhardt.com/iis-ssl-powershell/

Here is how I did it for the self-signed certificate with the Myrtille installer:
https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1#L29

**Comment by johnwmail** [comment]
Sound like complicate (for a linux user), will try it later, thanks.
BTW,  the link seem to broken https://www.jorgebernhardt.com/iis-ssl-powershell/

**Comment by cedrozor** [comment]
Agreed, everything is a bit more complicated on Windows... 
The link works
