### ISSUE TITLE
Request nginx reverse proxy config sample

### ISSUE THREAD

**Issue by quaggalinux** [cedrozor/myrtille#308]
I want to use nginx reverse proxy on the Myrtille web url.
Do you have any nginx reverse proxy config sample for reference?

**Comment by johnwmail** [comment]
Hi, below one work for me (with myrtille docker)

-------------------------
server {
        listen          443 ssl http2 default_server;
        server_name     win.mydomain.com;

    ssl_certificate         C://nginx-1.20.1/mydomain/fullchain.pem;
    ssl_certificate_key     C://nginx-1.20.1/mydomain/private/privkey.pem;

        index   index.html;

        location /myrtille/ {
                proxy_pass http://127.0.0.1:8080/myrtille/;

                # general proxy env
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
        location = / {
                return 301 https://win.mydomain.com/myrtille/;
        }
    }
