### ISSUE TITLE
How to install the API?

### ISSUE THREAD

**Issue by LucasFelipeMacedo** [cedrozor/myrtille#309]
Hello,

I work with PHP and I don't know much about ASP.net and C#, could you send me a manual on how to install the API on a windows server, without visual studio?

Congratulations on your work, the program is excellent.

**Comment by cedrozor** [comment]
Hi, you can install Myrtille, using the installer, then the connection API will be available on http://localhost:8008/MyrtilleAdmin/ConnectionService

This API is meant to orchestrate connections across multiple Myrtille servers. You can specify its URL there: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L163

Others APIs are specific to a given Myrtille server: https://github.com/cedrozor/myrtille/tree/master/Myrtille.Web/src/Services. You can access them on:
- http://server/Myrtille/CaptureService
- http://server/Myrtille/DisconnectionService
- http://server/Myrtille/SharingService

You can watch a tutorials there: https://myrtille.io/ (demos) and see how to use them in this project: https://github.com/cedrozor/myrtille/tree/master/Myrtille.Admin.Web

It's C# but the principle of a REST client with PHP is the same

**Comment by LucasFelipeMacedo** [comment]
Thanks for your feedback, it worked for me.

I have another question, I'm having a viewing problem with the datagridviewer, all other windows native objects is ok. maybe you can help me, here's an image of how it's appearing and below how it should be, is there any setting that I can adjust this view?

https://www.dropbox.com/s/5zld1yk4dvytcqm/Imagem.png?dl=0


I adjusted the quality, but it still didn't improve.

**Comment by LucasFelipeMacedo** [comment]
Thanks for your feedback, it worked for me.
