### ISSUE TITLE
Difficulty to build Myrtille in VS 2015

### ISSUE THREAD

**Issue by SieldP** [cedrozor/myrtille#31]
Hi cedrozor,

Firstly, thank you for the program, It looks very good !
But I have somes difficultys to build the setup in Visual Studio 2015... Here's the errors:
http://img15.hostingpics.net/pics/226766error1.png
After reading the documentation, I tried to do a cmake on FreeRDP folder in Myrtille.RDP directory but I has an error when I tried to generate the Visual Studio solution:
http://img15.hostingpics.net/pics/953700cmd.png

Also, I dn't find the file sysinfo.c in  winpr ... Can You help me or just send me the fork of FreeRDP contained in the folder ? Thank
And Happy New Year :))

**Comment by cedrozor** [comment]
Hi SieldP,

The first error is due to the fact Myrtille.Setup does not build FreeRDP by itself (because it's not part of the solution and also use cmake to customize the build depending on the environment) and expect in place it to be already built separately.

The second is probably due to the fact VS2015 doesn't install the Visual C++ compiler by default. To install it, you have to run the VS installer again, choose modify and select the VC++ in the optional features list.

Additionaly, FreeRDP requires OpenSSL; before running cmake you will have to install it (https://wiki.openssl.org/index.php/Binaries). As I did, I suggest you to use the pre-compiled Win32/64 libraries without external dependencies to the MSVC++ reditributables.

The myrtille FreeRDP fork is located at https://github.com/cedrozor/FreeRDP

Happy new year! :)

**Comment by SieldP** [comment]
Thanx for reply

Then I have 3 warnings and 6 errors when I try to build FreeRDP (vers. 1.1) using Msbuild cmd.
Here is the first error : http://img15.hostingpics.net/pics/321050error11.png

And I have 57 errors when I try to build FreeRDP (vers. master).
I using VS 2015 and OpenSSL 32bits with using library in OpenSSL binaries (OpenSSL/bin)

Sorry for the inconvenience :/

**Comment by cedrozor** [comment]
I should update the documentation... the branch to build is the master (https://github.com/cedrozor/FreeRDP/tree/master), the stable-1.1 doesn't contain the myrtille code (all FreeRDP branches and tags were duplicated when I forked the repository).

The needed OpenSSL libs are indeed the 32 bits ones. Initially, I installed the 1.0.2h precompiled version from https://slproweb.com/products/Win32OpenSSL.html (now there is the 1.0.2j and even the 1.1.0c). cmake does detect it and configures the solution for it.

Later, I wanted to remove the MSVC++ redistributables dependency, both from FreeRDP and OpenSSL. I changed the cmake configuration to build FreeRDP with static linkage and replaced the OpenSSL binaries (into the FreeRDP build output folder) by the ones availabled at https://indy.fulgan.com/SSL/ (see https://wiki.openssl.org/index.php/Binaries for a list of precompiled binaries OpenSSL distributions). 

OpenSSL is reputed difficult to build, so I didn't wanted to bother with it (I already had some hard time mixing the FreeRDP C code  and Myrtille C++ code...).

Myrtille.Setup takes the FreeRDP exe and dlls and OpenSSL dlls (libeay32.dll and ssleay32.dll) from the FreeRDP build output folder (release).

I tried to make it simple, but when it comes to C/C++, it's more difficult than C# ^^

**Comment by SieldP** [comment]
That work thank you so much !!!!!!! <3 :)

**Comment by SieldP** [comment]
Thank you, now I succeeded to build it, but I have an error when I try to install the builded setup:
Http://img11.hostingpics.net/pics/352037last.png

But the installation works fine when I use your Setup .... I think something wrong in the setup configuration in the solution.

**Comment by SieldP** [comment]
Sorry, I have one last problem. I succeeded to build Myrtille but when I go on the server of a virtual machine with the builded Myrtille setup, and I click "connect", the RDP page appears and then disappears and I am redirected to Default.aspx page...

I saw in your video ( https://www.youtube.com/watch?v=l4CL8h0KfQ8 ) that you had 10 projects in the Myrtille solution. I have only 5: http://img11.hostingpics.net/pics/321135solumgl.png
Can you tell me what you loaded in the folder Myrtille.RDP? Thank you

**Comment by SieldP** [comment]
Thank you I secceded to built it :)
