### ISSUE TITLE
Tracking Disconnect

### ISSUE THREAD

**Issue by bastigerner** [cedrozor/myrtille#310]
Hello,

currently I am using Myrtille inside a iFrame in a Blazor Porject.
Connecting and disconnecting via a button is no problem, but I am trying to track a disconnect instantiated form inside the RDP Seassion. 

Basically I do not want to see the default myrtille landing page after a session has ended. Is there any way to track such a bevahiour from myrtille?

Kind regards

**Comment by cedrozor** [comment]
Hi, you can use the Myrtille API which tracks the active connection state (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services.Contracts/IConnectionService.cs) and implement your own code on disconnect (i.e.: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Admin.Services/Services/ConnectionService.cs#L93)

If you want your own landing page, you can set it into web.config: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L197
