### ISSUE TITLE
Myrtille Performance Issues

### ISSUE THREAD

**Issue by matthewincardona** [cedrozor/myrtille#311]
I installed Myrtille on an AWS EC2 instance and have been getting low latency (~30ms), but slow response times and poor mouse tracking on remote program sessions running Inkscape. My internet is ~50MB/s, I'm using the default Myrtille settings, and my server is running 4 CPU, 16GB RAM, and a 2GB GPU. Was wondering if there are any known performance issues with AWS? Thanks!

And side note, changing the image type to WEBP makes the programs run much slower, where I thought it would be faster than JPEG or AUTO. Any reason for this?

**Comment by cedrozor** [comment]
Did you tried to display the connection stats, from the Myrtille toolbar? there you can inspect the latency, bandwidth and many other useful info. You can also gather similar data using the browser devtools.

If the problem is network related, you can try to fallback to HTML4 (xhr + long-polling), but the real solution would be to find the bottleneck between the browser and Myrtille.

WEBP produces smaller images (lower bandwidth usage) but at the expense of speed and cpu usage on the server side.

**Comment by matthewincardona** [comment]
This is a video of me running Inkscape with ~30mb/s internet connection on Vivaldi. It seems to run faster on Edge and Chrome. Maybe that's where the problem is coming from?
https://user-images.githubusercontent.com/55165394/131032053-b1fa5b56-426f-40a7-92f0-5a7e304849e9.mp4

**Comment by cedrozor** [comment]
I don't know Vivaldi but, yes, the problem might come from it. The latency, bandwidth usage and other info look fine into the stats bar. Could you please make a video using Chrome or Edge?

If you didn't tried already, it would be interesting to test with long-polling or SSE, by changing the network mode into [config.js](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L146):

from
`var networkMode = networkModeEnum.AUTO;`
to
 `var networkMode = networkModeEnum.LONGPOLLING;` or
 `var networkMode = networkModeEnum.EVENTSOURCE;`

If you still want to use websockets (default), you could limit their number to 2:
` var websocketCount = 2;`

**Comment by matthewincardona** [comment]
Vivaldi is Chromium-based, but its security features might be slowing down the connection.

This is Chrome without any settings changed (debug is hidden despite being enabled in Web.config).
https://user-images.githubusercontent.com/55165394/131063703-8d656ddf-c126-4e01-952e-c428a4047e09.mp4

Longpolling on Chrome never loaded.

Eventsource on Chrome ran well, close to Websocket performance in Inkscape.

Which file has websocketCount? I don't see it in config.js

**Comment by cedrozor** [comment]
It's definitively better in Chrome. Did you enabled hardware graphic acceleration in Vivaldi? (it's enabled by default in Chrome). How is Eventsource with Vivaldi?

[WebSocketCount](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L147)

**Comment by matthewincardona** [comment]
Eventsource + Vivaldi runs just as slow as Websocket. Hardware acceleration is enabled by default.

My version of config.js looks a bit different from yours. I installed Myrtille using the download installer on [cedrozor.github.io/myrtille](https://cedrozor.github.io/myrtille/). Could these be different versions?

I've also noticed that connecting to a single program through my website will start up several versions of that program. This slows down the server and, consequently, Myrtille (this does not happen when connecting directly through a link, so it's not what's slowing down Vivaldi). I'm opening a [separate issue](https://github.com/cedrozor/myrtille/issues/312) for this.

**Comment by cedrozor** [comment]
> My version of config.js looks a bit different from yours. I installed Myrtille using the download installer on cedrozor.github.io/myrtille. Could these be different versions?

Yes, the current master version is not released (in test), but you can change websocketCount in the latest release

**Comment by matthewincardona** [comment]
> If you still want to use websockets (default), you could limit their number to 2:
> ` var websocketCount = 2;`

Changing the webSocketCount seemed to help, thanks!
