### ISSUE TITLE
Audio remain on Remote Machine

### ISSUE THREAD

**Issue by Panduin** [cedrozor/myrtille#316]
Hello,

I try to figure out how to configure the Remote Connection so that the Audio remains on the Remote Machine. Is this even possible? When yes can someone tell me where and how to configure this?

Thank you

**Comment by cedrozor** [comment]
Hi, yes you need to change the `audio-mode` to 1 there: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L356, like this:

`" /audio-mode:" + (allowAudioPlayback ? "1" : "2");  // audio mode (0: redirect, 1: play on server, 2: do not play)`

but that way, you will no longer have audio output into the browser. If you simply want to disable audio output, you can have `allowAudioPlayback` to false into the Myrtille web.config: https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L182
