### ISSUE TITLE
Is OASIS still available for 2fa verification?

### ISSUE THREAD

**Issue by halajohn** [cedrozor/myrtille#317]
After searching old issues, I found that OASIS 2FA is moved to https://www.oasis2fa.com/. However, https://www.oasis2fa.com/ continuously reports "503 Service Temporarily Unavailable" in these days. Is this service still available for use in Myrtille?
BR.

**Comment by cedrozor** [comment]
Hi, no sorry the service was discontinued recently. Please have a look to https://github.com/cedrozor/myrtille/discussions/318
