### ISSUE TITLE
Myrtille Taking Up a Lot of Memory

### ISSUE THREAD

**Issue by matthewincardona** [cedrozor/myrtille#319]
The longer Myrtille runs for, the more memory it takes up. Looking into dev tools -> network, the amount of resources being used goes up very quickly. I'm using JPEG with Canvas.

On a side note, are there any plans to add an mp4 option instead of streaming individual images?

**Comment by cedrozor** [comment]
Memory usage can increase quickly indeed, but is normally garbage collected after a certain time, server side (.net) as well as in the browser. Video streaming is possible yes, it's something that I would like to do for some time but unfortunately I never find the time.
