### ISSUE TITLE
Share session issue / Skype link preview

### ISSUE THREAD

**Issue by johnwmail** [cedrozor/myrtille#324]
I noticed , when I share session/link via skype to teammate, it never work and show the error "The sharing link was already used"
I suspect skype will somehow lookup the link once before sending out, so myrtille say "The sharing link was already used".
my question is, can I config/setup the myrtille share session/link reusable (let say within 5 times, or restricted within 5 min to login)
Thanks.

![image](https://user-images.githubusercontent.com/1752235/144569038-501ce315-d2a7-41fe-a79c-c83c31a175af.png)

**Comment by cedrozor** [comment]
Yes, this problem was already noticed with Skype. No, the links are designed to be used only once. What you can do, however, is disable the link preview on Skype: https://tipsmake.com/how-to-turn-off-or-show-the-preview-url-link-on-skype

**Comment by johnwmail** [comment]
Ok, I find the option to tune off preview on skype now, thanks.
