### ISSUE TITLE
Installation fails on Windows Server 2019

### ISSUE THREAD

**Issue by KristianLake** [cedrozor/myrtille#326]
Hi When installing 2.9.2 on windows server 2019, there is an error in the powershell ps1 file that causes the installation to fail.

Is windows 2019 supported yet?

Thanks

**Comment by KristianLake** [comment]
Checked the FAQ, IIS console was installed already.

**Comment by cedrozor** [comment]
What is the error please ? yes, Windows server 2019 is supported

**Comment by KristianLake** [comment]
We changed to a 2016 machine before i could check sorry.
