### ISSUE TITLE
404 resource not found 

### ISSUE THREAD

**Issue by ayoub-tl** [cedrozor/myrtille#327]
i installed myrtille by downlinf .msi file from https://cedrozor.github.io/myrtille/ and installed it , but when accessing the URL it shows 404
http://myserver:8080/myrtille.
also 
http://x.x.x.x:8080/Myrtille/?__EVENTTARGET=connect&__EVENTARGUMENT=&server=x.x.x.x&user=username&password=password&connect=Connect%21
and 
http://x.x.x.x:8080/Myrtille/?__EVENTTARGET&__EVENTARGUMENT=&server=x.x.x.x:8080&user=username&password=password&connect=Connect%21
![image](https://user-images.githubusercontent.com/68382823/146806044-2d01d3f1-b4a7-4c11-bd64-185e8a174e3b.png)

**Comment by cedrozor** [comment]
A simple test to do is try to connect `http://myserver`. If you don't see the IIS page, then either myserver is not accessible or IIS is not correctly installed. From the machine itself, also try `http://localhost/myrtille`; if it works, it may also be a DNS problem resolving "myserver".

Can you check with the IIS management console that Myrtille (web application) is correctly installed under the default website? Do you use the standard 80 (http) and 443 (https) ports? Did you tried `https://myserver/myrtille`? (just in case IIS is configured to reject http connections).  In any case, Myrtille is not accessible on port 8080.

For further details, have a look to the install logs (`myrtille\log\Myrtille.Setup.log` and `Myrtille.Web.Install.log` among others logs).

**Comment by ayoub-tl** [comment]
thanks for the response
, i was mistaken, I did not need to use the 8080 port, it was accessible on the 80 port, in the installation is mentioned that to access the service use the port 8080,

**Comment by cedrozor** [comment]
8080 is the port for the Myrtille backend (services) and is accessed internally by the Myrtille frontend (IIS webapp), from the Myrtille machine itself.
