### ISSUE TITLE
Myrtille and android

### ISSUE THREAD

**Issue by ibonetti** [cedrozor/myrtille#331]
Is there a way to show the smartphone keyboard when we click at a "textbox" in the remote connection? Or if there is a way to keep keyboard visible, anything like that.
Thanks in advance.

**Comment by cedrozor** [comment]
The smartphone keyboard normally shows when you click a textbox. However in Myrtille, these are not textboxes but rendered display. You have to manually "tell" your smartphone to show its keyboard, I'm not sure it's even possible with most smartphones.... or you can use the "keyboard" button into the Myrtille toolbar which displays an on-screen keyboard.

**Comment by ibonetti** [comment]
Thanks for the reply. I´m able to show the keyboard using a hidden input, bu i´ll have to do something to send the text to the rdp session.
Thanks

**Comment by cedrozor** [comment]
>  i´ll have to do something to send the text to the rdp session.

Have a look to the "Text" button, into the toolbar, this is what it does
