### ISSUE TITLE
dll's and exe's are not included in source file

### ISSUE THREAD

**Issue by mdsajidfaizan** [cedrozor/myrtille#36]
Dear All,
I am using this source code.
But below listed dlls are missing form the setup project.

freerdp-client.dll
freerdp.dll
libeay32.dll
ssleay32.dll
wfreerdp.exe
winpr-tools.dll
winpr.dll

Please let me know if i am searching on wrong place.

Thank you.

**Comment by cedrozor** [comment]
Hi,

Assemblies are never commited along with source code. You have to install OpenSSL and build FreeRDP (https://github.com/cedrozor/FreeRDP) as described into the documentation.

You can also use the installer (https://github.com/cedrozor/myrtille/releases/download/v1.4.0/Myrtille_1.4.0_x86_x64_Setup.exe), which contains and installs pre-compiled DLLs and EXEs.

Regards,
Cedric
