### ISSUE TITLE
404 Error and /myrtille/myrtille/Default.aspx not found

### ISSUE THREAD

**Issue by matifali** [cedrozor/myrtille#367]
When I try to access `http://localhost/myrtille` I get this,
![image](https://user-images.githubusercontent.com/10648092/236375829-fa53e997-7e73-4ff5-9cae-ed1c4c2362a1.png)

**Comment by cedrozor** [comment]
Myrtille was probably not installed successfully, you can check the installation logs (in the installation directory, C:\Program files (x86\Myrtille (by default)) to see what was the issue. Or maybe the Myrtille web application was registered under a different uri? (use the IIS console management to check the configuration)

**Comment by matifali** [comment]
Thanks for the response. I was accessing the above URL through a reverse proxy, and that was causing the issue. I found a workaround for now by opening the http:\\localhost and then redirecting to the the URL my app creates.

For full context you can see:
https://github.com/matifali/coder-templates/tree/main/gcp-windows-rdp
