### ISSUE TITLE
Session fixation protection

### ISSUE THREAD

**Issue by cedrozor** [cedrozor/myrtille#37]
Myrtille, like most ASP.NET applications, is vulnerable to [session fixation attack](https://www.owasp.org/index.php/Session_Fixation).

In brief, it's an attack which combines http session stealing an phishing.

One fix consists in generating a new session ID on login.

**Comment by tmakaro** [comment]
I thought most ASP.NET applications would have used the forms authentication cookie instead of a session cookie. I don't think session fixation attacks work with those.

**Comment by cedrozor** [comment]
Hi Troy,

Yes I think you are right, because the authentication ticket is set on login. I didn't used it initially because the authentication itself is made by the rdp server, not the gateway; but it could be an alternative, I will dig it.

**Comment by cedrozor** [comment]
Generating a new session ID upon login was (a bit) easier; also, the rdp server is still responsible for the authentication.
