### ISSUE TITLE
Myrtille starts but the web URL returns a 404 error

### ISSUE THREAD

**Issue by nviet** [cedrozor/myrtille#40]
Hi there, I'm trying to install Myrtille but I can't get it to work. My computer is running on Windows 8.1 with .NET framework 4 and IIS 10.0 installed.

After installing Myrtille (I set the HTTP port to , the service does start and the "MyrtilleAppPool" is running on IIS. However, when I try to access http://myserver/myrtille , I just get a 404 error.

So what have I done wrong?

**Comment by dcarba01** [comment]
You should check ASP.NET is registered within IIS.

**Comment by windylea** [comment]
I installed ASP.NET 4.5 module (through the **Turn Windows features on or off** in **Control Panel**) then tried again. At first the web page gave this error message:

> **Description**: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
> 
> **Details**: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

So I edited the file _Web.config_ in the program folder to add the tag as the page suggested and reloaded the web page. Then I got this error message:

> **Description**: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> **Exception Details**: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
> 
> **Source Error**:
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> **Stack Trace**:
> 
> [SocketException (0x271d): An attempt was made to access a socket in a way forbidden by its access permissions]
>    System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) +6703464
>    System.Net.Sockets.Socket.Bind(EndPoint localEP) +218
>    Myrtille.Fleck.SocketWrapper.Bind(EndPoint endPoint) +9
>    Myrtille.Fleck.WebSocketServer.Start(Action`1 config) +65
>    Myrtille.Web.RemoteSessionSocketServer..ctor(Global global, IWebSocketServer server) +267
>    Myrtille.Web.Global.Application_Start(Object sender, EventArgs e) +1085
> 
> [HttpException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions]
>    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9982013
>    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
>    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
>    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
>    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296
> 
> [HttpException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions]
>    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9963380
>    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
>    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

So what to do now?

**Comment by dcarba01** [comment]
Try giving write permissions to the log directory to the iis app pool user, and the iusr_xxxx Also try disabling the firewall for testing. Regards.

**Comment by windylea** [comment]
Hi, my firewall is already disabled. I tried to give the Write permission to the log directory as you told (here is a screenshot http://imgur.com/a/8Smxk ). After that, I run the service again:

> Service: Myrtille.Services.RemoteSessionProcess
> Endpoint: WSDualHttpBinding_IRemoteSessionProcess
> Address: http://localhost:8181/Myrtille/RemoteSessionProcess
> Binding: WSDualHttpBinding
> Contract: Myrtille.Services.Contracts.IRemoteSessionProcess
> 
> Service: Myrtille.Services.FileStorage
> Endpoint: BasicHttpBinding_IFileStorage
> Address: http://localhost:8181/Myrtille/FileStorage
> Binding: BasicHttpBinding
> Contract: Myrtille.Services.Contracts.IFileStorage
> 
> press any key to exit...

Accessing the page gives me a 500 Internal Server Error message. The file _Myrtille.Services.log_ is empty but the file _Myrtille.Web.log_ has this:

> 2017-04-03 08:39:24,697 [1] ERROR System.Diagnostics redirection [(null)] - Failed to start Myrtille.Web application (System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at Myrtille.Fleck.SocketWrapper.Bind(EndPoint endPoint)
>    at Myrtille.Fleck.WebSocketServer.Start(Action`1 config)
>    at Myrtille.Web.RemoteSessionSocketServer..ctor(Global global, IWebSocketServer server)
>    at Myrtille.Web.Global.Application_Start(Object sender, EventArgs e))

Can you help please?

**Comment by dcarba01** [comment]
Re-reading your message, I can tell you that I don't remember changing any port on the installer, and just accept the default configuration.
If I were you I would try re-installing or take a second look to the web config, where you have the bindings to the remote session and filestorage services , wich use a port different from the WebSocketServer port at the end of the file, on the appSetting section.
Hope this helps.
Regards,

**Comment by cedrozor** [comment]
It seems indeed related to the websocket server ports. Did you changed the default values (8181 and 8431) on install (which values did you set)? 

You have something blocking them (firewall or antivirus?), a system policy regarding private networks (http://stackoverflow.com/a/20623477) or they are already used by another process.

See http://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbbiden-by-its-access-permiss if it can help.

**Comment by windylea** [comment]
So, after many tries but I still haven't got it to work yet. Accessing the page just gives me a 404 error. Here is the summary of my situation:
- My computer is running on Windows 8.1 N 32-bit. IIS 10, ASP.NET 4.5 and .NET framework 4.0 are installed.
- IIS default ports are 80 and 443. Myrtille default ports are 8181 and 8143. These ports are not being listened by any other processes. Myrtille service starts without any problem.
- Firewall and antivirus are not installed at all.

I will try to install Myrtille on another computer in the same network to see if it works or not. Anyway, thank you guys very much for the help.

**Comment by cedrozor** [comment]
Some myrtille users had a 404 in the past. Did you registered on the [myrtille forum](https://groups.google.com/forum/#!forum/myrtille_rdp) ? there are at least 3 posts on that subject.

- One of them was an undefined issue with IIS / ASP.NET. Uninstalling/reinstalling the roles fixed it.
- Another was about the websocket server certificate (.pfx file into the myrtille ssl folder) being changed : restoring the original (self-signed certificate) fixed it.
- The last was about changing the port for the myrtille web application, from http 80 (default) to 8080; there is currently a bug when changing the default port (will be fixed in the next release); but it's not your case apparently

You should check the windows system and application event logs if you see something useful. It may also be an access rights issue; you can try to grant read/list permission to the "IIS AppPool\MyrtilleAppPool" user on the myrtille base folder. Also grant write permission to the myrtille log folder.

**Comment by prcdpr** [comment]
In my case I needed to enable ASP.NET 4.6 on Windows Server. I thought setup.exe is smart enough to enable this role, but documentation confused me

**Comment by CE1CECL** [comment]
![Capture](https://user-images.githubusercontent.com/52040854/106826387-d7476b00-6654-11eb-860a-2c29a2a212f4.png)
I'm having the same issue, tired the 2 latest versions, on 2 different machines, and I still can't get it to work.

**Comment by cedrozor** [comment]
404 is indeed "page not found".

You must have a typo into the url you enter or something that redirects this url to something else. Use the browser devtools (Ctrl+Shift+I), network tab, Fiddler (http proxy tool) or have a look to the IIS logs on the Myrtille machine to see what this wrong url is and thus be able to take steps to remedy it.
