### ISSUE TITLE
Remote App or start program support

### ISSUE THREAD

**Issue by dcarba01** [cedrozor/myrtille#41]
I installed and configure myrtille successfully. I can open sessions, and it works like a charm, but I couldn't start a remote app or an application using the "program to run" option.
I tried with the full path, with the || syntax, and always starts the desktop. Can you please help me with this matter?

**Comment by cedrozor** [comment]
Did you URL encoded the program path and name (and options if there are some) ? 

For example,

> C:\Program Files\MyApp\AppName.exe -with -some -params \"with spaces inside (please note that double quotes are escaped)\"

translates to:

> C%3A%5CProgram+Files%5CMyApp%5CAppName.exe+-with+-some+-params+%5C%22with+spaces+inside+%28please+note+that+double+quotes+are+escaped%29%5C%22

You can do it using http://www.url-encode-decode.com/

More details here: https://github.com/cedrozor/myrtille/wiki/Start-program-from-URL

**Comment by dcarba01** [comment]
Hello cedrozor, first of all. Nice Work!!!!

I encoded the URL as you suggest, when I tried the first time, but nothing happens. 

Don't worry about this, and again, congratulations.

Regards,

**Comment by cedrozor** [comment]
Hi, did you succeeded to start your program (from URL) ?
