### ISSUE TITLE
Error 1001 with an compiled Myrtille

### ISSUE THREAD

**Issue by mak1311** [cedrozor/myrtille#45]
Hi,

I have an error during the bin installation:
Error 1001. Unable to cast COM object of type 'System.__ComObject' to interface type 'CERTENROLLLib.CX509PrivateKey'. This operation failed because QueryInterface call on the COM component for the interface with IID '{728AB362-217D-11DA-B2A4-000E7BBB2B09}' failed due to the followinf error: ...

I get this error when I compile the project using VS 2015, But, when with your binnaries, I have any problem.

I tried on Windows 7 Pro, Windows 8.1 (IIS ienabled)

However, the installation goes well when I install it on the computer that compiled the program (Windows 10 Student)

I read the link in the Wiki for this error (1001) but I can not resolve it.

Thank you

**Comment by cedrozor** [comment]
Hi,

The CERTENROLLLib COM object is referenced under "Myrtille.Common" project ([there](https://github.com/cedrozor/myrtille/blob/69bf7ea4e5727f6330facbd11a67841f0919e22a/Myrtille.Common/Myrtille.Common.csproj#L161)) and is used by the installer to create a self-signed certificate.

After looking a bit, I found that : http://stackoverflow.com/questions/11421502/asp-net-certenroll-cx509certificaterequestpkcs10-exception

> Since in Win2008 R2 Microsoft overwrote the interface, if the code is written in Win2008 R2 the run time is looking for the new interface GUID and in regular Win2008 it can't be found because Win2008 R2 interface GUID differs from Win2008 interface Guid.
> So, object can't be created, and as the result exception is thrown.
> Accessing the interface by ProgID solves the issue.

I will try to update the code ([CreateSelfSignedCertificate](https://github.com/cedrozor/myrtille/blob/69bf7ea4e5727f6330facbd11a67841f0919e22a/Myrtille.Common/Helpers/CertificateHelper.cs#L28)) as detailed there : http://stackoverflow.com/questions/33001983/issues-compiling-in-windows-10

...or I could also use another libs, such as Bouncy Castle, just like they did there: https://github.com/bertjohnson/OpaqueMail/issues/45

Thanks for the report :)

**Comment by mak1311** [comment]
Thank you,

Work fine after remplacing : 
` var privateKey = new CX509PrivateKey(); `

by : 
` var privateKey = (IX509PrivateKey)Activator.CreateInstance(Type.GetTypeFromProgID("X509Enrollment.CX509PrivateKey")); `

:-)

**Comment by cedrozor** [comment]
Thanks, I will report it to the master branch :)

**Comment by cedrozor** [comment]
This may occurs again on Windows 7 machines because I moved to Visual Studio 2017 and Windows 10 as build environment; following the method indicated there: https://stackoverflow.com/a/39397121

**Comment by MrZakos** [comment]
Hi , this occurs on Window Server 2012 R2 also, please fix

**Comment by cedrozor** [comment]
Fixed into 1.8.1

Tested successfully under Windows 10, Windows 7, Windows Server 2016 and Windows Server 2012 R2
