### ISSUE TITLE
Websocket Error 1006

### ISSUE THREAD

**Issue by Arcath** [cedrozor/myrtille#47]
Myrtille was working great and now I get an error when I connect saying that the websocket connection failed with error code 1006.

![image](https://user-images.githubusercontent.com/19609/26878259-ca5459b0-4b84-11e7-87c2-21093cdd2188.png)

I'm sure that it is not my firewall. The service is running and everything so I'm not sure where the error is coming from.

It falls back to long polling at works.

**Comment by cedrozor** [comment]
Hi, did you changed or updated your browser? error 1006 means the connection was closed abnormally (locally) by the browser implementation (see https://stackoverflow.com/a/19305172)

**Comment by cedrozor** [comment]
Myrtille version 1.5.0 is out! :) it uses the same ports for http and ws protocols, so you should no longer have such issue.
