### ISSUE TITLE
Does this support all-in-one? And what's the suggested requirements?

### ISSUE THREAD

**Issue by ruiruige** [cedrozor/myrtille#49]
Is this allowed if I make the gateway IIS server and the RDP server to be the same server?

and if I install the whole system only for myself's personal use(I mean no more concurrent user), what's the suggested requirements:
1. bandwidth between the IIS and the browser
2. bandwidth between the IIS and the RDP server
3. how many memory and nums of CPU of the IIS

Thanks a lot.

And if available, I suggest that we can put the information onto the "requirements" of the main page

**Comment by cedrozor** [comment]
> Is this allowed if I make the gateway IIS server and the RDP server to be the same server?

Yes

> and if I install the whole system only for myself's personal use(I mean no more concurrent user), what's the suggested requirements:

A simple dual core with 4GB RAM will be enough

> bandwidth between the IIS and the browser

About 20KB/sec

> bandwidth between the IIS and the RDP server

About 50KB/sec (uncompressed bitmaps)

> how many memory and nums of CPU of the IIS

The gateway work is minimal, most of the resources will be used by the rdp client process(es); about 50KB RAM by process most of the time

Thanks a lot.

> And if available, I suggest that we can put the information onto the "requirements" of the main page

Good idea

**Comment by cedrozor** [comment]
Added to readme in version 1.5.0 :)
