### ISSUE TITLE
Improved file transfer

### ISSUE THREAD

**Issue by cedrozor** [cedrozor/myrtille#5]
Myrtille features a simple file transfer from/to the connected user documents folder. While it' sufficient for basic needs, it could be improved for more a advanced usage (i.e.: show file properties, size, preview, change permissions, etc.).

Your help is welcome! :)

**Comment by rahulraghu94** [comment]
Hello,
I was going through this project and found it quite fascinating! I thought this might be a good place to begin contributing towards it.
However, I was looking through the installation instructions and seems like it's compatible only with a Windows machine. I use Linux and I do not have access to Windows and I'm not sure where to go from here, if there is even a way!

**Comment by cedrozor** [comment]
Hi, unfortunately no, myrtille is targeted to Windows as its uses IIS and .NET. There are pros and cons, for example being able to use Windows based features such as hardware GDI (http://unix.stackexchange.com/questions/219171/why-are-rdp-clients-on-linux-much-slower-than-on-windows) but at the cost of portability. Often too, people or companies having Windows (RDP) servers also have Windows clients.

You can have a look to [Guacamole](https://github.com/glyptodon/guacamole-client), it's very comparable to myrtille and is for Linux.

That said, the code I added to the FreeRDP Windows client (https://github.com/cedrozor/FreeRDP/tree/master/client/Windows) for myrtille can also be added to the FreeRDP Linux client; then there will be some work to have a myrtille linux gateway working similarly as the windows one, but it woudn't be so difficult (Apache/Java instead of IIS/C#). The javascript code would be the same.

**Comment by rahulraghu94** [comment]
I was really looking forward to get involved!
Thanks for the taking the time out to suggest another project :dagger: 
I'll have a look right away.

Good luck :D

**Comment by cedrozor** [comment]
If you really don't have access to Windows, porting the gateway to linux would be a nice way to get involved! ;) By the way, I don't use any fancy .NET feature, so I guess [.NET core](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/) could be used for that purpose. The C++ code used into FreeRDP is already portable.
