### ISSUE TITLE
Encryption and Tunneling

### ISSUE THREAD

**Issue by pierremta** [cedrozor/myrtille#50]
Hello,

The connection between Myrtille and the client it is secure ? Did you use asymmetric encryption to do communicate ?

Thank you

**Comment by cedrozor** [comment]
Do you mean the communication between myrtille and the browser? If that is, yes it's encrypted if the page is accessed using https.

If you mean the communication between myrtille and the rdp client, it could be but currently isn't because both are on the same machine (IPC communication).

**Comment by SieldP** [comment]
I mean betwenne myrtille and the browser yes :)

The probelm is that I tried to use nginx server as proxy to IIS: I set the IIS secure port : 8443 and then I redirect nginx from 443 port to the port 8443.
When the redirection work well, but when I try to lunch an RDP Session from Myrtille, I get timeout expired message ... 

There is my nginx configuration:


```
server {
		listen 80;
		return 301 https://$host$request_uri;
}

server {
		server_name localhost;
		
		listen 443 ssl;
		ssl_certificate ./ssl/public.crt;
		ssl_certificate_key ./ssl/private.rsa;
		
			location /Myrtille{
                proxy_pass         https://127.0.0.1:8443/Myrtille;
				proxy_set_header Host $host;
				proxy_set_header X-Ssl on;
			}
		}
```

**Comment by cedrozor** [comment]
Good idea to use a reverse proxy for myrtille with redirect from port 443 to 8443. However, the latter is meant for the websocket server and not IIS.

I'm not sure if nginx is capable of redirecting a given protocol (wss:// and not https://) but, if it is, it should be configured to do that.

The upcoming myrtille release does support native IIS8+ websockets and uses the standard tcp 80 and 443.

**Comment by pierremta** [comment]
Hi,

I succeed to redirect IIS server with nginx, however, I noticed that when I turn off nginx server, the RDP session is still connected.. It's because that I redirect nginx to the IIS server and not the ws ?
I don't know how to proceed to redirect nginx to ws : should I use port 8080 ?

Thank you.

**Comment by cedrozor** [comment]
I don't know well nginx either but it seems possible (https://www.nginx.com/blog/websocket-nginx/).

However, i'd suggest you to use myrtille 1.5.0 which uses the same ports for http and ws, as soon as it's stable (currently beta).

**Comment by cedrozor** [comment]
1.5.0 is stable now, you should try it out :)
