### ISSUE TITLE
Connecting automatically

### ISSUE THREAD

**Issue by philrykoff** [cedrozor/myrtille#53]
Hi,

first of all - myrtille is really easy to use compared to Guacamole :-)

I'd like to embed myrtille into an existing web application using an iframe. Using the described link algorithm, I have:

`https://<host>/myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=localhost&domain=<domain>&user=<user>&password=<password>&program=calc.exe&connect=Connect%21`

When the page is loaded, the password has not been written to the password field and it does not seem to be connecting (automatically). Is the link somehow wrong? Or is this intended behaviour?

I am currently working around it by posting a message to the myrtille iframe and executing some custom JavaScript which sets the password field and simulates a click on the connect button.

Thanks for your feedback!

**Comment by cedrozor** [comment]
Hi,

Thanks, yes I tried to have it super simple :)

In addition to the params you are passing into the URL, you need to pass the display resolution (*width* and *height*).

It's currently autodetected when you click "Connect!" on the login screen but not from an URL. I'll try to see if it's possible to autodect it, if missing.

**Comment by cedrozor** [comment]
I just tested and, after appending"&width=<width>&height=<height>" params, it works.

However, there is a regression (bug), probably due to the anti session fixation attack added to the 1.5.0, because each time you refresh the page after logging in, it starts a new remote session :/

I'll see to fix that.

**Comment by cedrozor** [comment]
Fixed it and updated the release 1.5.0.

If you don't specify a display resolution into the url, it will now autodetect it from the client. If you do, it will override it.

Page refresh after logging in no longer starts a new remote session.

**Comment by philrykoff** [comment]
Thanks a lot for implementing that & fixing the reconnection "bug" at the same time! 👍

**Comment by cedrozor** [comment]
You're welcome :) into the version 1.5.0, I also added the ability to encrypt the password into the url! just replace "&password" by "&passwordHash=" into the url (see https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#start-remote-application-from-url)
