### ISSUE TITLE
session crash when text entry in MS WORD 2010

### ISSUE THREAD

**Issue by luchenue** [cedrozor/myrtille#54]
it will happen when entry more than one letter.

**Comment by cedrozor** [comment]
Is the problem happening when you run MS Word into a console session ? or into an mstsc (rdp) session? From the issue description, it may be due to the spell checker; see https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_win10/word-2016-keeps-crashing-while-using-spell-check/63886e08-ab72-4b0e-8464-5393aadc2a22 and also have a look to the event logs (as also described into the link)

**Comment by cedrozor** [comment]
The above link was for MS Word 2016, but the problem already existed with MS Word 2010 : https://answers.microsoft.com/en-us/office/forum/office_2010-word/word-2010-regularly-crashes-when-spell-checking/3c7a0ce7-c4bc-43c7-b479-691360738147

It may be a corrupt dictionary (you can try to reset or delete it).

**Comment by luchenue** [comment]
the crash session seems to be MYRTILLE, 
because after crash i use mstsc.exe tp connect, everything is ok
I try to delete corrupt dictionary, but nothing different.

screen record:
![2017_07_26_10_07_26_170](https://user-images.githubusercontent.com/1430668/28601815-1148a41e-71ed-11e7-951c-34de4733d0de.gif)

**Comment by luchenue** [comment]
I tried Word **2016** everything was fine
but worried about other software can cause similar problems like 2010

**Comment by cedrozor** [comment]
Thanks for the video.

There must be something with FreeRDP (the rdp client used by myrtille). I never tested with chinese characters, it may be related to the glyph cache (enabled with myrtille, but tagged experimental).

Can you do the following:
- Stop "Myrtille.Services" (windows service) on the myrtille machine
- Enable "RemoteSessionLog" (value="true") into [myrtille install path]\bin\Myrtille.Services.exe.config
- Start "Myrtille.Services"

Then retry with myrtille and Word 2010 as you did. The remote session log will be stored into [myrtille install path]\log, and timestamped with wfreerdp process ID.

If you doesn't have anything useful into the log file (no indication why the session froze or crashed), you can also do the following:

From a command line console, set the environment variables on the myrtille machine (40.44.0.107):
```
SET WLOG_APPENDER=FILE
SET WLOG_FILEAPPENDER_OUTPUT_FILE_PATH=[myrtille install path]\bin
SET WLOG_FILEAPPENDER_OUTPUT_FILE_NAME=wfreerdp.log
SET WLOG_LEVEL=DEBUG
```
Then run FreeRDP (into the myrtille bin folder) from command line as follow: wfreerdp.exe /v:40.44.0.229 /u:administrator /p:yourpassword /log-level:DEBUG

It will run FreeRDP without myrtille integration, glyph cache disabled and more FreeRDP logs. Once connected, try to run Word 2010.

If that works, the problem may be the glyph cache, or another FreeRDP param used by myrtille. In this case, I'll instruct you further steps to diagnose the issue.

If that doesn't work, please send me the log :p

**Comment by luchenue** [comment]
when I set RemoteSessionLog true,  Word 2010 run fine
but set RemoteSessionLog false, it crash again

**Comment by cedrozor** [comment]
There must be a race condition with FreeRDP. Enabling "RemoteSessionLog" slightly slows the program execution, which must avoid the problem.

But it's not a proper fix to leave it enabled...

After FreeRDP crash with Debug, do you have something useful into wfreerdp.log?

**Comment by luchenue** [comment]
nothing useful in  wfreerdp.log
[wfreerdp.txt](https://github.com/cedrozor/myrtille/files/1179771/wfreerdp.txt)

**Comment by cedrozor** [comment]
Thanks for the logs.

Myrtille already uses software gdi (and it was anyway enforced for Windows lately into the FreeRDP codebase (https://github.com/FreeRDP/FreeRDP/commit/61ab600c1441fe5dad9251fb426f40eebbbc98a0)).

The params on your 3rd test are those used by myrtille (you probably attached a debugger under VS).

Before entering some text into Word 2010, can you try to disable the spell checker? also try to disable the  glyph cache ( -glyph-cache).

If it's a race condition, it can work sometimes and crash another times... it's difficult to track down :/

Anyway, it's weird that it works fine with Word 2016 and not with Word 2010...

**Comment by luchenue** [comment]
**spell checker** has been closed

temporarily closed to issue, if there is something new to continue to communicate

**Comment by cedrozor** [comment]
I'll install and try with a Word 2010 on a Windows Server 2008 R2 (your config).

Did you tried with glyph cache disabled?

**Comment by luchenue** [comment]
thx.
i disable glyph cache in RemoteSessionProcess.cs, it also crash

**Comment by cedrozor** [comment]
Hi, I made some changes into [myrtille 1.6.1](https://github.com/cedrozor/myrtille/releases/tag/v1.6.1) that should fix the issue. Could you retry and tell me if it still occurs? thanks!

**Comment by cedrozor** [comment]
The issue seems fixed. Closing :)
