### ISSUE TITLE
.installState file not found

### ISSUE THREAD

**Issue by MobilenerdSiri** [cedrozor/myrtille#55]
I'm using the .exe file to install myrtille on windows server (Azure). The installation is failing with the above error.
Could not find file myrtille\bin\myrtille.services.installState 
Help would be appreciated.
Thanks.

**Comment by cedrozor** [comment]
Did you had an error code (1001 perhaps?) given by the installer? you may find additional info into the Windows event logs (System and Applications).

Did you enabled IIS and ASP.NET 4.5 on your machine prior to the installation? (https://stackoverflow.com/questions/6425442/http-error-404-3-not-found-in-iis-7-5/8487214#8487214)

More troubleshooting info: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot
