### ISSUE TITLE
Integrating my remote caputre application to the Myrtille 

### ISSUE THREAD

**Issue by danielfdeus** [cedrozor/myrtille#57]
First of all, I'd like to congrat everyone by the awsome project.

My application capture the content of an application’s DirectX, OpenGL or Vulkan render context using Nvidia APIs and encode that buffer producing a .h264 file.

After that I stream the file over IP network, as an exemple:
http://127.0.0.0:3000 - user0
http://127.0.0.0:3001 - user1
...                                    ...

I'd like to integrate that to the Myrtille by first I'd like to know how, because I don't want to send the entire desktop but only the App enconded.

*** I'v read this [thread ](https://github.com/cedrozor/myrtille/issues/27)and this [thread](https://github.com/cedrozor/myrtille/issues/41), but the RDP alternative is a done solution.

**Comment by cedrozor** [comment]
Nice idea but, indeed, it make sense to send only the application rendering, and not the whole desktop. Moreover, only the updated area(s) of the application rendering should be sent. That's what the RDP protocol do, in addition to user session management, that's the reason we started with it.

That said, HTML5 does support H264 streaming, so it's also a good idea. We thought about it long time ago (2009), but having a real time encoding at this time was tricky (mostly on VMs where hardware graphics was not available); we tried multithreaded OpenCL, CUDA, etc. but it also proven quite difficult to code.

Following the "simple is better" pattern, we decided to keep it simple and go only with regions bitmaps, compressed as PNGs and/or JPEGs.

But starting with RDP 8.0, the H264 encoding is natively supported, so it may be time to use it :)

Any help is welcome about that. Audio could also be captured and sent within the H264 stream.

**Comment by danielfdeus** [comment]
Yes. It is exactly I'd like to do which is send only the game process. 

So, is there any intention Myrtille implement RDP 8.0 in any future releases?
 
I'wil really appreciate that to implement together with my applications.

**Comment by cedrozor** [comment]
H264 integration with Myrtille is planned yes, but I don't know when exactly because last time I checked FreeRDP with H264 enabled there were 2 issues:
- Some glitches with the rendering
- Some FreeRDP crashes (read/write access violation), see https://github.com/cedrozor/myrtille/releases/tag/v1.5.0

So it seems H264 is a bit unstable with the latest FreeRDP branch. It's unfortunate because I noticed a significant performance improvement with it.

I'll enable it with Myrtille as soon as it's stable. It will require some work however, to send the H264 stream to the browser instead of compressed images.

**Comment by cedrozor** [comment]
About games also, if you plan to keep a good framerate, it will require some serious CPU/GPU power and network bandwidth; RDP also does support remoteFX but I'm not sure it's made for games; so yes, it's better to use DirectX, OpenGL or Vulkan for capture but you'll have to find a way to interface it with RDP afterward...
