### ISSUE TITLE
Data security enhancement

### ISSUE THREAD

**Issue by philrykoff** [cedrozor/myrtille#60]
Hi!

Thanks for developing myrtille again :-)

While we analyzed myrtille in regards to data security, we figured out that while we need auto login (so login using a specific domain, username, password combination), we cannot allow the user to take the URL and reconnect to myrtille at a later - unauthorized - time.

I was thinking about adding a web service to myrtille, which takes domain, username and password and returns a one time access token. The login page would then need to be extended to allow the login via said access token (only via GET param, no need for form input). The Access tokens need to be stored somewhere - SQLite would probably be overkill, a map? - and invalidated after a login with them (one time; so they can not be used again). The web service itself would need to be secured by a secure token configurable via some config file. All other parameters of the login (width, height, executable) would still be taken from the GET params.

Would you accept a PR? Any directions on where to place the WebService / security token would be appreciated.

**Comment by cedrozor** [comment]
Hi Phil,

One time login token is a good idea. Sure, a simple webservice could handle that; but, if you want something more robust/secure/flexible, you could also consider a [multi-factor authentication](https://en.wikipedia.org/wiki/Multi-factor_authentication) (or at least 2FA) to provide the token.

Here is a list of authentication providers : https://en.wikipedia.org/wiki/Comparison_of_authentication_solutions

On a side note, I had requests in the past about implementing SSO into myrtille. If you want the token to be valid accross the RDS farm (and not a given server), you may consider coupling your token provider to an RD connection broker and gateway (see http://woshub.com/sso-single-sign-on-authentication-on-rds/).

**Comment by philrykoff** [comment]
Hi cedrozor,

while your suggestion is indeed a lot more robust and flexible than what I proposed for securing access... we don't really need to authenticate the users. 😁 

We'd like to include a Myrtille iframe into our intranet solution. As our users are already properly authenticated (with single / two factors), they should just not take the link and be able to access the VM at a later time without a track record of that on our platform. 

The discussion started with us not wanting to expose username and password in the URL. Then someone read your splendid docs and found out that the password could be encrypted. Nevertheless, once the URL including username and password (encrypted or not) is known to someone, that someone cannot be easily blocked from accessing the machine. Hence the one time pass idea.

Thanks for your go ahead! I'll get this to our team and once we get green light, I'll create a PR.

**Comment by cedrozor** [comment]
You're welcome. Please try to have it generic (working with an iframe or not, user pre-authenticated or not), so other people can use it :)

**Comment by cedrozor** [comment]
Hi, any news on this?

**Comment by philrykoff** [comment]
Our vendor is currently implementing this. ETA about 2 weeks.

**Comment by cedrozor** [comment]
Please check myrtille 1.8.0 (beta); I hope it can fit your needs.
