### ISSUE TITLE
Grammatical errors in README.md

### ISSUE THREAD

**Issue by therohitramesh** [cedrozor/myrtille#62]
The first subheading reads **How does it works?** whereas it should be **How does it work?**
The first line in that section itself has the words **maintain a session**. It should be **maintains a session**, instead.
In the same section, last line it is supposed to be **More information in the DOCUMENTATION.md file.**

**Comment by therohitramesh** [comment]
I would like to work on this.

**Comment by cedrozor** [comment]
Merged. Thanks for this, english is not my native language.
