### ISSUE TITLE
how to simulate a right-click

### ISSUE THREAD

**Issue by ladygh** [cedrozor/myrtille#65]
Maybe my question is stupid..
I tried several htm5 RDP client, it seems all of them don;t support right-click.
Is there any way to simulate a right-click ?

**Comment by cedrozor** [comment]
You mean on iOS? Normally, the gesture is a long touch (https://support-splashtoppersonal.splashtop.com/hc/en-us/articles/230005547-Introduction-to-iOS-gestures-iPad-iPhone-), but it doesn't work currently with myrtille (which overrides the default mouse/touchscreen handlers).

I can see to add a "Right Click" button (into the myrtille toolbar, on top of the screen) to simulate a right-click (on the last left clicked coordinates, for example).

**Comment by ladygh** [comment]
Hi, thanks for reply. I mean in windows, I’m using Firefox.

________________________________

**Comment by cedrozor** [comment]
I just re-checked on Window 7 and 10, with the latest Firefox update, and the mouse right-click worked. Did you installed an extension or something which could block the right-click?

**Comment by cedrozor** [comment]
implemented in version 1.6.0

**Comment by cedrozor** [comment]
I will add a toggle button for a better right-click managemenent in a next release
