### ISSUE TITLE
Unable to Run a program

### ISSUE THREAD

**Issue by FMiscia** [cedrozor/myrtille#66]
Hello, first of all thank you for this amazing job.
I installed and configured myrtille 1.5.0 on a Windows7 machine. 
Everything works fine except of the "run a program" option.
Either by the form or passing the arguments (encoded) by URL I receive always the plain desktop as a result.

This is an example that gives me the desktop and not the notepad
http://172.16.1.16/myrtille/?__EVENTTARGET=&__EVENTARGUMENT=?server=172.16.1.16&domain=&user=user&password=password&program=notepad.exe&width=500&height=500&connect=Connect%21

And putting "notepad.exe" as value in the input form gives me the same result.

Am I missing anything?

**Comment by cedrozor** [comment]
Hi, you're welcome :)

First at all, you should install the [version 1.6.0](https://github.com/cedrozor/myrtille/releases/tag/v1.6.0), which brings some security fixes, performance improvements and a little refactoring of the auto-connect / start program from url feature.

For more safety if you distribute the link, you can also hash the password as described [here](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#syntax).

Also, if the server IP is the same as the gateway, you can use "localhost" for the server param.

Regarding your issue, there is a typo in you url, you must have a & before the server param and not a ?

That said, it should work (tested it successully with your url, just changing IP and credentials). You should double check your credentials encoding into the url (http://www.url-encode-decode.com/)

**Comment by cedrozor** [comment]
But if it also doesn't work with the input form, it must be something else.

Is your server a Windows 2008 server ? sadly, neither the FreeRDP /shell nor /app feature work with that OS :/ (see [notes and limitations](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#notes-and-limitations)).

**Comment by FMiscia** [comment]
Thank you for the reply.
I'm running Myrtille for testing on a Windows7 machine, maybe I should try on a more recent Windows distribution.
 I fixed the typo in the URL but the result is the same.

Did you ever notice issues like this related to Windows7?

Anyway, I will let you know deploying everything on another Windows ;)

**Comment by cedrozor** [comment]
Is Windows 7 the machine on which you installed myrtille (the http gateway) or the machine you are trying to connect (the rdp server)? 

I only noticed that with Windows server 2008, and lately tested it with success with a Windows server 2012 R2 and Windows 10. I have to re-check with Windows 7.

**Comment by FMiscia** [comment]
> Is Windows 7 the machine on which you installed myrtille (the http gateway) or the machine you are trying to connect (the rdp server)?
It acts both as gateway and server

Actually I have the same problem with Windows 10 (using it as gateway and server). I'm wondering whether this functionality works only on Windows Server editions or I'm missing something else.

It is strange because I'm able to connect to the entire desktop, but not to a single application, and I'm trying both with the default form and the URL

**Comment by cedrozor** [comment]
Indeed I (re)tested it  on Windows 10 and it doesn't work :/ This can either be a regression or something that escaped the tests. I will investigate, thanks for reporting the issue!

**Comment by cedrozor** [comment]
If you have the same problem with Windows 7, Microsoft may have disabled that functionality for non Windows Server editions :/

**Comment by FMiscia** [comment]
> If you have the same problem with Windows 7, Microsoft may have disabled that functionality (on a recent patch?) for non Windows Server editions :/

Probably yes. 

Anyway I moved on a Windows Server edition and everything works perfectly.

**Comment by awthank** [comment]
Hello
I installed and configured myrtille 1.6.0 on a Windows Server 2012 R2 machine.
I receive error ...
The system can not find the file specified
Unable to start this initial program:notepad.exe

or Unable to start this initial program:C:\Windows\system32\notepad.exe
How can check this problem?

**Comment by cedrozor** [comment]
Hi, this is strange indeed.

Did you tried to run `C:\Windows\system32\notepad.exe` (Windows is installed on `C:\`, isn't it?), manually from a command line, within the rdp session? Does the connected user have the rights to run notepad (maybe some GPOs misconfiguration, even if you don't seem to use a domain)?

Remoteapp only allows listed programs to be run through rdp. It shouldn't be related (myrtille use an alternate shell instead of remoteapp), but could you try to run (import registry keys) [RDPSetup.reg](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Setup/RDPSetup.reg) (located into the myrtille bin folder) on your rdp server (192.168.88.200)? what I'm interested in is [this key](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Setup/RDPSetup.reg#L8).

Do you have the same issue with mstsc.exe?

**Comment by awthank** [comment]
Hello
sorry, i didn't run the RDPSetup.reg.
It works fine after run the RDPSetup.reg.
thanks your help.
