### ISSUE TITLE
How to see desktop background on remote computer?

### ISSUE THREAD

**Issue by Sydrik** [cedrozor/myrtille#73]
Awesome software.

I have a wallpaper on my remote desktop. If had made sure to set _Enforce Removal of Remote Desktop Wallpaper_ to _Disabled_ on the remote desktop. If I use Remote Desktop Connection, I would have changed the connection quality to allow me to check the option _Desktop background_ under the _Experience_ tab. So, how do I do the same on Myrtille?

Thanks.

**Comment by cedrozor** [comment]
Hi, thanks. I'm a bit ashamed to say it's currenly hardcoded (for performance purpose).

I will try to make it configurable in a future release (config file or UI). In between, you can change it [there](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L100), by setting `+wallpaper`.

**Comment by Sydrik** [comment]
Great, thanks! I look forward to this new feature then.
