### ISSUE TITLE
Running Myrtille with more than one Session Host

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#75]
I'm trying to understand how Myrtille works. I have the following RDS scenario: I have 1 VM with the Broker and the Licenses 2 Session Host VMs, the question is how will Myrtille access the session of one of these hosts, how will Myrtille choose a host? Or is this the Broker's responsibility?

**Comment by cedrozor** [comment]
It's the broker responsibility. Myrtille doesn't do any load balancing, it just connect an rdp client (wfreerdp) to the address entered into the login page.

If the address is a Session Host server, it connects it directly; if it's a Connection Broker, the broker will redirect the connection to the appropriate host into the RDS farm (https://technet.microsoft.com/en-us/library/cc772245(v=ws.11).aspx).
