### ISSUE TITLE
Keyboard problem

### ISSUE THREAD

**Issue by sina-attarzadeh** [cedrozor/myrtille#77]
Hello All

I have installed Myrtille on my windows 10 machine, then connect by my browser from another windows 7 machine and after establishing the connection some keys on keyboard do wrong action, I press LEFT arrow key then it prints 2 and UP key then prints 8 for instance. I have tried Chrome, Firefox and IE too.
The problem began when I used ALT key.

**Comment by cedrozor** [comment]
Hi, numlock/capslock are sometimes inverted; this is a known behavior of older versions of rdp (https://social.technet.microsoft.com/Forums/forefront/en-US/c002126a-0f50-49e0-977c-d66ec051c880/num-lockcap-lock-are-working-in-reverse-on-terminal-server-2012-r2?forum=winserver8gen).

Someone already reported this issue  (https://github.com/cedrozor/myrtille/issues/11) and I had it myself also (quite rarely).

It doesn't depend on the browser but on the remote session. Try to enable/disable numlock and see if it works. Also try to hit the ALT key another time, in case the key modifier wasn't released (i.e: lost focus on the browser window before releasing the key).

If it doesn't work, the session is bugged; you'll have to disconnect/reconnect it.

**Comment by sina-attarzadeh** [comment]
Great,
I turned of the NUMLOCK and it is work smoothly, but still ALT key does not work probably, I used an application which on defined some short key combination with ALT.

Although it is fine for me and I can handle it.
Thanks a lot.

**Comment by cedrozor** [comment]
You're welcome.
