### ISSUE TITLE
Resources for Gateway

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#80]
The link https://github.com/cedrozor/myrtille/wiki/resources says that a simple dual core CPU with 4 GB of RAM is recommended for the gateway. When you talk about the gateway, do you talk about the RD Gateway server or the Myrtille service?

Already in the link https://github.com/cedrozor/myrtille/wiki/notes-and-limitations says that myrtille gateway and services are installed on the same server. Who is myrtille gateway and what is the difference for RD Gateway?

Using Myrtille I still need RD Gateway and RD Web Access?

**Comment by cedrozor** [comment]
Myrtille, by itself, is an http to rdp gateway; it's composed of 2 parts:
- a web application
- a windows service

The web application can be compared with RD Web Access, but works in any browser (pure HTML 4&5).
The windows service handles rdp sessions and bind them to http contexts.

When talking about the gateway, I talk about myrtille (combination of both a web application and a windows service).

Using myrtille, you don't need RD Gateway and RD Web Access.

**Comment by welsonplay** [comment]
Thank you very much for your response and for responding quickly.
