### ISSUE TITLE
Starting app not working with Windows Server 2012

### ISSUE THREAD

**Issue by MrASousa** [cedrozor/myrtille#83]
I followed the setup and got my server running right away.
But whenever I try to start my application with a program as a parameter, it doesn't work.
So far those are the attempts I made:

`https://172.xx.xx.xx/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=172.20.9.67&user=support&password=123456&program=C:\Windows\System32\notepad.exe&connect=Connect%21
`
`https://172.xx.xx.xx/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=172.20.9.67&user=support&password=123456&program=C%3A%5CWindows%5CSystem32%5Cnotepad.exe&connect=Connect%21
`

Whenever I use those links, it will call just the desktop, without opening any program.
Not really relevant, but at the current Chrome version, it is not working, just on Firefox and Opera browsers.

Is anything wrong with my calls? Am I getting something wrong? I don't really know what is the EVENTTARGET and EVENTARGUMENT, so I left the default value as you guys can see.

Great application! Thanks for the effort in making it! Glad I can use it.

**Comment by cedrozor** [comment]
The "start program from url" feature doesn't work on Windows 10 (I should update the documentation) but should work on 2012 R2 server (worked last time I tested, anyway).

Your system drive is C:, isn't it? did you tried using mstsc, with notepad as startup program, does it work?

Do you also use remoteApp on the target server? if so, you may need to add notepad to the allowed programs. You can also import the RDPSetup.reg file (located into the myrtille bin folder) on the target server to configure it automatically.

**Comment by cedrozor** [comment]
Did you got it working?

**Comment by MrASousa** [comment]
Yes, but I could only make it work when I changed the server, but it's all working fine now! Thanks.

**Comment by cedrozor** [comment]
Nice :)
