### ISSUE TITLE
authentication required

### ISSUE THREAD

**Issue by ShankzPatil** [cedrozor/myrtille#84]
hi,

i had done installation from release path.
and the tried to open https://localhost/Myrtille 
then browser prompt authentication required screen with username and password.

i don't know default username and password to login.

please help me.

**Comment by cedrozor** [comment]
Hi, this is the user authentication for the rdp server you want to connect

**Comment by ShankzPatil** [comment]
then how to set user credentials.
I Am not able to figure out login details after successful installation

**Comment by cedrozor** [comment]
It's the windows credentials for the user account you want to connect, just like when you use [mstsc](https://en.wikipedia.org/wiki/Remote_Desktop_Services#Remote_Desktop_Connection)
