### ISSUE TITLE
USB redirection

### ISSUE THREAD

**Issue by sirbig** [cedrozor/myrtille#85]
Hi,

Is it possible to redirect USB connection so it can be used on the remote server?
If it's not integrated with Myrtille, can you suggest any alternatives?

**Comment by cedrozor** [comment]
Hi, no it would be difficult to do that with just a browser and no plugin. You can still upload your usb content to the server (with the file upload button) then use it from there.

**Comment by sirbig** [comment]
The purpose of this would be to redirect a smart card to the RDP server so it can be used server side.
It's for internal use so using plugins is an option.

**Comment by cedrozor** [comment]
The good news is that FreeRDP 2.0 improved alot the smartcard management; but I don't intend to develop plugins for myrtille (that said, I'm open to specific developments, non open source).
