### ISSUE TITLE
Error 1001 on installing on SBS2008 - certificate issue

### ISSUE THREAD

**Issue by helpmewill** [cedrozor/myrtille#86]
Hi,

Just tried to install this on an old SBS2008 server, which is as far as I know is essentially a Windows Server 2008 (not R2), and couldn't complete the setup due to the following error:

Product: Myrtille -- Error 1001. Error 1001. CertEnroll::CX509Enrollment::CreatePFX: The requested property value is empty. 0x80094004 (-2146877436).

Evidently it has an issue with the installation of the certificate. If this isn't fixable, is there a way to bypass installing the certificate, so I can add one afterwards?

Thanks.

**Comment by cedrozor** [comment]
Hi,

It seems that the SBS2008 is missing the COM object CertEnroll. You can disable the self-certificate creation by disabling the following [code](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/WebInstaller.cs#L73) into the myrtille installer:

```
                // create a self signed certificate
                var cert = CertificateHelper.CreateSelfSignedCertificate(Environment.MachineName, "Myrtille self-signed certificate");

                // bind it to the default website
                IISHelper.BindCertificate(cert);
```

and also this [code](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/WebInstaller.cs#L139):

```
                // retrieve the myrtille self signed certificate
                var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
                store.Open(OpenFlags.ReadWrite);
                var certs = store.Certificates.Find(X509FindType.FindByIssuerName, Environment.MachineName, false);
                if (certs.Count > 0)
                {
                    foreach (var cert in certs)
                    {
                        if (cert.FriendlyName == "Myrtille self-signed certificate")
                        {
                            // unbind it from the default website
                            IISHelper.UnbindCertificate(cert);

                            // remove it
                            store.Remove(cert);

                            // normally, there should be only one myrtille self-signed certificate, but let's check further (just in case)...
                            //break;
                        }
                    }
                }

                store.Close();
```
