### ISSUE TITLE
Auto disconnect

### ISSUE THREAD

**Issue by c-lillini** [cedrozor/myrtille#88]
Hi,
is there a way to close rdp session automatically at browser closing without click "Disconnect" button?
I found a lot of active connection in my server.

Thank you!

**Comment by cedrozor** [comment]
Hi,
Yes, you can either:

- Click the user logout option (next to restart, shutdown, switch user, etc; the difference with disconnect is that your session is closed and won't we able to reconnect it afterward)
- Set a low disconnection time, through RDS configuration or a registry tweak on the rdp server ([MaxDisconnectionTime](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Setup/RDPSetup.reg#L18), or just import the whole RDSetup.reg file on the rdp server if it fits your needs).
