### ISSUE TITLE
Does not connect to an RDS Farm

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#89]
I am trying to access a SessionHost server from an RDS farm. I am putting the RD Connection Broker address in the server parameter, but I am not being directed to a Session Host server, but I am accessing the RD Connection Broker server itself instead of a session host. Do I need to do any more configuration for Myrtille to identify that I am accessing an RDS farm?

**Comment by welsonplay** [comment]
I think this is the same problem issue # 76, because I can connect using an IP (internal and external), but when I use a domain name Myrtille could not connect. From what I understood from issue # 76, this problem was fixed in version 1.7.0, but I'm using that version and the problem continues. can anybody help me?

**Comment by cedrozor** [comment]
Hi,

To workaround an issue into the latest FreeRDP code (which may be related to OpenSSL, I'm not sure), myrtille 1.7.0 does translate FQDN and NETBIOS names into IP addresses (IPv4 or IPv6, depending on the network), when connecting a session host directly or through a connection broker redirect.

To achieve that (resolving the target IP), the myrtille machine must be part of the same domain as the target (session host or connection broker) or, at least, the myrtille machine DNS configuration (primary or secondary) should point to the Domain Controller.

**Comment by welsonplay** [comment]
The problem was that I was placing the Broker IP and not the RDS Farm domain. I followed the steps in this article to create an RDS farm and are now redirecting correctly.

https://ryanmangansitblog.com/2013/03/30/create-a-rdsh-farm-rds-2012-using-dns-round-robin/
