### ISSUE TITLE
Keyboard not working on Ubuntu

### ISSUE THREAD

**Issue by JonasDbt** [cedrozor/myrtille#92]
I'm trying to connect to a hyper-v virtual machine with ubuntu on. The connection itself works, but the keyboard doesn't seem to work. Connecting to a windows virtual machine works great. 
But when connecting to the ubuntu vm, the keys are not transmitting correct. Not 1 key is sending the correct 'keystroke'.

Is this a known problem? Could this be solved?

**Comment by cedrozor** [comment]
Do you try to connect an xrdp server on the ubuntu machine? I didn't tested myrtille extensively with it (mainly windows servers). For the keyboard issue, you can pop the on screen keyboard (osk.exe), it's also convenient on touchscreen devices.

**Comment by cedrozor** [comment]
osk.exe is for windows; for ubuntu: https://help.ubuntu.com/stable/ubuntu-help/keyboard-osk.html

**Comment by JonasDbt** [comment]
Ok, So to be a bit clearer. I altered the service a bit to connect to the console of a hyper-v VM. For windows VM's this works great. I even have a pfsense machine where everything works fine. But for the ubuntu the keyboard is messed up. When I press the numpad '1' key, 'n' is printed to the ubuntu VM. My ubuntu is a commandline server so the onscreen keyboard won't work I'm afraid. 
I'm thinking it could have something to do with the 'JSKeyCodeToRDPScanCodeMapping'? But I'm not sure.

**Comment by cedrozor** [comment]
It's surprising there is a different scancode mapping for ubuntu (I though it was normalized for rdp). I will investigate that, thanks for the report.

**Comment by JonasDbt** [comment]
I've got it almost working. Only the Alt-Gr isn't working. Sending Alt + Control isn't an option. When I do that I get ^[@ instead of the @ character. 
For an azerty keyboard the @ is typed by pressing Alt-Gr + "2". On our linux distrubution this works. But Ctrl + Alt + 2 gives ^[@. 

By using sudo showkey I saw that the keycode for alt-gr=100. So I send K100-1, U3-1 through the pipes. But the K100 is never received. Any idea?

**Comment by cedrozor** [comment]
Hi, you just spotted an oversight into the [mapping table](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/JSKeyCodeToRDPScanCodeMapping.cs) :) the right alt (AltGr) is not mapped!

When looking at https://www.vmware.com/support/ws55/doc/ws_devices_keymap_vscan.html, we see the right alt scancode is 0x138 (hex), so 312 (decimal). There is just to find the javascript keycode associated with AltGr and add the mapping into the table; I'll look into that!

**Comment by cedrozor** [comment]
Ok, that was fast. There is something special about this key; have a look to https://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press/18570096 and https://stackoverflow.com/questions/8562528/is-there-a-way-to-detect-which-side-the-alt-key-was-pressed-on-right-or-left.

Even this (nice) little tool http://keycode.info/ gets fooled and detect the same code (18) for left and right alt.

So, it seems like there is a tweak to do into the [keyboard javascript code](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/user/keyboard.js#L85), according to https://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press/18570096#18570096, to handle that AltGr key. I'll do that.

**Comment by cedrozor** [comment]
It works well under Windows with Chrome and Firefox... I have to setup an Ubuntu client for further tests

**Comment by cedrozor** [comment]
It happens to be linked to the keyboard layout/language installed on your remote server. Myrtille uses by default a QWERTY/US (latin) mapping, and I don't plan to implement any charset existing on the planet! :p please try to add a QWERTY/US keyboard on your remote server and select it on connect, it should work.

**Comment by mapl** [comment]
Perhaps implementing the most common keybaord layouts will fix it for most ppl

**Comment by cedrozor** [comment]
Yes, but the problem is the keyboard layout of the remote server is not exposed to FreeRDP (or I didn't found how to retrieve it anyway), so I can't map it acordingly on the gateway. That's why I went to the QWERTY/US layout, which is most common.
