### ISSUE TITLE
RDS session stream slow

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#93]
I installed Myrtille and pointed it to an RDS farm, but I find the stream from the RDS session very slow, and at times the screen is blurry and slow to render. I set the imageQuality and imageQuantity to 80 to see if it improves, but unfortunately it is still slow. Anyone have an idea of what might be happening or is this expected slowness?

**Comment by cedrozor** [comment]
Are your machines (myrtille gateway, rdp brokers and hosts) resources good enough? I noticed lately on my 2012 and 2016 machines the **tiworker.exe** process (windows updates) was taking 100% CPU, during a long time.

Also, you can try to ping the rdp brokers and hosts from the myrtille gateway to see if there isn't a network issue.

**Comment by welsonplay** [comment]
the weird one that accessing by RdWeb via Windows RDP client. No, this drilling problem, but that is not used by Myrtillo.

Does myrtille require how much of an internet link?

**Comment by cedrozor** [comment]
Each myrtille session uses about 20KB/sec bandwidth with the browser. 

RDWeb works a bit differently by making the rdp connection directly from the end user machine (through the mstsc ActiveX), while myrtille makes the rdp connection from the machine it's installed on (the gateway). Does the gateway have enough available resources (CPU, RAM, etc.)?

**Comment by welsonplay** [comment]
CPU consumption is less than 10% and memory is 50%. My server is having more than one resource. I'll check if it's any networking problem or latency.

**Comment by cedrozor** [comment]
Last time I checked myrtille through internet was some time ago, but it worked exactly the same as intranet;  could you ask on the myrtille forum ? there are some peope here using myrtille for their external customers and they didn't reported me any issue.

**Comment by cedrozor** [comment]
Did you checked the network connection? I didn't tested much on azure but the last time I did it was good and no one reported me anything since.

**Comment by SieldP** [comment]
Hi welsonplay,

Did you solve the it ? If yes, can you tell how you did ? I have the same probleme. I am using Myrtille trought internet (upload/download : ~5-6 MB/s for both connections),CPU / RAM usage less than 50% and the session stream is very slow. Can't do anythink. Through an classic rdp session (mstsc.exe) the session is good.
Myrtille is installed on Windows 8.1 with websocket protocol enabled.

Thank you

**Comment by cedrozor** [comment]
There is no difference between myrtille on-premise and internet beside the network layer. Windows 7 (IIS7.5) doesn't support websockets, so it might explain the slowness; but Azure shoud host Windows Servers 2012 or 2016 (is that the case welsonplay?), so with websockets support (IIS8+). But the **websocket protocol is not enabled by default under IIS** (see the [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#installation)), so please enable it if you don't.

That said, there are many pieces of network equipment that can filter/cache the websocket protocol (and thus slow the stream), so this should also be checked. A ping could indicate a small latency but it's raw tcp and is not processed the same way as http or ws.

You can **enable on-screen stats, debug and compatibility modes** into [Default.css](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/css/Default.css#L147). That will provide you 3 new buttons into the toolbar to help you identify the issue.

Just comment out the css, as below, and refresh the page (F5):

```
/*
#stat,
#debug,
#browser
{
    visibility: hidden;
    display: none;
}
*/
```

**Comment by SieldP** [comment]
Thank for your anwser.
![scmyrtillestat](https://user-images.githubusercontent.com/24812575/36876580-fc98a396-1db5-11e8-90ed-9eeefb630e6f.png)

Here's stats during a Myrtille session. As you can see, I think that I have a problem with de bandwith detection (0/0). However, the session stream work, but it's very slow.
I can't use an other Windows version than Win 7. So I can't try with WS protocol. Howerver, when I install Myrtille in my home (win 7 too), and I limit the connection to simulate the same latency than this server, Myrtille session is much better and the bandwith is detected is stats :/
Any idea ?
Thank you

**Comment by didimomonteiro** [comment]
I'm trying to change the image quality through the config.js file

But we can not make a connection. continuous quality 100% and encodig PNG 

![image](https://user-images.githubusercontent.com/51522576/59154480-89c2c700-8a49-11e9-8b93-bc3a73074bf2.png)

![image](https://user-images.githubusercontent.com/51522576/59154487-b7a80b80-8a49-11e9-96c4-765e03457e32.png)
