### ISSUE TITLE
Hide session ID in URL

### ISSUE THREAD

**Issue by davemail** [cedrozor/myrtille#94]
Hello,

First of all, thank you very much for this great tool.

I was just wondering, if it would be possible to hide the session ID somehow (for example cookies). If someone takes a picture of my screen with a smartphone, she could easily steal my running session and I can do nothing to hinder others from disturbing my precious work :)

Thank you.

Best wishes,

David

**Comment by cedrozor** [comment]
Hi David,

Yes of course, you can hide it by enabling cookies. I disabled them in order for myrtille to work in a private/incognito browsing window (cookieless). But, indeed, if someone behind you take a picture of your screen, you would share the same session (that could be for a collaborative work btw).

To enable cookies, just edit the [web.config](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L53) file (into the myrtille install folder) as below: 
Replace `<sessionState mode="InProc" cookieless="UseUri" timeout="20"/>`
By `<sessionState mode="InProc" timeout="20"/>`

Please note that cookies are set for a domain, so you won't be able to have multiple sessions/tabs under this configuration. 

Cedric

**Comment by davemail** [comment]
Bonjour Cedric,

Excellent, that worked like a charm! Now we are ready to go live with "Browser-RDP" before MS launches the official html5 preview ;)

Again, thank you very much for your support and your great program!


Best wishes,

David
