### ISSUE TITLE
Enable file button

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#95]
The file button is locked. How can I enable this button?
Can I download and upload files for my session using the Myrtillhe Files button?

**Comment by cedrozor** [comment]
The files button is enabled if both myrtille and the rdp server are on the same machine (localhost) or if the rdp server is member of a domain (and you specified it on connect). This is enforced to work with local and roaming accounts, respectively.

**Comment by welsonplay** [comment]
The Myrtille server is in the same domain as the Session Host Farm VMs, but the button is disabled. Do you need to set up any specific permissions?

**Comment by cedrozor** [comment]
No; the domain just needs to be specified on connect
