### ISSUE TITLE
Ctrl + C and Ctrl + V

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#98]
Has anyone come to implement Ctrl + C and Ctrl + V without having to use Mytille's clipboard and keyboard?

**Comment by welsonplay** [comment]
Chrome

**Comment by cedrozor** [comment]
Back in days, access to the clipboard was forbidden to the browsers (as a security measure); I'll check know if things have changed... I know there are some workarounds/hacks and access to the clipboard may be allowed for write operations (that you need).

**Comment by welsonplay** [comment]
I'll check and notice here it worked. Many thanks @cedrozor.

**Comment by p33kabo0** [comment]
Cedrozor, have you ever checked this Clipboard-API for the clipboard?

https://www.w3.org/TR/clipboard-apis/

And I'm not able to make the clipbard work with the Myrtille menu ...
